#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("Which logic gate is known as a 'universal gate' because any Boolean logic function can be constructed using exclusively this gate type?",
     ["AND", "OR", "NAND", "XOR"], 2,
     "NAND (and NOR) are universal gates capable of implementing any arbitrary Boolean combinational function without any other gate types.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the primary architectural difference between the Von Neumann architecture and the Harvard architecture?",
     ["Von Neumann shares a single memory and bus for both instructions and data, whereas Harvard has separate physical memories and buses for instructions and data", "Harvard uses only 8-bit registers", "Von Neumann does not use an ALU", "Harvard does not support pipelining"], 0,
     "Von Neumann utilizes a unified memory bus for instructions and data (leading to the Von Neumann bottleneck); Harvard isolates instruction and data pathways.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In pipelined CPU architectures, what is a Read-After-Write (RAW) hazard also known as?",
     ["True Data Dependency", "Anti-Dependency", "Output Dependency", "Structural Hazard"], 0,
     "RAW is a true data dependency where an instruction requires the result of a preceding in-flight instruction before that result has been written back.", "Medium", "Computer Architecture", "Previous Exam"),
    ("Which technique allows a pipelined CPU to pass the output of an ALU operation directly to the input of a subsequent instruction's execution stage without waiting for memory write-back?",
     ["Branch Prediction", "Operand Forwarding (Bypassing)", "Loop Unrolling", "Register Renaming"], 1,
     "Operand Forwarding routes execution results directly from pipeline stage latches to dependent ALU inputs, resolving RAW hazards without stalling.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the difference between Big-Endian and Little-Endian byte ordering in computer memory?",
     ["Big-Endian stores the most significant byte (MSB) at the lowest memory address, whereas Little-Endian stores the least significant byte (LSB) at the lowest address", "Big-Endian is only used on 64-bit systems", "Little-Endian compresses numbers automatically", "Big-Endian stores numbers in reverse binary"], 0,
     "In Big-Endian, the highest-order byte is placed first at the smallest address; in Little-Endian (e.g., x86), the lowest-order byte is placed at the smallest address.", "Easy", "Computer Architecture", "Previous Exam"),
    ("In a direct-mapped cache, how is a physical memory address divided to locate a byte in cache?",
     ["Tag, Index (Set), and Block Offset", "Page number and Frame offset", "Segment selector and Displacement", "Bus address and Sector ID"], 0,
     "Memory addresses map to cache via: Block Offset (byte within cache line), Index (cache line row), and Tag (distinguishes memory blocks mapping to the same line).", "Medium", "Computer Architecture", "Previous Exam"),
    ("What are the 'Three Cs' of cache misses in computer architecture?",
     ["Compulsory (Cold), Capacity, and Conflict", "Critical, Concurrent, and Cyclic", "Code, Context, and Core", "Clock, Cache, and CPU"], 0,
     "Mark Hill's 3 Cs classify misses: Compulsory (first access to a block), Capacity (cache is too small to hold working set), and Conflict (collision in direct/set-associative mapping).", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the purpose of Direct Memory Access (DMA) in computer systems?",
     ["Allows high-speed I/O devices to transfer data directly to and from main memory without continuous CPU intervention", "Speeds up arithmetic multiplication in the ALU", "Directly connects two graphics cards", "Bypasses RAM to write straight to tape"], 0,
     "DMA controllers offload bulk data transfers between peripherals and memory, interrupting the CPU only when the entire block transfer completes.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What does the Program Counter (PC) register hold in a central processing unit?",
     ["The memory address of the next instruction to be fetched and executed", "The count of clock cycles elapsed since boot", "The result of the latest ALU calculation", "The current process ID"], 0,
     "The Program Counter (Instruction Pointer) points to the address of the next instruction waiting in memory to be fetched.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the difference between SRAM (Static RAM) and DRAM (Dynamic RAM)?",
     ["SRAM uses bistable latching flip-flops and needs no refresh cycles (faster, used in caches); DRAM stores bits on capacitors and requires periodic electrical refreshing (denser, used in main memory)", "SRAM requires continuous refreshing", "DRAM is faster than SRAM", "SRAM is non-volatile flash memory"], 0,
     "SRAM holds data statically via transistor cross-coupled inverters (fast, expensive); DRAM stores charge on tiny capacitors requiring continuous refresh cycles.", "Easy", "Computer Architecture", "Previous Exam"),

    # 11-20
    ("In IEEE 754 single-precision (32-bit) floating-point format, how many bits are allocated to the sign, exponent, and mantissa (fraction)?",
     ["1 sign bit, 8 exponent bits, 23 mantissa bits", "1 sign bit, 11 exponent bits, 52 mantissa bits", "2 sign bits, 6 exponent bits, 24 mantissa bits", "1 sign bit, 15 exponent bits, 16 mantissa bits"], 0,
     "IEEE 754 single-precision (float) uses: 1 bit for sign, 8 bits for exponent (with bias 127), and 23 bits for normalized mantissa.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the two's complement representation of the decimal number -5 in an 8-bit signed integer format?",
     ["11111011", "10000101", "11111010", "11110101"], 0,
     "+5 is 00000101. Inverting bits gives 11111010; adding 1 yields 11111011 (-5).", "Medium", "Computer Architecture", "Previous Exam"),
    ("In digital logic, what is a Half Adder circuit capable of performing?",
     ["Adding two 1-bit binary numbers, producing a Sum and a Carry output, without accommodating an incoming carry from previous stages", "Adding two 32-bit floating numbers", "Multiplying two 4-bit numbers", "Dividing binary numbers by two"], 0,
     "A Half Adder computes Sum = A XOR B and Carry = A AND B for two inputs, lacking a Carry-in input required for chaining.", "Easy", "Computer Architecture", "Previous Exam"),
    ("How does a Full Adder differ from a Half Adder?",
     ["A Full Adder accepts three 1-bit inputs: two operands (A and B) and an incoming Carry-in (Cin)", "A Full Adder can add negative numbers only", "A Full Adder has three outputs", "A Full Adder uses analog amplifiers"], 0,
     "A Full Adder adds three 1-bit inputs (A, B, Cin) producing Sum and Carry-out, allowing multiple adders to cascade for multi-bit addition.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the primary advantage of a Carry Lookahead Adder (CLA) over a simple Ripple Carry Adder (RCA)?",
     ["It calculates carry bits in advance using Generate and Propagate logic, eliminating long propagation delays across cascaded stages", "It requires 90% fewer logic gates", "It converts binary to decimal automatically", "It consumes zero electrical power"], 0,
     "RCA propagates carry serially in O(N) time; CLA calculates carries in parallel using propagate (P) and generate (G) logic in O(log N) time.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is a Multiplexer (MUX) in combinational digital circuits?",
     ["A circuit that selects one of several analog or digital input signals and forwards the selected input into a single line based on control select lines", "A circuit that multiplies numbers by two", "A circuit that stores 100 bytes of data", "A circuit that amplifies audio signals"], 0,
     "A 2^n-to-1 multiplexer routes one of its 2^n input channels to a single output based on the binary state of n select lines.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the difference between a Mealy machine and a Moore machine in sequential state machine design?",
     ["In a Moore machine, outputs depend solely on the current state; in a Mealy machine, outputs depend on both current state and current inputs", "Mealy machines have no clock signal", "Moore machines have no state registers", "Mealy machines only produce binary zeros"], 0,
     "Moore state machine outputs are purely functions of the current state; Mealy outputs depend on current state plus immediate external inputs.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the 'race-around condition' in an SR or JK flip-flop?",
     ["When the clock pulse duration is longer than the propagation delay of the flip-flop and J=1, K=1, causing the output to toggle repeatedly within a single clock pulse", "Two CPUs racing to access RAM", "A short circuit in the power supply", "A buffer overflow in the register"], 0,
     "The race-around condition occurs in level-triggered JK flip-flops when clock high duration exceeds gate delay, causing continuous toggling.", "Medium", "Computer Architecture", "Previous Exam"),
    ("How is the race-around condition typically eliminated in flip-flop circuit design?",
     ["By using Master-Slave flip-flop architectures or edge-triggered clock inputs", "By disconnecting the ground wire", "By using only NOR gates", "By lowering the voltage to zero"], 0,
     "Master-Slave setups or edge-triggering isolate input sampling from output updates, ensuring states toggle at most once per clock transition.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In Boolean algebra, what is De Morgan's First Law?",
     ["NOT (A AND B) = (NOT A) OR (NOT B)", "NOT (A OR B) = (NOT A) OR (NOT B)", "A AND (B OR C) = (A AND B) OR C", "A AND A = 0"], 0,
     "De Morgan's first theorem states that the complement of a conjunction is the disjunction of the complements: !(A * B) = !A + !B.", "Easy", "Computer Architecture", "Previous Exam"),

    # 21-30
    ("What is De Morgan's Second Law in Boolean algebra?",
     ["NOT (A OR B) = (NOT A) AND (NOT B)", "NOT (A AND B) = (NOT A) AND (NOT B)", "A OR 0 = 0", "A AND 1 = 0"], 0,
     "De Morgan's second theorem states that the complement of a disjunction is the conjunction of the complements: !(A + B) = !A * !B.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a Karnaugh Map (K-map) used for in digital logic design?",
     ["A visual method for minimizing Boolean algebraic expressions and finding minimal Sum-of-Products (SOP) forms without complex algebraic factoring", "Mapping internet router paths", "Designing CPU heat sinks", "Visualizing database ER models"], 0,
     "K-maps organize truth tables into Gray-code grids where adjacent cells differ by only one bit, facilitating visual Boolean minimization.", "Easy", "Computer Architecture", "Previous Exam"),
    ("Why are adjacent cells in a Karnaugh Map arranged in Gray code sequence (00, 01, 11, 10) rather than standard binary (00, 01, 10, 11)?",
     ["To ensure that adjacent horizontal and vertical cells differ by only a single binary variable", "To make arithmetic addition faster", "Because binary 11 cannot be converted to logic gates", "To prevent electromagnetic interference"], 0,
     "Gray code ordering guarantees unit Hamming distance between adjacent cells, allowing common terms to factor out via A + !A = 1.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a 'Don't Care' condition (denoted by X or d) in a Karnaugh Map?",
     ["An input combination that is physically impossible or whose output value does not matter, which can be grouped as 0 or 1 to optimize minimization", "An error in the digital simulation", "A gate that has blown a fuse", "A disconnected jumper wire"], 0,
     "Don't Care conditions allow logic designers the freedom to treat unspecified outputs as 1 or 0 to form larger rectangular grouping loops in K-maps.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What characterizes RISC (Reduced Instruction Set Computer) architectures compared to CISC?",
     ["Simple, fixed-length instructions, load-store architecture where only load/store instructions access memory, and a large register set", "Complex variable-length instructions executing multi-step memory operations directly", "Absence of pipelining support", "Only 4-bit data buses"], 0,
     "RISC designs focus on simple, single-cycle, uniform-length instructions operating strictly on registers (Load/Store architecture).", "Easy", "Computer Architecture", "Previous Exam"),
    ("What characterizes CISC (Complex Instruction Set Computer) architectures (such as x86)?",
     ["A rich variety of specialized, variable-length instructions that can perform complex multi-clock operations and access memory operands directly", "Fixed 32-bit instructions only", "Lack of microcode", "Strict requirement for compiler optimization"], 0,
     "CISC architectures provide hardware-implemented complex instructions (e.g., string copies, arithmetic directly in memory) to minimize code size.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a Write-Through cache write policy?",
     ["Data is written simultaneously to both the cache and underlying main memory on every write operation", "Data is written only to cache and written to main memory upon eviction", "Writes bypass the cache completely", "Data is written to tape backup"], 0,
     "Write-Through updates both cache and main RAM on every write, ensuring RAM is always consistent but increasing bus traffic.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a Write-Back (Copy-Back) cache write policy?",
     ["Data is written only to the cache line and marked with a dirty bit; it is written to main memory only when the dirty cache line is evicted", "Data is written to main memory immediately", "Data is discarded after 10 milliseconds", "Writes are sent over the network"], 0,
     "Write-Back modifies RAM only when a dirty line is evicted, drastically reducing bus bandwidth requirements at the cost of transient RAM incoherency.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the MESI protocol used for in multi-core CPU architectures?",
     ["Maintaining cache coherency across multiple CPU core caches using states: Modified, Exclusive, Shared, and Invalid", "Measuring CPU energy consumption", "Encrypting memory channels", "Routing packets between chipsets"], 0,
     "MESI is an invalidation-based cache coherency protocol ensuring all cores maintain consistent views of shared memory addresses.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is the difference between Memory-Mapped I/O and Port-Mapped (Isolated) I/O?",
     ["Memory-Mapped I/O shares the same address space and machine instructions for memory and peripherals; Port-Mapped I/O uses dedicated I/O address space and special CPU instructions (e.g., IN/OUT)", "Memory-Mapped I/O is for disks; Port-Mapped is for keyboards", "Port-Mapped I/O cannot transfer data", "They are identical in modern CPUs"], 0,
     "Memory-Mapped I/O maps device registers to standard RAM addresses (used in ARM); Port-Mapped uses separate buses and dedicated instructions (x86 IN/OUT).", "Medium", "Computer Architecture", "Previous Exam"),

    # 31-40
    ("What is the Instruction Register (IR) in a CPU?",
     ["A register that holds the current instruction while it is being decoded and executed", "A register that stores the stack pointer", "A register that stores ALU status flags", "A register containing memory addresses"], 0,
     "Once fetched from memory via the MDR, the binary instruction opcode and operands reside in the Instruction Register during decoding.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the Memory Address Register (MAR)?",
     ["A CPU register that holds the memory address from which data will be fetched or to which data will be written", "A register holding instruction opcodes", "A register tracking CPU temperature", "A register storing floating point exponents"], 0,
     "The MAR connects directly to the address bus, specifying the physical RAM location targeted by read/write operations.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the Memory Buffer Register (MBR) or Memory Data Register (MDR)?",
     ["A register that holds the data read from memory or the data waiting to be written to memory via the data bus", "A register that counts instructions", "A register storing the BIOS date", "A cache for mouse movements"], 0,
     "The MDR/MBR connects to the data bus, acting as an electrical staging buffer between memory and internal CPU registers.", "Easy", "Computer Architecture", "Previous Exam"),
    ("In CPU flags, what does the Carry flag (C) indicate?",
     ["An arithmetic overflow occurred out of the most significant bit during unsigned integer addition or subtraction", "A negative number was produced in signed math", "The result was exactly zero", "A divide by zero error occurred"], 0,
     "The Carry flag detects unsigned arithmetic overflows (or borrows in subtraction) past the maximum bit width of the ALU register.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What does the Overflow flag (V or OF) indicate in ALU status registers?",
     ["A signed arithmetic overflow occurred where the sign of the result is incorrect because the value exceeded signed range capacity", "An unsigned number was too small", "Memory bus was disconnected", "Cache missed"], 0,
     "The Overflow flag indicates an erroneous sign inversion resulting from signed two's complement addition/subtraction (e.g., positive + positive = negative).", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is Immediate Addressing mode in assembly language?",
     ["The operand value is specified directly within the instruction itself (e.g., MOV R1, #42)", "The operand is located at an address in RAM", "The operand is pointed to by a pointer in memory", "The operand is read from disk"], 0,
     "In Immediate addressing, the actual data value is encoded directly into the instruction bytes, requiring no additional memory lookups.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is Register Indirect Addressing mode?",
     ["The instruction specifies a register that contains the memory address of the operand (e.g., MOV R1, [R2])", "The operand is stored in register R1", "The instruction uses immediate constants", "The register stores the opcode"], 0,
     "Register Indirect uses the value inside a CPU register as an effective memory address pointer to fetch data from RAM.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the purpose of an Interrupt Service Routine (ISR)?",
     ["A specialized software routine executed by the CPU in response to a hardware or software interrupt to handle the triggering event", "A routine that compiles assembly code", "A function that cleans the hard drive", "A routine that installs operating system updates"], 0,
     "When an interrupt signals, the CPU saves its context, looks up the vector table, and branches to the ISR handler.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a Vectored Interrupt?",
     ["An interrupt scheme where the interrupting device supplies an interrupt vector number to direct the CPU to the specific ISR in memory", "An interrupt that uses vector graphics", "An interrupt caused by GPU shaders", "An unmaskable power failure"], 0,
     "Vectored interrupts pass an identification index on the data bus, allowing the CPU to jump straight to the device's handler in the vector table.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the Non-Maskable Interrupt (NMI)?",
     ["A critical hardware interrupt that cannot be ignored or disabled by CPU software masking instructions, reserved for catastrophic faults (e.g., parity error, power fail)", "An interrupt generated by a mouse click", "An interrupt that can be delayed for 1 hour", "A user typing on the keyboard"], 0,
     "NMIs bypass interrupt enable/disable flags to ensure immediate CPU response to catastrophic events like hardware memory parity errors.", "Medium", "Computer Architecture", "Previous Exam"),

    # 41-50
    ("What is Superscalar architecture in modern microprocessors?",
     ["A CPU design that can execute more than one instruction per clock cycle by dispatching multiple instructions to redundant execution units", "A CPU with a clock speed above 10 GHz", "A CPU submerged in liquid nitrogen", "A CPU containing only GPUs"], 0,
     "Superscalar processors employ instruction-level parallelism (ILP) with multiple parallel pipelines and ALUs, achieving IPC > 1.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the Tomasulo Algorithm used for in CPU design?",
     ["Dynamic instruction scheduling enabling out-of-order execution while tracking register dependencies using reservation stations and a common data bus", "A sorting algorithm for RAM", "An instruction compression algorithm", "A power management governor"], 0,
     "Robert Tomasulo's algorithm resolves WAR and WAW hazards dynamically via register renaming and reservation stations, enabling out-of-order completion.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is Branch Prediction in modern pipelined processors?",
     ["Speculative logic that guesses the outcome of conditional branches (taken vs not taken) before the branch condition is evaluated to keep pipelines full", "Predicting tree growth in biology", "Guessing user mouse movements", "Calculating hard drive seek time"], 0,
     "Branch predictors guess branch direction and target addresses to avoid pipeline flushes (bubbles) caused by control hazards.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a 2-bit Saturating Counter used for in dynamic branch prediction?",
     ["A state machine with states Strongly Taken, Weakly Taken, Weakly Not Taken, Strongly Not Taken that requires two consecutive mispredictions to flip prediction", "Counting binary bits in 2-bit bytes", "Measuring clock frequencies", "Tracking cache misses"], 0,
     "A 2-bit saturating counter tolerates occasional loop anomalies (such as loop exit) without prematurely changing the general branch prediction.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is a Branch Delay Slot in architectures like MIPS?",
     ["An instruction slot immediately following a branch that is always executed regardless of whether the branch is taken or not", "A pause where the CPU stops for 10 cycles", "A physical slot on the motherboard", "A register holding the target address"], 0,
     "Classic RISC ISAs (like MIPS) expose the pipeline delay by always executing the single instruction following a branch instruction.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is Register Renaming designed to eliminate in out-of-order execution pipelines?",
     ["False data dependencies (WAR - Write-After-Read and WAW - Write-After-Write) caused by a limited number of architectural registers", "True RAW dependencies", "Memory page faults", "TLB misses"], 0,
     "Register renaming maps architectural registers to a larger pool of physical registers, removing artificial name dependencies (WAR/WAW).", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is the Reorder Buffer (ROB) in modern out-of-order execution processors?",
     ["A circular buffer that ensures instructions that execute out of order are committed and retired strictly in original program order", "A buffer that reorders network packets", "A disk cache for hard drives", "A keyboard key queue"], 0,
     "The ROB allows instructions to execute speculatively and out of order while guaranteeing in-order retirement, preserving precise interrupt semantics.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is SIMD (Single Instruction, Multiple Data) processing?",
     ["A parallel computing architecture where a single instruction operates simultaneously on multiple data elements packed into vector registers", "A CPU with only one single register", "A database query executed across multiple tables", "An operating system without multitasking"], 0,
     "SIMD (e.g., SSE, AVX, NEON) applies vector operations to packed arrays of integers or floats in a single clock cycle.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is Hyper-Threading (Simultaneous Multithreading - SMT)?",
     ["A technology allowing a single physical CPU core to appear as two logical processors to the OS by duplicating architectural state registers while sharing execution units", "Running two operating systems in virtual machines", "Overclocking CPU clock frequencies", "Using two power supplies on one PC"], 0,
     "SMT shares execution units and caches among multiple thread execution contexts, hiding memory latency and boosting core utilization.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the Von Neumann Bottleneck?",
     ["The throughput limitation caused by the shared bus between the CPU and memory, where instruction fetches and data accesses must compete for the same bus", "A slow computer keyboard", "A bottleneck caused by small hard drives", "A cooling fan failure on the CPU"], 0,
     "Because data and programs share the same physical bus in Von Neumann systems, memory throughput severely throttles CPU processing performance.", "Medium", "Computer Architecture", "Previous Exam"),

    # 51-60
    ("What is an instruction cycle's traditional sequence of phases?",
     ["Fetch -> Decode -> Execute -> Memory Access -> Write Back", "Code -> Test -> Build -> Deploy", "Read -> Sort -> Delete", "Boot -> Connect -> Print"], 0,
     "The classic instruction pipeline consists of: Instruction Fetch (IF), Instruction Decode (ID), Execution (EX), Memory Access (MEM), and Write Back (WB).", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is microcode in CISC processors?",
     ["A layer of low-level hardware instructions stored in internal ROM that translates complex machine instructions into a sequence of simple micro-operations", "A very small C program", "Source code written in assembly", "A bug in the CPU instruction decoder"], 0,
     "Microcode decodes complex CISC assembly instructions into sequences of primitive hardware micro-ops executed by underlying execution units.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a Hardwired Control Unit as opposed to a Microprogrammed Control Unit?",
     ["A control unit implemented using fixed combinational logic gates and flip-flops, offering faster execution speeds at the expense of inflexibility", "A control unit made of vacuum tubes", "A control unit programmed in Python", "A control unit connected with physical wires to the monitor"], 0,
     "Hardwired control units generate control signals via combinational logic gates, delivering high clock frequencies typical of RISC chips.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In assembly language, what is the Stack Pointer (SP) register used for?",
     ["Stores the memory address of the current top of the call stack (used for local variables, return addresses, and saved registers)", "Points to the next instruction in memory", "Points to the base of the heap", "Holds the return value of a function"], 0,
     "SP points to the active top element of the LIFO call stack, incrementing or decrementing during PUSH and POP instructions.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What does the Base Pointer (BP or Frame Pointer FP) typically maintain in standard calling conventions?",
     ["A fixed reference anchor address pointing to the base of the current function's stack frame to access parameters and local variables reliably", "The base address of the hard drive", "The start address of the operating system kernel", "The primary key of the process table"], 0,
     "The Frame Pointer anchors the active stack frame, providing constant offsets to function arguments and local variables even as the SP fluctuates.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the x86 C calling convention (cdecl)?",
     ["Function arguments are pushed onto the stack in right-to-left order, the caller cleans up the stack, and return values are passed in EAX/RAX", "Arguments are passed via registers only and callee cleans stack", "Arguments are passed via global variables", "The return value is pushed onto the stack"], 0,
     "Under cdecl, parameters are pushed right-to-left, caller pops arguments off the stack after the call returns, and integer results reside in EAX.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is Sign Extension in binary computer arithmetic?",
     ["Increasing the bit width of a signed two's complement number by copying its most significant bit (sign bit) into all new upper bit positions", "Adding a minus sign character to a string", "Converting positive numbers to negative", "Multiplying a number by -1"], 0,
     "Sign extension widens a signed integer (e.g., 8-bit to 16-bit) while preserving its numerical value and sign by replicating the MSB.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the difference between an Arithmetic Right Shift and a Logical Right Shift?",
     ["Arithmetic shift preserves the sign bit by shifting in copies of the sign bit on the left; Logical shift always shifts in zeros on the left", "Logical shift only works on floats", "Arithmetic shift multiplies by 2", "There is no difference in binary shifts"], 0,
     "Logical right shift inserts 0s (for unsigned numbers); arithmetic right shift replicates the MSB, preserving the negative sign for signed division by 2.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a D flip-flop (Data flip-flop)?",
     ["A clocked flip-flop that captures the value of the D input at a specific clock edge and stores it on output Q until the next clock event", "A flip-flop with two data inputs", "A circuit that divides numbers by 10", "An analog transistor amplifier"], 0,
     "D flip-flops act as fundamental 1-bit memory cells, latching the input state D onto output Q on clock transitions.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a T flip-flop (Toggle flip-flop)?",
     ["A flip-flop whose output toggles to its complement on every clock pulse whenever input T is high (T=1)", "A flip-flop that resets to zero continuously", "A temperature-sensitive flip-flop", "A flip-flop with three clock pins"], 0,
     "T flip-flops invert their output state on active clock edges when T=1, forming the core building blocks of binary ripple counters.", "Easy", "Computer Architecture", "Previous Exam"),

    # 61-70
    ("What is the difference between a Latch and a Flip-Flop in digital electronics?",
     ["A latch is level-triggered (transparent while the enable signal is active); a flip-flop is edge-triggered (samples inputs only on clock transitions)", "Latches are analog; flip-flops are digital", "Flip-flops cannot store data", "Latches require three clock phases"], 0,
     "Latches change state continuously while their enable level is high; flip-flops only update state on the rising or falling edge of a clock signal.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the Setup Time (t_setup) of a flip-flop?",
     ["The minimum amount of time the data input must remain stable BEFORE the active clock edge arrives", "The time required to manufacture a chip", "The time to turn on the power supply", "The delay between input and output"], 0,
     "Setup time is the requisite pre-clock stability window; violating setup time causes internal circuit metastability.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the Hold Time (t_hold) of a flip-flop?",
     ["The minimum amount of time the data input must remain stable AFTER the active clock edge has arrived", "The time an output holds a high voltage", "The time a computer holds data in RAM", "The duration of the reset pulse"], 0,
     "Hold time dictates how long inputs must remain constant post-clock edge to avoid latched data corruption.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is Metastability in digital sequential circuits?",
     ["An unpredictable, quasi-stable state where a flip-flop output hovers between logic 0 and logic 1 for an indeterminate period due to setup/hold violations", "A permanent hardware short circuit", "A CPU running at double speed", "A stable power voltage"], 0,
     "Violating setup/hold times causes flip-flop internal balance points to oscillate indeterminately between valid logic levels before resolving randomly.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is a Shift Register in digital circuits?",
     ["A cascade of flip-flops sharing a common clock, where bits shift from one flip-flop to the next on each clock transition (e.g., Serial-In Parallel-Out)", "A register holding instruction offsets", "A register used exclusively by math coprocessors", "A hardware counter that resets on zero"], 0,
     "Shift registers move binary words sequentially through chains of flip-flops, converting between serial and parallel data representations.", "Easy", "Computer Architecture", "Previous Exam"),
    ("In digital logic, what is an Encoder circuit?",
     ["A combinational circuit that converts 2^n active input lines into an n-bit binary code output", "A circuit that compresses MP3 files", "A circuit that translates English into Spanish", "A circuit that decodes instruction registers"], 0,
     "An encoder takes multiple input lines (where one is high) and outputs the binary representation of that line number.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a Priority Encoder?",
     ["An encoder that produces the binary code corresponding to the highest-priority active input when multiple inputs are asserted simultaneously", "A circuit that prioritizes CPU interrupts", "A decoder with priority outputs", "A circuit that encrypts high-priority messages"], 0,
     "Priority encoders resolve simultaneous inputs by emitting the binary code of the active input assigned the greatest operational priority.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a Decoder circuit in digital logic?",
     ["A combinational circuit that converts an n-bit binary input code into 2^n unique output lines (asserting exactly one line)", "A circuit that decodes video signals", "A hardware firewall", "A circuit that adds binary numbers"], 0,
     "Decoders expand n binary inputs into 2^n output lines, commonly used for memory address decoding and multiplexer building.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a Tri-State Buffer in bus architecture?",
     ["A digital logic gate that can output High (1), Low (0), or High-Impedance (Hi-Z), allowing multiple devices to share a common bus without electrical conflict", "A buffer with three inputs", "A memory cell holding 3 bits", "An analog sound filter"], 0,
     "Tri-state buffers disconnect outputs electronically (Hi-Z / floating) when not enabled, preventing short circuits when sharing physical bus traces.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What does High Impedance (Hi-Z) mean in digital bus systems?",
     ["The output is electronically disconnected from the circuit, behaving like an open switch with virtually infinite resistance", "The output is tied directly to 5 Volts", "The circuit is drawing maximum current", "The gate is destroyed by static electricity"], 0,
     "Hi-Z effectively detaches a device pin from a shared bus wire, permitting other attached drivers to drive the bus line safely.", "Medium", "Computer Architecture", "Previous Exam"),

    # 71-80
    ("What is a Structural Hazard in a pipelined CPU?",
     ["A hardware resource conflict where two or more instructions in the pipeline need to use the exact same physical hardware unit at the same clock cycle", "A bug in the C compiler", "A crack in the silicon die", "A power outage affecting the motherboard"], 0,
     "Structural hazards occur when hardware components (e.g., a single memory port or shared ALU) cannot support simultaneous access by different pipeline stages.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a Control Hazard (Branch Hazard) in CPU pipelining?",
     ["A delay caused by the pipeline not knowing which instruction to fetch next until a conditional branch instruction resolves", "A failure of the control bus", "A crash of the operating system", "An overheating voltage regulator"], 0,
     "Control hazards arise because the target address of branch instructions is unknown during early fetch stages, requiring branch prediction or stalls.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a Data Hazard in pipelining?",
     ["A condition where an instruction depends on the data results of an earlier instruction that is still executing in the pipeline", "Data corrupted on the hard drive", "An erroneous calculation by the ALU", "A network packet dropped by a NIC"], 0,
     "Data hazards (RAW, WAR, WAW) occur when operand values cannot be read or written at expected program order intervals.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a pipeline 'Bubble' (or Stall)?",
     ["An intentional NOP (No Operation) cycle inserted into the pipeline to delay dependent instructions until a hazard clears", "A physical defect in the CPU package", "A cooling bubble in water cooling systems", "A memory leak in system software"], 0,
     "A stall suspends early pipeline stages, holding instructions stationary while allowing downstream stages to complete to resolve dependencies.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is Loop Unrolling in compiler code optimization?",
     ["A code transformation technique that expands loop iterations to decrease loop control overhead (branching and counters) and expose ILP", "A technique to stop infinite loops", "A way to convert while loops to for loops", "A method for encrypting loops"], 0,
     "Loop unrolling replicates loop bodies multiple times, amortizing branch tests and enabling instruction schedulers to interleave independent operations.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is VLIW (Very Long Instruction Word) architecture?",
     ["An architecture where the compiler packages multiple independent operations into a single wide instruction word to be executed in parallel by multiple functional units", "An instruction that accepts sentences instead of numbers", "A 1024-bit computer bus", "A text processing chip"], 0,
     "VLIW relies on compile-time static scheduling to bundle parallel operations into massive instruction words (e.g., Intel Itanium).", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is the difference between Write-Allocate and No-Write-Allocate on a cache write miss?",
     ["Write-Allocate loads the targeted block into cache before executing the write; No-Write-Allocate writes directly to lower memory without caching the block", "Write-Allocate allocates RAM memory pages", "No-Write-Allocate prevents all writes", "Write-Allocate only works on L3 cache"], 0,
     "Write-Allocate brings missing blocks into cache on write misses (typical of write-back); No-Write-Allocate bypasses cache on write misses (typical of write-through).", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is a Translation Lookaside Buffer (TLB) miss penalty?",
     ["The time overhead required for hardware or the OS page table walker to traverse in-memory hierarchical page tables to resolve a virtual address", "A hardware crash requiring a reboot", "The time taken to reboot the CPU", "The cost of buying new RAM"], 0,
     "A TLB miss triggers a page table walk across memory hierarchies, incurring multi-cycle latencies to fetch the translation into the TLB.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is an Inverted Page Table's primary advantage in 64-bit architectures?",
     ["Its size scales with the amount of physical RAM installed rather than the vast virtual address space size", "It eliminates all TLB misses", "It does not require memory protection bits", "It can be stored in CPU registers"], 0,
     "Inverted tables maintain one entry per physical frame in RAM, avoiding the massive overhead of multi-level page tables for 64-bit sparse address spaces.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is Non-Uniform Memory Access (NUMA)?",
     ["A multiprocessor architecture where memory access times depend on the memory location relative to the processor (local vs remote memory)", "A memory error causing random crashes", "A computer with odd numbers of RAM sticks", "A system without a memory controller"], 0,
     "In NUMA systems, CPUs access their own local physical memory bank faster than shared remote memory banks attached to other processor sockets.", "Medium", "Computer Architecture", "Previous Exam"),

    # 81-90
    ("What is the Memory Management Unit (MMU)?",
     ["A hardware component responsible for translating virtual memory addresses into physical RAM addresses and enforcing memory protection", "A software driver for SSDs", "A chip that formats flash drives", "A register holding the stack pointer"], 0,
     "The MMU performs on-the-fly hardware translation of virtual addresses to physical addresses using page tables and the TLB.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the purpose of an Instruction Cache (I-Cache) and Data Cache (D-Cache) split (Harvard cache architecture)?",
     ["Allows simultaneous instruction fetching and data reading/writing, eliminating structural conflicts in pipelined processors", "Stores code on tape and data on disk", "Separates user data from system data", "Encrypts instructions and data with different keys"], 0,
     "Splitting L1 into separate I-cache and D-cache enables concurrent instruction fetch and memory operand stages without structural bus stalls.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is Cache Pollution?",
     ["A situation where infrequently accessed or transient data displaces useful, frequently accessed data from the cache, degrading hit rates", "Dust accumulated on RAM sticks", "Corrupted memory bits in cache", "Electromagnetic interference from power supplies"], 0,
     "Cache pollution happens when large linear scans evict working set blocks with high temporal locality, harming overall system performance.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the purpose of the CPU Clock signal?",
     ["A periodic square-wave electrical signal that synchronizes the operations and state changes of all internal sequential logic circuits across the processor", "To display the current time and date on screen", "To measure the battery charge level", "To time out internet connections"], 0,
     "The clock synchronizes flip-flops, ensuring all logic operations across the CPU transition cleanly and reliably on uniform step intervals.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is Clock Skew in synchronous digital circuit design?",
     ["The spatial variation in arrival times of the clock signal at different components across the chip due to differing wire lengths and gate delays", "A clock running too fast due to overheating", "A clock running backwards", "A battery running out of power"], 0,
     "Clock skew occurs when clock distribution paths have unequal physical propagation delays, risking setup or hold time violations.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is Clock Jitter?",
     ["The temporal variation of a clock signal's edge transitions relative to an ideal periodic reference clock", "The shaking of a physical crystal oscillator", "A computer freezing periodically", "A drop in motherboard voltage"], 0,
     "Jitter measures the cycle-to-cycle timing instability of clock period edges, constraining maximum allowable circuit operating frequencies.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is the purpose of a Clock Tree Synthesis (CTS) in ASIC/FPGA layout design?",
     ["Designing a balanced distribution network (such as an H-tree) to deliver the clock signal to all sequential elements with minimal skew and insertion delay", "Planting trees to cool down server rooms", "A data structure for scheduling tasks", "A digital clock display component"], 0,
     "Clock Tree Synthesis creates balanced buffer networks that equalize wire delays, ensuring clock pulses arrive at all chip flip-flops concurrently.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is a Gray Code?",
     ["A binary numeral system where two successive numerical values differ in only one bit position", "An encryption code used in World War II", "A grayscale image format", "A code that contains only zeros"], 0,
     "Gray code guarantees that adjacent values differ by a single bit change, preventing spurious glitch states in rotary encoders and K-maps.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a Ripple Counter in digital electronics?",
     ["An asynchronous binary counter where each flip-flop is clocked by the output of the preceding flip-flop, causing transitions to ripple sequentially", "A water ripple sensor", "A counter that counts in random order", "A counter built inside RAM chips"], 0,
     "In ripple counters, clock pulses ripple asynchronously down the flip-flop chain, creating cumulative propagation delays across bits.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a Synchronous Counter compared to an Asynchronous (Ripple) Counter?",
     ["All flip-flops are connected to a common, simultaneous clock pulse, changing states concurrently without cumulative ripple delay", "A counter that syncs with an atomic clock via NTP", "A counter with no reset pin", "A software loop counting seconds"], 0,
     "Synchronous counters clock all stage flip-flops simultaneously from a shared clock trace, achieving much higher operating frequencies than ripple counters.", "Medium", "Computer Architecture", "Previous Exam"),

    # 91-100
    ("What is the function of the Accumulator register in classic CPU architectures?",
     ["A temporary register used to store intermediate results of arithmetic and logical operations produced by the ALU", "A capacitor that stores electrical power", "A counter that accumulates clock cycles", "A register tracking memory parity"], 0,
     "In single-operand accumulator architectures, the accumulator holds one input operand and captures the ALU's output result.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the Status Register (Flags Register)?",
     ["A collection of individual bit flags (e.g., Zero, Carry, Sign, Overflow) indicating the outcome of the most recent ALU operation and CPU status", "A register tracking the user's online status", "A register holding the computer's serial number", "A register monitoring internet connectivity"], 0,
     "The flags register records conditional outcomes (Z, C, S, O, parity) utilized by subsequent conditional branch instructions.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What does the Zero flag (Z) indicate in a CPU?",
     ["Set to 1 if the result of an arithmetic or logical operation is zero; cleared to 0 otherwise", "Set if the CPU is in sleep mode", "Set if memory is empty", "Set if an error occurred"], 0,
     "The Zero flag is asserted when an operation yields zero, directly governing instructions like JZ (Jump if Zero) or JE (Jump if Equal).", "Easy", "Computer Architecture", "Previous Exam"),
    ("What does the Sign flag (S or Negative Flag N) indicate?",
     ["It reflects the most significant bit (MSB) of the result, indicating whether a signed two's complement value is negative", "Indicates the user entered a minus sign on the keyboard", "Indicates a division by negative zero", "Indicates high voltage on the data bus"], 0,
     "The Sign flag copies the MSB of the ALU output; MSB=1 denotes negative values in two's complement arithmetic.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the purpose of an ALU (Arithmetic Logic Unit)?",
     ["The digital circuit inside the CPU that performs integer arithmetic operations (addition, subtraction) and bitwise logical operations (AND, OR, XOR)", "To allocate virtual memory", "To decode video files", "To synchronize computer clocks"], 0,
     "The ALU executes fundamental arithmetic computations and logical tests upon operand registers under control unit guidance.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is an FPU (Floating-Point Unit)?",
     ["A specialized math coprocessor or hardware execution unit dedicated to carrying out floating-point numerical calculations efficiently", "A power supply regulator unit", "A flash memory controller", "A fan speed control chip"], 0,
     "FPUs execute IEEE 754 floating-point operations in hardware, dramatically outperforming software emulation on integer ALUs.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is a Barrel Shifter?",
     ["A digital logic circuit that can shift or rotate a data word by a specified number of bits in a single clock cycle", "A wooden storage container for hardware parts", "A rotating hard drive platter", "A circular shift register"], 0,
     "Barrel shifters use multiplexer networks to shift or rotate binary words by any arbitrary bit offset in a single clock cycle.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the function of the Bus Arbitration unit in a multi-master computer bus?",
     ["Decide which device is granted control of the shared bus when multiple bus masters request bus access simultaneously", "Compress data sent over the bus", "Encrypt bus addresses", "Clean physical copper contacts"], 0,
     "Bus arbiters use priority schemes (daisy-chain, centralized, or distributed) to allocate bus ownership without signal contention.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is Cycle Stealing in Direct Memory Access (DMA)?",
     ["The DMA controller accesses the system bus for single bus cycles during periods when the CPU is not using the bus, without stopping the CPU", "Stealing power cycles from the wall socket", "Overclocking the CPU bus", "A virus that steals CPU cycles"], 0,
     "Cycle stealing interleaves single-word DMA transfers between CPU bus cycles, minimizing CPU stalls compared to burst mode.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is Burst Mode in DMA data transfer?",
     ["The DMA controller seizes total control of the system bus and transfers a large contiguous block of data without relinquishing the bus until done", "A mode that causes the computer to shut down", "A mode for rapid fire in video games", "A temporary increase in network speed"], 0,
     "In burst mode, the DMA controller locks the bus for the entire duration of a multi-byte transfer, blocking CPU memory access until finished.", "Medium", "Computer Architecture", "Previous Exam")
]

print(f"Total Part 6 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part6_data = []
for i, q in enumerate(questions):
    qid = f"p6-q{i+1}"
    part6_data.append({
        "id": qid,
        "part": 6,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part6.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_6_QUESTIONS: Question[] = ")
    json.dump(part6_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 6 successfully to src/data/parts/part6.ts")
