#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("In the OSI 7-layer model, which layer is responsible for end-to-end reliable communication, flow control, and segmentation?",
     ["Network Layer", "Transport Layer", "Data Link Layer", "Session Layer"], 1,
     "The Transport layer (Layer 4) provides transparent, reliable end-to-end data transfer, segmentation, and flow control.", "Easy", "Computer Networks", "Previous Exam"),
    ("Which protocol resolves an IPv4 address into its corresponding physical hardware MAC address on a local area network?",
     ["DHCP", "DNS", "ARP (Address Resolution Protocol)", "ICMP"], 2,
     "ARP broadcasts a request on the local segment to map a known IP address to a hardware MAC address.", "Easy", "Computer Networks", "Previous Exam"),
    ("What are the flags exchanged in order during the standard TCP three-way connection establishment handshake?",
     ["SYN, ACK, FIN", "SYN, SYN-ACK, ACK", "ACK, SYN, SYN-ACK", "SYN, ACK, DATA"], 1,
     "TCP establishes a connection via: Client sends SYN, Server responds with SYN-ACK, Client sends ACK.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the length of an IPv6 address compared to an IPv4 address?",
     ["64 bits vs 32 bits", "128 bits vs 32 bits", "128 bits vs 64 bits", "256 bits vs 32 bits"], 1,
     "IPv4 uses 32-bit addresses (approx 4.3 billion addresses), while IPv6 uses 128-bit hexadecimal addresses.", "Easy", "Computer Networks", "Previous Exam"),
    ("Which routing protocol uses Dijkstra's Shortest Path First (SPF) algorithm and is categorized as a Link-State interior gateway protocol?",
     ["RIP (Routing Information Protocol)", "BGP (Border Gateway Protocol)", "OSPF (Open Shortest Path First)", "EGP"], 2,
     "OSPF is a link-state routing protocol that utilizes Dijkstra's SPF algorithm to calculate shortest routing paths within an autonomous system.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the maximum payload transmission unit (MTU) for standard Ethernet frames at the Data Link layer?",
     ["512 bytes", "1024 bytes", "1500 bytes", "9000 bytes"], 2,
     "The standard Ethernet MTU is 1500 bytes of payload (excluding Ethernet preamble and frame headers).", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the primary function of ICMP (Internet Control Message Protocol)?",
     ["Transfer files between host computers", "Send network error messages and operational diagnostic telemetry (e.g., ping, traceroute)", "Encrypt application-layer payloads", "Assign dynamic IP addresses"], 1,
     "ICMP is used by network devices to send error reports (e.g., Destination Unreachable, TTL Expired) and diagnostics (Echo Request/Reply).", "Medium", "Computer Networks", "Previous Exam"),
    ("How many usable host IP addresses are available in a subnet with CIDR notation /26?",
     ["64", "62", "30", "126"], 1,
     "A /26 subnet has 32 - 26 = 6 host bits. Total addresses = 2^6 = 64; subtracting network and broadcast addresses yields 64 - 2 = 62 usable hosts.", "Medium", "Computer Networks", "Previous Exam"),
    ("In TCP congestion control, what happens immediately after a packet loss is detected via a retransmission timeout (RTO)?",
     ["Congestion window (cwnd) is reset to 1 MSS, and the algorithm enters Slow Start", "Cwnd is doubled immediately", "TCP switches to UDP mode", "Connection is terminated with a RST packet"], 0,
     "Upon a timeout, TCP sets ssthresh to half of cwnd, drops cwnd back to 1 Maximum Segment Size (MSS), and restarts Slow Start.", "Hard", "Computer Networks", "Previous Exam"),
    ("Which protocol uses the DORA (Discover, Offer, Request, Acknowledge) handshake process?",
     ["DNS", "DHCP", "FTP", "BGP"], 1,
     "DHCP client configuration follows the DORA sequence: DHCP Discover, DHCP Offer, DHCP Request, and DHCP ACK.", "Easy", "Computer Networks", "Previous Exam"),

    # 11-20
    ("What is the size of the UDP header compared to the minimum TCP header size?",
     ["8 bytes vs 20 bytes", "16 bytes vs 32 bytes", "4 bytes vs 12 bytes", "20 bytes vs 40 bytes"], 0,
     "A UDP header is lightweight at fixed 8 bytes (Source port, Destination port, Length, Checksum), while a standard TCP header is minimum 20 bytes.", "Medium", "Computer Networks", "Previous Exam"),
    ("Which layer of the OSI model does a network switch operating on MAC addresses primarily belong to?",
     ["Physical Layer (Layer 1)", "Data Link Layer (Layer 2)", "Network Layer (Layer 3)", "Transport Layer (Layer 4)"], 1,
     "Standard Ethernet switches operate at Layer 2 (Data Link layer), forwarding frames based on hardware MAC addresses.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the purpose of the Spanning Tree Protocol (STP, IEEE 802.1D) in switched local area networks?",
     ["Prevent bridge loops and broadcast storms in redundant network topologies", "Encrypt traffic between access points", "Assign IP addresses dynamically", "Increase link bandwidth using aggregation"], 0,
     "STP disables redundant bridge links logically to prevent bridge loops and catastrophic broadcast storms.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the count-to-infinity problem in Distance Vector routing protocols (such as RIP)?",
     ["Routers slowly increment metric hop counts indefinitely when a route becomes unreachable", "Network throughput increases to infinity", "Routers run out of memory due to too many routing table entries", "Subnet masks expand beyond 32 bits"], 0,
     "The count-to-infinity problem occurs when a link fails and routing loops cause distance estimates to increment slowly toward the protocol infinity metric (16 in RIP).", "Hard", "Computer Networks", "Previous Exam"),
    ("Which mechanism is used by Distance Vector protocols to prevent two adjacent routers from bouncing unreachable route updates back and forth?",
     ["Split Horizon and Poison Reverse", "Dijkstra algorithm", "Fast Retransmit", "Triple DES encryption"], 0,
     "Split Horizon forbids advertising a route back out the same interface it was learned from; Poison Reverse sets the metric to infinity.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the well-known port number for secure web communications using HTTPS?",
     ["80", "443", "8080", "22"], 1,
     "HTTPS standardly listens on port 443; plain HTTP listens on port 80.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the role of the TTL (Time to Live) field in an IPv4 packet header?",
     ["Indicate how many seconds a packet may remain in buffer before delivery", "Prevent packets from looping infinitely in routing loops by decrementing at each router hop", "Specify the transmission timestamp", "Determine the maximum MTU"], 1,
     "The TTL field is decremented by 1 at every router hop; when TTL reaches 0, the packet is discarded and an ICMP Time Exceeded is returned.", "Medium", "Computer Networks", "Previous Exam"),
    ("Which DNS resource record maps a hostname directly to an IPv6 address?",
     ["A record", "AAAA record", "CNAME record", "MX record"], 1,
     "An A record maps a hostname to an IPv4 (32-bit) address; an AAAA record (quad-A) maps a hostname to an IPv6 (128-bit) address.", "Easy", "Computer Networks", "Previous Exam"),
    ("In web protocols, what major improvement did HTTP/2 introduce over HTTP/1.1?",
     ["Switching from TCP to UDP", "Multiplexing multiple concurrent requests over a single TCP connection and binary framing", "Elimination of SSL/TLS certificates", "Replacing JSON with XML"], 1,
     "HTTP/2 introduced binary framing, header compression (HPACK), and multiplexed streams over a single persistent TCP connection.", "Medium", "Computer Networks", "Previous Exam"),
    ("Which protocol is the standard exterior gateway protocol used for routing between autonomous systems (AS) on the global Internet?",
     ["BGP (Border Gateway Protocol)", "OSPF", "RIP", "IS-IS"], 0,
     "BGP is the path-vector exterior routing protocol that powers core routing decisions between distinct Autonomous Systems on the Internet.", "Medium", "Computer Networks", "Previous Exam"),

    # 21-30
    ("What does CSMA/CD stand for in Ethernet local area networks?",
     ["Carrier Sense Multiple Access with Collision Detection", "Channel Switching Multi-Access with Code Division", "Carrier Signal Modulation Algorithm with Collision Delay", "Centralized System Management Architecture with Data Routing"], 0,
     "CSMA/CD stands for Carrier Sense Multiple Access with Collision Detection, the legacy arbitration scheme for half-duplex Ethernet.", "Easy", "Computer Networks", "Previous Exam"),
    ("Why is CSMA/CA (Collision Avoidance) used in wireless Wi-Fi (802.11) instead of CSMA/CD?",
     ["Wireless transceivers cannot reliably detect collisions while transmitting due to signal attenuation (hidden terminal problem)", "Wireless signals travel faster than Ethernet", "Collisions cannot physically occur over radio waves", "CSMA/CD is proprietary to IBM"], 0,
     "In wireless media, transmitters drown out incoming signals, making collision detection during transmission physically impractical; hence avoidance (RTS/CTS, ACK) is used.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the function of the sliding window mechanism in TCP?",
     ["Manage end-to-end flow control to prevent the sender from overwhelming the receiver's receive buffer", "Encrypt packets before transmission", "Compress HTML payloads", "Route packets through proxy servers"], 0,
     "TCP's sliding window enforces flow control: the receiver advertises its available buffer space (rwnd), bounding the amount of unacknowledged data the sender may transmit.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the purpose of the TIME_WAIT state during TCP connection termination?",
     ["Ensure that the final ACK was received by the remote end and allow late duplicate packets to expire safely in the network", "Wait for the user to enter a password", "Cool down the CPU before closing sockets", "Measure connection round-trip latency"], 0,
     "TIME_WAIT (typically 2 * MSL) prevents delayed segments from being misinterpreted by a future connection using the same socket pair.", "Hard", "Computer Networks", "Previous Exam"),
    ("In email architecture, which protocol is typically used to push outgoing mail from a client to a mail server or between mail servers?",
     ["POP3", "IMAP", "SMTP", "SNMP"], 2,
     "Simple Mail Transfer Protocol (SMTP, port 25/587) is the standard protocol for sending and relaying emails.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the primary difference between POP3 and IMAP?",
     ["POP3 downloads emails and typically deletes them from the server, while IMAP synchronizes mailboxes on the server across multiple clients", "POP3 supports SSL while IMAP does not", "IMAP cannot display HTML messages", "POP3 is only used on mobile phones"], 0,
     "IMAP keeps email messages on the server so that folders and statuses stay synchronized across all devices, unlike simple POP3 downloads.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is NAT (Network Address Translation) primarily used for?",
     ["Map private internal IP addresses within a LAN to one or more public registered IP addresses on the WAN", "Translate English hostnames into IP addresses", "Convert analog voice to digital VoIP packets", "Encrypt VPN tunnel payloads"], 0,
     "NAT allows multiple private devices (e.g., 192.168.x.x) to share a single public IP address, conserving IPv4 address space.", "Medium", "Computer Networks", "Previous Exam"),
    ("Which IP address block is defined by RFC 1918 as private non-routable address space for Class C networks?",
     ["10.0.0.0 to 10.255.255.255", "172.16.0.0 to 172.31.255.255", "192.168.0.0 to 192.168.255.255", "127.0.0.0 to 127.255.255.255"], 2,
     "192.168.0.0/16 is the Class C private IPv4 range; 10.0.0.0/8 is Class A private; 172.16.0.0/12 is Class B private.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the loopback IPv4 address reserved for internal testing within a local host?",
     ["0.0.0.0", "127.0.0.1", "255.255.255.255", "192.168.1.1"], 1,
     "127.0.0.1 (or any address in 127.0.0.0/8) is reserved for the local loopback interface (localhost).", "Easy", "Computer Networks", "Previous Exam"),
    ("What does a collision domain represent in computer networking?",
     ["A network segment where packet collisions can occur if two devices transmit simultaneously on shared media", "A domain name that conflicts with another domain", "A server room with overheating routers", "An encrypted VPN tunnel"], 0,
     "A collision domain is a physical network segment where simultaneous transmissions from two devices collide (e.g., all ports on a shared hub).", "Easy", "Computer Networks", "Previous Exam"),

    # 31-40
    ("How do switches differ from hubs regarding collision and broadcast domains?",
     ["Each switch port represents its own separate collision domain, but all ports share a single broadcast domain (unless VLANs are configured)", "Switches create one large collision domain for all ports", "Hubs separate broadcast domains while switches do not", "Switches eliminate both collision and broadcast domains completely"], 0,
     "Each switch port is an isolated collision domain, while an entire switch forms a single broadcast domain unless segmented by VLANs.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is a VLAN (Virtual Local Area Network)?",
     ["A logical grouping of network devices configured to communicate as if they were on the same physical broadcast domain regardless of physical switch location", "A local area network connected via satellite", "A simulated network created by virtual reality goggles", "An insecure public Wi-Fi network"], 0,
     "VLANs partition a physical switch network into logically isolated broadcast domains (governed by IEEE 802.1Q tagging).", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the purpose of the IEEE 802.1Q standard?",
     ["Add a 4-byte VLAN tag into standard Ethernet frame headers for VLAN trunking", "Define wireless Bluetooth connections", "Standardize power-over-Ethernet (PoE)", "Encrypt browser sessions"], 0,
     "IEEE 802.1Q inserts a 32-bit field (including a 12-bit VLAN ID) into the Ethernet frame to identify VLAN membership across trunk links.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the difference between iterative and recursive DNS queries?",
     ["In recursive queries, the DNS server resolves the full name on behalf of the client; in iterative queries, it returns referrals to other servers", "Recursive queries use UDP while iterative queries use TCP", "Iterative queries cannot resolve .com domains", "There is no difference in DNS resolution"], 0,
     "In a recursive query, the contacted server does all the legwork to return the final answer; in an iterative query, it replies with the best current referral.", "Medium", "Computer Networks", "Previous Exam"),
    ("Which transport layer protocol does DNS typically use for standard hostname lookups?",
     ["UDP port 53", "TCP port 80", "ICMP port 0", "SCTP port 443"], 0,
     "Standard DNS queries and responses use UDP on port 53 due to low latency, using TCP port 53 for zone transfers or oversized responses (>512 bytes).", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the primary role of the TLS (Transport Layer Security) handshake?",
     ["Authenticate the server, negotiate cryptographic cipher suites, and establish shared symmetric session keys", "Compress network images", "Assign dynamic IP addresses", "Prevent SYN flood attacks at router firewalls"], 0,
     "The TLS handshake verifies identity via digital certificates, agrees on encryption algorithms, and exchanges session keys securely.", "Medium", "Computer Networks", "Previous Exam"),
    ("In symmetric vs asymmetric cryptography used in TLS/HTTPS, which statement is true?",
     ["Asymmetric encryption (e.g., RSA/ECC) is used during handshake to securely exchange keys, then symmetric encryption (e.g., AES) encrypts session data", "Symmetric encryption is used for digital certificates", "Asymmetric encryption encrypts all video streams because it is faster", "TLS never uses symmetric encryption"], 0,
     "Asymmetric crypto is computationally expensive, so it is only used to authenticate and exchange a symmetric session key; fast symmetric crypto then encrypts the traffic.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the Shannon Capacity theorem used to determine in telecommunications?",
     ["The maximum theoretical data rate of a communication channel in the presence of noise: C = B * log2(1 + S/N)", "The physical length limit of fiber optic cable", "The cost of building a cell tower", "The minimum latency of a satellite link"], 0,
     "Shannon's theorem establishes the upper bound on data transmission rate over an analog channel given bandwidth B and Signal-to-Noise ratio (S/N).", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the Nyquist theorem formula for maximum bit rate of a noiseless channel with bandwidth B and M signal levels?",
     ["BitRate = 2 * B * log2(M)", "BitRate = B * S/N", "BitRate = M / B", "BitRate = log10(B * M)"], 0,
     "Nyquist theorem states that the maximum transmission rate of a noiseless channel is 2 * B * log2(M) bits per second.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is Manchester encoding in physical layer digital communications?",
     ["A line code where each bit period has a voltage transition in the middle, providing self-clocking synchronization", "An encryption algorithm invented in Manchester", "A compression method for JPEG pictures", "A protocol for transatlantic cables"], 0,
     "Manchester encoding ensures a mid-bit transition (low-to-high for 1, high-to-low for 0), allowing the receiver to synchronize its clock reliably.", "Medium", "Computer Networks", "Previous Exam"),

    # 41-50
    ("What is the function of the Checksum in the TCP header?",
     ["Verify error detection across the TCP header, TCP payload, and a pseudo-header containing IP addresses", "Encrypt the TCP segment", "Track the number of intermediate hops", "Measure round trip time"], 0,
     "TCP checksum covers the TCP segment plus a 12-byte pseudo-header containing source/destination IPs to detect corrupted or misdelivered segments.", "Medium", "Computer Networks", "Previous Exam"),
    ("What does a TCP RST (Reset) packet indicate when received by a client?",
     ["The receiving host rejects the connection because no process is listening on the requested port, or an invalid segment arrived", "The connection was completed successfully", "The server requests retransmission of data", "The client should double its congestion window"], 0,
     "A RST flag is sent to abruptly abort or reject a connection when an unexpected or invalid packet arrives on an unlistening port.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the primary role of the Dynamic Host Configuration Protocol (DHCP) lease time?",
     ["The duration of time an assigned IP address is valid for use by the client before requiring renewal", "The time required to boot the operating system", "The network cable latency", "The maximum duration of a web browsing session"], 0,
     "Lease time defines how long a client may retain an assigned IP configuration before requesting a lease extension from the DHCP server.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is an autonomous system (AS) in Internet architecture?",
     ["A connected group of IP networks under the administrative control of a single entity presenting a common routing policy", "A self-driving automobile network", "A home Wi-Fi router with no password", "A standalone computer disconnected from the Internet"], 0,
     "An AS is a collection of connected routing prefixes under common administrative ownership (like an ISP or university) identified by an ASN.", "Medium", "Computer Networks", "Previous Exam"),
    ("Which protocol is commonly used for secure remote command-line login across encrypted network channels?",
     ["Telnet", "SSH (Secure Shell)", "FTP", "RDP"], 1,
     "SSH (port 22) provides strong encrypted terminal access, replacing insecure legacy plaintext protocols like Telnet (port 23).", "Easy", "Computer Networks", "Previous Exam"),
    ("What does the traceroute (or tracert) utility use to discover intermediate routers along a path?",
     ["Sends packets with progressively incrementing TTL values (1, 2, 3...) to trigger ICMP Time Exceeded messages from each hop", "Scans router memory directly using SNMP", "Reads GPS coordinates stored in IP headers", "Queries Google Maps API"], 0,
     "Traceroute starts with TTL=1, which expires at the first router returning an ICMP TTL Exceeded; it then increments TTL to discover subsequent hops.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the maximum hop count allowed by the Routing Information Protocol (RIP) before a route is declared unreachable?",
     ["15 hops (16 denotes infinity/unreachable)", "255 hops", "100 hops", "32 hops"], 0,
     "RIP caps route metrics at 15 hops to mitigate distance-vector routing loops; a metric of 16 represents infinity (unreachable).", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the primary advantage of CIDR (Classless Inter-Domain Routing) over classful addressing?",
     ["Allows arbitrary prefix lengths (/n), enabling flexible subnet allocation and route aggregation (supernetting)", "Eliminates the need for routers", "Multiplies IPv4 addresses by 10", "Makes all IP addresses private"], 0,
     "CIDR replaced rigid Class A/B/C boundaries with variable-length subnet masking (VLSM), dramatically slowing IPv4 table bloat.", "Medium", "Computer Networks", "Previous Exam"),
    ("In IPv4 headers, what is the purpose of the Fragment Offset field?",
     ["Specifies the relative position of fragmented data within the original unfragmented datagram (in units of 8 bytes)", "Measures distance between sender and receiver in miles", "Tracks TCP sequence numbers", "Defines the port number"], 0,
     "Fragment offset indicates where in the original packet this fragment belongs, measured in 8-byte (64-bit) blocks.", "Hard", "Computer Networks", "Previous Exam"),
    ("Which flag in the IPv4 header prevents routers from fragmenting a packet, dropping it if its size exceeds the outgoing interface MTU?",
     ["DF (Don't Fragment) flag", "MF (More Fragments) flag", "SYN flag", "URG flag"], 0,
     "When the DF bit is set to 1, routers unable to forward the packet without fragmenting must drop it and return an ICMP Fragmentation Needed message.", "Medium", "Computer Networks", "Previous Exam"),

    # 51-60
    ("What is Path MTU Discovery (PMTUD)?",
     ["A technique where a host sends packets with the DF bit set to determine the smallest MTU along the entire transmission path", "A protocol to discover nearby Wi-Fi printers", "A speed test for home broadband", "A hardware tester for twisted pair cables"], 0,
     "PMTUD sets the DF bit so that intermediate routers drop oversized packets and report their MTU via ICMP, allowing the sender to adapt its segment size.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the well-known port number for SNMP (Simple Network Management Protocol) agent queries?",
     ["161", "53", "25", "110"], 0,
     "SNMP agents receive monitoring queries over UDP port 161 (SNMP traps are sent to port 162).", "Medium", "Computer Networks", "Previous Exam"),
    ("What is an Anycast IP address?",
     ["An address assigned to multiple interfaces across different locations; packets are routed to the nearest topologically available host", "A broadcast sent to all devices worldwide", "An address reserved for multicast TV streams", "A temporary IP address that expires in 1 minute"], 0,
     "Anycast assigns the same IP to multiple servers; BGP routes client requests to whichever server is closest from a routing perspective (common in DNS/CDNs).", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the purpose of the Address Resolution Protocol (ARP) cache?",
     ["Store recently resolved IP-to-MAC address mappings in RAM to reduce local network broadcast traffic", "Cache DNS domain names", "Save web browser history", "Store Wi-Fi passwords"], 0,
     "The ARP table caches IP-to-MAC associations so that repeated packets to the same destination do not require continuous ARP broadcasts.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is ARP spoofing (ARP poisoning)?",
     ["An attacker sends fake ARP responses linking their MAC address to the IP of a legitimate default gateway to intercept LAN traffic", "Changing an IP address in the operating system GUI", "Deleting the local DNS resolver cache", "Flooding an Ethernet switch with random MACs"], 0,
     "ARP spoofing tricks local hosts into associating the attacker's MAC with the router IP, enabling Man-in-the-Middle (MitM) packet eavesdropping.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the function of a network bridge in local area networks?",
     ["Connect and filter traffic between two distinct physical network segments at the Data Link layer (Layer 2) based on MAC addresses", "Connect two optical fibers physically", "Convert IPv4 to IPv6 at Layer 3", "Enforce web firewall rules"], 0,
     "A bridge connects two network segments at Layer 2, inspecting incoming frame destination MACs to decide whether to forward them across the bridge.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is a broadcast storm in Ethernet switching networks?",
     ["A continuous loop where broadcast frames multiply exponentially, consuming all available network bandwidth and crashing switches", "A lightning strike hitting radio antennas", "A server sending 100 emails simultaneously", "A high volume of DNS requests to root servers"], 0,
     "Broadcast storms occur when redundant switch paths lack loop-prevention (like STP), causing broadcast packets to circulate and replicate infinitely.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the purpose of the BGP Autonomous System Number (ASN)?",
     ["A globally unique integer identifying an autonomous system on the Internet routing plane", "The serial number of a Cisco router", "The MAC address of an internet exchange switch", "A software license key for routing software"], 0,
     "ASNs are unique numbers assigned by IANA/RIRs identifying individual autonomous networks for BGP peering and route advertisement.", "Medium", "Computer Networks", "Previous Exam"),
    ("What does the term 'peering' mean in Internet service provider architecture?",
     ["Two internet service providers directly exchanging traffic between their respective customer networks without paying transit fees", "Connecting two computers with a crossover cable", "Viewing someone's screen remotely", "Streaming video over P2P torrents"], 0,
     "Settlement-free peering is an agreement where two network operators exchange traffic directly at Internet Exchange Points (IXPs) for mutual benefit.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is an Ephemeral Port in TCP/IP networking?",
     ["A short-lived dynamic port number allocated automatically by the OS client stack for the client end of a connection", "A physical port that disconnects automatically", "Port 80 reserved for HTTP", "A port used exclusively by database administrators"], 0,
     "Ephemeral ports (typically 49152-65535) are temporary port numbers assigned dynamically to outbound client sockets and recycled upon closing.", "Medium", "Computer Networks", "Previous Exam"),

    # 61-70
    ("What is the purpose of the MSS (Maximum Segment Size) in TCP?",
     ["The maximum amount of TCP data payload (excluding TCP and IP headers) that a host can receive in a single segment", "The maximum physical size of a router", "The total size of a TCP connection in RAM", "The time taken to transmit one packet"], 0,
     "MSS specifies the maximum chunk of application data a host can accept per segment, typically MTU (1500) minus IP (20) and TCP (20) headers = 1460 bytes.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the purpose of the Nagle's Algorithm in TCP?",
     ["Combine small outgoing data chunks into a single larger TCP segment to prevent congesting networks with tiny packets (silly window syndrome)", "Speed up ping response times", "Encrypt credit card transactions", "Balance load across CPU cores"], 0,
     "Nagle's algorithm delays transmission of small application buffers if unacknowledged data is outstanding, aggregating them into full MSS packets.", "Hard", "Computer Networks", "Previous Exam"),
    ("What does the TCP Fast Retransmit mechanism do?",
     ["Retransmits a lost segment immediately upon receiving 3 duplicate ACKs without waiting for the retransmission timer (RTO) to expire", "Doubles transmission speed on fiber networks", "Skips TCP handshake during reconnection", "Bypasses the operating system kernel"], 0,
     "Three duplicate ACKs indicate to the sender that a specific segment was dropped, triggering immediate retransmission before the slow timer fires.", "Hard", "Computer Networks", "Previous Exam"),
    ("In HTTP, what does status code 301 Moved Permanently signify?",
     ["The requested resource has been definitively assigned a new permanent URI, and search engines should update their indexed links", "The request was forbidden", "The server crashed due to an error", "The client request was successful"], 0,
     "HTTP 301 indicates a permanent redirection; browsers and crawlers cache the new target URL specified in the Location header.", "Easy", "Computer Networks", "Previous Exam"),
    ("What does HTTP status code 403 Forbidden indicate?",
     ["The server understood the request, but refuses to authorize access regardless of authentication status", "The page was not found", "The server timed out waiting for input", "The requested method is not allowed"], 0,
     "HTTP 403 indicates that access to the requested resource is forbidden to the client, unlike 401 which asks for missing credentials.", "Easy", "Computer Networks", "Previous Exam"),
    ("What does HTTP status code 503 Service Unavailable mean?",
     ["The server is currently unable to handle the request due to a temporary overload or scheduled maintenance", "The user password was wrong", "The requested file extension is invalid", "The DNS server could not be reached"], 0,
     "HTTP 503 signifies a temporary condition where the web server is overloaded or down for maintenance and will recover shortly.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the difference between HTTP GET and POST methods according to RFC standards?",
     ["GET is idempotent and should be safe without server side effects, while POST submits data intended to cause state changes or resource creation", "GET cannot include query parameters", "POST cannot transmit more than 100 bytes", "GET is encrypted while POST is plaintext"], 0,
     "GET requests retrieve data safely without mutating server resources (idempotent); POST sends payloads to create or modify server resources.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the role of the Content-Type HTTP header?",
     ["Indicate the MIME media type of the body entity included in the request or response (e.g., application/json, text/html)", "Specify the author of the webpage", "Define the expiration date of cookies", "Determine screen resolution"], 0,
     "Content-Type tells the recipient how to parse the payload data by specifying its MIME type and character encoding.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the function of the CORS (Cross-Origin Resource Sharing) mechanism?",
     ["A browser security mechanism that uses HTTP headers to allow or restrict resources requested from a different domain/origin", "A method for speeding up CSS downloads", "A protocol for sharing files across Wi-Fi", "A database replication tool"], 0,
     "CORS permits web browsers to make AJAX/fetch requests across distinct domain origins while enforcing origin policies specified by server headers.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the purpose of HTTP cookies in web applications?",
     ["Small blocks of stateful data stored by the web browser on behalf of the server to maintain sessions, user preferences, and tracking", "Visual decorations on buttons", "Hardware chips storing BIOS passwords", "Temporary files storing video textures"], 0,
     "Cookies store state across stateless HTTP requests (e.g., session identifiers, authentication tokens, shopping cart contents).", "Easy", "Computer Networks", "Previous Exam"),

    # 71-80
    ("What is the security significance of the 'HttpOnly' flag on a cookie?",
     ["Prevents client-side scripts (such as JavaScript) from accessing the cookie, mitigating Cross-Site Scripting (XSS) session theft", "Forces the cookie to be sent only over HTTPS", "Deletes the cookie when the browser closes", "Compresses the cookie body"], 0,
     "HttpOnly prevents document.cookie from exposing sensitive session tokens to injected JavaScript during XSS attacks.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the security function of the 'Secure' attribute on an HTTP cookie?",
     ["Ensures that the cookie is transmitted only over encrypted HTTPS connections, never over unencrypted HTTP", "Encrypts the cookie with the user's password", "Locks the cookie to a specific IP address", "Prevents search engines from indexing the page"], 0,
     "The Secure flag instructs the browser to omit the cookie from unencrypted HTTP requests, protecting it against wiretapping.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the purpose of a Content Delivery Network (CDN)?",
     ["Distribute cached static and streaming content across a geographically dispersed network of edge servers close to end-users", "Generate synthetic training data for AI models", "Replace web hosting servers entirely", "Provide domain name registration"], 0,
     "CDNs store cached copies of web assets on edge proxy servers globally to minimize latency and offload traffic from origin servers.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the primary protocol used by HTTP/3 for underlying transport instead of traditional TCP?",
     ["QUIC (Quick UDP Internet Connections)", "SCTP", "DCCP", "IPsec"], 0,
     "HTTP/3 uses QUIC over UDP, providing multiplexing without head-of-line blocking and faster connection handshakes than TCP.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the head-of-line (HoL) blocking problem in HTTP/1.1 and TCP?",
     ["A single lost or slow packet/request blocks all subsequent data in the FIFO stream from being delivered to the application", "A bottleneck caused by CPU overheating", "A router running out of power", "A monitor cable being disconnected"], 0,
     "HoL blocking occurs when delays or drops in the leading element of a queue hold up all subsequent queued items behind it.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is the function of the DNS CNAME (Canonical Name) record?",
     ["Alias one domain name to another canonical domain name", "Map a domain name to an IPv4 address", "Specify the mail exchange server", "Store cryptographic public keys"], 0,
     "A CNAME record maps an alias hostname (e.g., www.example.com) to its canonical domain name (example.com).", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the DNS MX (Mail Exchange) record used for?",
     ["Specify the mail server responsible for accepting incoming email messages on behalf of a domain", "Send instant chat messages", "Store audio files", "Provide DNS root hints"], 0,
     "MX records direct email agents to the mail servers authorized to handle mail delivery for the domain, with priority rankings.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is an Autonomous System (AS) path in BGP routing?",
     ["The sequence of AS numbers traversed by a route advertisement to reach the destination prefix, used for loop prevention and path selection", "The physical highway route taken by fiber cables", "The internal path between CPU and memory", "The list of DNS servers queried"], 0,
     "The AS_PATH attribute lists every AS the route has passed through; if a router sees its own ASN in the path, it discards the route to prevent loops.", "Hard", "Computer Networks", "Previous Exam"),
    ("What is a subnet mask used for in IPv4 networking?",
     ["Distinguish the network prefix portion of an IP address from the host portion using bitwise AND", "Encrypt IP packets during transit", "Hide an IP address from hackers", "Convert binary addresses to hexadecimal"], 0,
     "A subnet mask defines which bits belong to the network identifier (1s) and which bits identify the specific host (0s).", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the broadcast address for the network 192.168.1.0/24?",
     ["192.168.1.255", "192.168.1.0", "192.168.1.1", "255.255.255.255"], 0,
     "In a /24 network, the host portion comprises the last 8 bits; setting all host bits to 1 yields .255, the directed broadcast address.", "Easy", "Computer Networks", "Previous Exam"),

    # 81-90
    ("What is the default subnet mask for a legacy Class B IPv4 network?",
     ["255.255.0.0 (/16)", "255.0.0.0 (/8)", "255.255.255.0 (/24)", "255.255.255.255 (/32)"], 0,
     "Class B networks use the first 16 bits for network ID and 16 bits for host IDs, corresponding to 255.255.0.0.", "Easy", "Computer Networks", "Previous Exam"),
    ("What range of initial octet values identifies Class C IPv4 addresses?",
     ["192 to 223", "1 to 126", "128 to 191", "224 to 239"], 0,
     "Class A: 1-126; Class B: 128-191; Class C: 192-223; Class D (multicast): 224-239; Class E (experimental): 240-255.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the purpose of IPv4 Class D addresses (224.0.0.0 to 239.255.255.255)?",
     ["Multicast group communications", "Private home Wi-Fi networks", "Military satellite links", "Loopback testing"], 0,
     "Class D addresses are reserved for IP multicast, delivering single packets simultaneously to groups of registered subscribers.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the role of IGMP (Internet Group Management Protocol)?",
     ["Allow IPv4 hosts to report their multicast group memberships to adjacent local routers", "Route email between organizations", "Encrypt internet banking sessions", "Assign static IP addresses"], 0,
     "IGMP allows local devices to join and leave multicast streaming groups, informing local routers which streams to forward onto the LAN.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is Port Address Translation (PAT / NAT Overload)?",
     ["A form of NAT that translates both IP addresses and port numbers, allowing thousands of internal hosts to share a single public IP", "Translating website domain names to ports", "Rewriting MAC addresses in switch tables", "Forwarding print jobs to printers"], 0,
     "PAT maps internal private IP/port combinations to distinct source ports on a single public IP, enabling shared internet access.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the function of the WebSocket protocol (RFC 6455)?",
     ["Provide full-duplex, bidirectional communication channels over a single persistent TCP socket connection initiated via HTTP upgrade", "Download files in background", "Stream video over UDP only", "Encrypt hard drives"], 0,
     "WebSockets upgrade an HTTP connection into a persistent, low-overhead, full-duplex channel for real-time data exchange.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the standard payload data unit (PDU) at the Data Link layer?",
     ["Frame", "Packet", "Segment", "Bit"], 0,
     "PDU names across layers: Physical = Bit, Data Link = Frame, Network = Packet, Transport = Segment, Application = Message/Data.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the PDU name at the Transport layer for TCP?",
     ["Segment", "Packet", "Frame", "Datagram"], 0,
     "At Layer 4, TCP data units are called Segments (UDP data units are often referred to as Datagrams).", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the PDU name at the Network layer?",
     ["Packet", "Frame", "Segment", "Byte"], 0,
     "At Layer 3 (Network layer), the unit of data encapsulation is called a Packet (or IP datagram).", "Easy", "Computer Networks", "Previous Exam"),
    ("What does the Bellman-Ford algorithm compute in Distance Vector routing protocols?",
     ["Shortest path routes from a source node to all other nodes in a graph, accommodating edges with negative weights", "Fast Fourier transforms", "CRC error polynomials", "Public-key cryptography primes"], 0,
     "Bellman-Ford iteratively calculates shortest paths in weighted graphs, forming the theoretical mathematical basis of Distance Vector protocols like RIP.", "Hard", "Computer Networks", "Previous Exam"),

    # 91-100
    ("What is a proxy server in network architecture?",
     ["An intermediary server that acts as an agent making network requests on behalf of clients, providing caching, filtering, and anonymity", "A physical network wire", "A secondary power generator", "A backup motherboard"], 0,
     "A forward proxy intercepts client requests and forwards them to internet destinations, providing access control, logging, and caching.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is a Reverse Proxy?",
     ["A server that sits in front of one or more web servers, intercepting requests from clients to provide load balancing, SSL termination, and caching", "A client pretending to be a router", "A cable that reverses byte order", "A backward Wi-Fi antenna"], 0,
     "A reverse proxy (e.g., NGINX, HAProxy) stands before backend origin servers, distributing incoming user traffic and terminating TLS.", "Medium", "Computer Networks", "Previous Exam"),
    ("What does round-trip time (RTT) measure in computer networks?",
     ["The duration of time it takes for a data packet to travel from sender to destination and its acknowledgment to return", "The time taken to boot a computer", "The rotation speed of a hard drive platter", "The time required to compile code"], 0,
     "RTT measures the total elapsed time for a network signal to travel to the remote destination and bring back an acknowledgment.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the function of the SSH known_hosts file?",
     ["Store public key fingerprints of previously verified remote servers to detect unauthorized host key changes (MitM protection)", "Store user passwords", "List all websites visited by the user", "Configure local network subnets"], 0,
     "known_hosts caches server public keys; if a host key changes unexpectedly, SSH warns the user of possible Man-in-the-Middle tampering.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is link aggregation (IEEE 802.3ad / LACP)?",
     ["Combining multiple physical network cables between switches into a single logical channel to increase bandwidth and provide redundancy", "Soldering two wires together", "Joining multiple Wi-Fi networks simultaneously", "Compressing network packets with zip"], 0,
     "Link aggregation combines multiple physical Ethernet links into a single logical trunk for higher throughput and failover protection.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is attenuation in physical transmission media?",
     ["The progressive loss of signal strength (amplitude) as it propagates through a transmission medium", "The speeding up of electrons in copper", "The encryption of radio frequencies", "The reflection of light in fiber optic cables"], 0,
     "Attenuation is the natural degradation and weakening of electrical or optical signal power over physical distance.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is jitter in network performance metrics?",
     ["The variation (packet delay variation) in the arrival latency of sequential packets over time", "The physical shaking of network cables", "The percentage of dropped packets", "The bandwidth of an Ethernet connection"], 0,
     "Jitter measures the inconsistency in packet latency across a stream, critical for real-time VoIP and video streaming quality.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is the primary role of a Firewall in network security?",
     ["Monitor and filter incoming and outgoing network traffic based on predetermined security rules to isolate trusted and untrusted networks", "Extinguish physical server fires", "Accelerate CPU clock frequency", "Clean optical fibers with lasers"], 0,
     "A firewall inspects packet headers and states (stateful inspection) to block unauthorized connections between security zones.", "Easy", "Computer Networks", "Previous Exam"),
    ("What is the maximum payload size of a single standard IPv4 datagram?",
     ["65,535 bytes (including IP header)", "1,500 bytes", "4,096 bytes", "1,048,576 bytes"], 0,
     "The 16-bit Total Length field in the IPv4 header allows a maximum theoretical datagram size of 2^16 - 1 = 65,535 bytes.", "Medium", "Computer Networks", "Previous Exam"),
    ("What is a SYN flood attack?",
     ["A Denial of Service (DoS) attack where an attacker sends a deluge of TCP SYN requests without completing the 3-way handshake, exhausting server connection tables", "Flooding a server room with water", "Sending large emails to crash mail servers", "Cracking passwords with dictionary attacks"], 0,
     "SYN flood exploits TCP handshake state tables by allocating half-open connections that exhaust the server's backlog queue.", "Medium", "Computer Networks", "Previous Exam")
]

print(f"Total Part 3 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part3_data = []
for i, q in enumerate(questions):
    qid = f"p3-q{i+1}"
    part3_data.append({
        "id": qid,
        "part": 3,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part3.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_3_QUESTIONS: Question[] = ")
    json.dump(part3_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 3 successfully to src/data/parts/part3.ts")
