#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("Which SOLID design principle states that software entities (classes, modules, functions) should be open for extension, but closed for modification?",
     ["Single Responsibility Principle", "Open/Closed Principle", "Liskov Substitution Principle", "Interface Segregation Principle"], 1,
     "The Open/Closed Principle (OCP) asserts that systems should allow new functionality to be added through extension (e.g., subclassing, interfaces) without altering existing tested source code.", "Easy", "Software Engineering", "Previous Exam"),
    ("Which design pattern provides an interface for creating families of related or dependent objects without specifying their concrete classes?",
     ["Factory Method", "Abstract Factory", "Builder", "Prototype"], 1,
     "Abstract Factory defines an interface for creating families of related objects without exposing concrete implementations.", "Medium", "Software Engineering", "Previous Exam"),
    ("In object-oriented design, what does the Liskov Substitution Principle (LSP) require?",
     ["Subtypes must be substitutable for their base types without altering the correctness of the program", "All classes must inherit from an abstract interface", "Classes should have only one reason to change", "Private fields cannot be accessed by methods"], 0,
     "LSP mandates that objects of a superclass should be replaceable with objects of its subclasses without breaking application behavior.", "Medium", "Software Engineering", "Previous Exam"),
    ("Which Gang of Four (GoF) behavioral pattern defines a family of algorithms, encapsulates each one, and makes them interchangeable at runtime?",
     ["State Pattern", "Strategy Pattern", "Observer Pattern", "Command Pattern"], 1,
     "The Strategy pattern encapsulates alternative algorithms into separate classes conforming to a common interface, allowing dynamic runtime selection.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the primary role of the Scrum Master in an Agile Scrum development team?",
     ["Manage project budgets and assign tasks directly to developers", "Facilitate Scrum ceremonies, remove blockers, and coach the team on Scrum values and practices", "Write the user stories and prioritize the Product Backlog", "Perform code reviews and approve pull requests"], 1,
     "The Scrum Master is a servant leader who removes team impediments, facilitates sprint events, and protects the team from external distractions.", "Easy", "Software Engineering", "Previous Exam"),
    ("Which structural design pattern attaches additional responsibilities to an object dynamically as an alternative to subclassing?",
     ["Adapter", "Decorator", "Facade", "Proxy"], 1,
     "The Decorator pattern wraps an object to dynamically add or augment behavior transparently without altering the original class.", "Medium", "Software Engineering", "Previous Exam"),
    ("What does the 'D' stand for in the SOLID design principles?",
     ["Direct Object Instantiation", "Dependency Inversion Principle", "Data Encapsulation Principle", "Dynamic Dispatch Pattern"], 1,
     "The Dependency Inversion Principle (DIP) states that high-level modules should depend on abstractions (interfaces), not concrete low-level details.", "Easy", "Software Engineering", "Previous Exam"),
    ("In Git version control, what does 'git rebase' do compared to 'git merge'?",
     ["Creates a merge commit tying two branches together", "Replays commits from the current branch on top of the tip of another branch, producing a linear commit history", "Deletes all untracked files in the working directory", "Pushes commits directly to the remote repository"], 1,
     "Rebase rewrites commit history by transplanting commits onto a new base commit, creating a clean linear project history without merge commits.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the cycle followed in Test-Driven Development (TDD)?",
     ["Design -> Code -> Test -> Release", "Red (write a failing test) -> Green (write minimal code to pass) -> Refactor (clean up code)", "Code -> Test -> Fix -> Deploy", "Plan -> Sprint -> Review -> Retrospective"], 1,
     "TDD follows the Red-Green-Refactor loop: author a failing test first, write the simplest implementation to satisfy the test, and then refactor for elegance.", "Easy", "Software Engineering", "Previous Exam"),
    ("Which architectural style breaks an application into a collection of loosely coupled, independently deployable services organized around business capabilities?",
     ["Monolithic architecture", "Microservices architecture", "Client-Server architecture", "Layered 3-tier architecture"], 1,
     "Microservices partition systems into small, independently deployable services communicating via lightweight protocols (e.g., HTTP/REST or gRPC).", "Easy", "Software Engineering", "Previous Exam"),

    # 11-20
    ("What is the difference between Method Overloading and Method Overriding in OOP?",
     ["Overloading is compile-time polymorphism with identical method names but different parameter signatures; Overriding is runtime polymorphism replacing superclass method implementations", "Overriding occurs in the same class; Overloading requires inheritance", "Overloading changes the return type only", "Overriding is not permitted in Java or C++"], 0,
     "Overloading defines methods with the same name but different signatures within a class (static); Overriding provides subclass-specific implementations for inherited methods (dynamic dispatch).", "Medium", "Software Engineering", "Previous Exam"),
    ("Which structural design pattern provides a unified, simplified high-level interface to a complex subsystem of classes?",
     ["Facade", "Flyweight", "Composite", "Bridge"], 0,
     "The Facade pattern wraps intricate subsystem APIs behind a simple, cohesive interface to make the subsystem easier to use.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Technical Debt in software engineering?",
     ["Financial debt incurred by buying cloud servers", "The implied cost of future additional rework caused by choosing an easy, fast solution now instead of a better architectural approach", "Salary owed to contract programmers", "The cost of commercial software licenses"], 1,
     "Ward Cunningham coined 'technical debt' to describe the compounding maintenance cost of taking expedient engineering shortcuts.", "Easy", "Software Engineering", "Previous Exam"),
    ("Which design pattern restricts the instantiation of a class to a single instance and provides a global access point to it?",
     ["Factory", "Singleton", "Prototype", "Builder"], 1,
     "Singleton guarantees a class has only one instance throughout the application lifecycle, maintaining a static global access method.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Interface Segregation Principle (ISP) in SOLID design?",
     ["Clients should not be forced to depend upon interfaces they do not use (prefer many small, specific interfaces over one bloated interface)", "Every class must have at least two interfaces", "Interfaces cannot have abstract methods", "All interfaces must be public"], 0,
     "ISP advises decomposing broad, monolithic interfaces into narrow, client-focused interfaces so implementing classes only care about methods they need.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the difference between White-Box Testing and Black-Box Testing?",
     ["White-Box tests internal code structures, logic branches, and paths with knowledge of the source code; Black-Box tests external functionality against requirements without inspecting internal code", "White-box tests hardware; black-box tests software", "Black-box is only performed by developers", "White-box testing cannot be automated"], 0,
     "White-box testing examines internal implementation and control flows; black-box testing validates inputs against expected outputs based on specifications.", "Easy", "Software Engineering", "Previous Exam"),
    ("Which creational design pattern separates the construction of a complex object from its representation, allowing the same construction process to create various representations step-by-step?",
     ["Builder Pattern", "Factory Method", "Flyweight Pattern", "Composite Pattern"], 0,
     "The Builder pattern constructs complex objects incrementally step-by-step, avoiding telescoping constructors.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the purpose of the Observer design pattern?",
     ["Define a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically", "Log user keyboard events to disk", "Observe CPU performance metrics", "Encrypt communication channels"], 0,
     "The Observer pattern (Publish-Subscribe) decouples subjects from observers, automatically broadcasting notifications upon state transitions.", "Easy", "Software Engineering", "Previous Exam"),
    ("What does 'Cohesion' mean in software modularity, and what is the recommended design practice?",
     ["The degree to which elements within a single module belong together; high cohesion is desired", "The degree of interdependence between different modules; high cohesion is desired", "The speed at which classes compile", "The number of lines of code per file"], 0,
     "High cohesion means a module focuses cleanly on a single unified responsibility; software should strive for high cohesion and loose coupling.", "Medium", "Software Engineering", "Previous Exam"),
    ("What does 'Coupling' mean in software engineering, and what is the best practice?",
     ["The degree of interdependence between software modules; loose (low) coupling is desired", "The connection between mouse and keyboard", "The relationship between client and server", "The number of variables in a function"], 0,
     "Coupling measures how closely connected two modules are; loose coupling minimizes ripples where modifying one module breaks another.", "Medium", "Software Engineering", "Previous Exam"),

    # 21-30
    ("In Git, what constitutes a 'commit' object internally?",
     ["A SHA-1/SHA-256 hash referencing a tree object (directory snapshot), parent commit hash(es), author/committer metadata, and a log message", "A simple diff text patch file", "A zip archive of the entire hard drive", "An encrypted password string"], 0,
     "Git commits are immutable directed acyclic graph (DAG) objects referencing a root tree object, metadata, author info, and parent commit hashes.", "Hard", "Software Engineering", "Previous Exam"),
    ("What does the 'git cherry-pick' command do?",
     ["Applies the changes introduced by a specific existing commit from one branch onto the current working branch as a new commit", "Deletes redundant branches", "Picks the newest version of Git from the internet", "Resolves merge conflicts automatically"], 0,
     "Cherry-pick copies the exact diff introduced by an arbitrary commit and reapplies it cleanly onto the currently active HEAD branch.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Regression Testing in software quality assurance?",
     ["Re-running functional and non-functional tests to ensure that previously developed and tested software still performs correctly after new changes or bug fixes", "Testing older deprecated hardware", "Testing software until the computer crashes", "Calculating developer productivity scores"], 0,
     "Regression testing confirms that recent code modifications, patches, or configuration updates have not unintentionally broken existing functionality.", "Easy", "Software Engineering", "Previous Exam"),
    ("Which behavioral design pattern encapsulates a request as an object, thereby letting you parameterize clients with different requests, queue or log requests, and support undoable operations?",
     ["Command Pattern", "Chain of Responsibility", "Mediator Pattern", "Memento Pattern"], 0,
     "The Command pattern packages an action, its receiver, and parameters into a standalone object, facilitating undo/redo stacks and task scheduling.", "Medium", "Software Engineering", "Previous Exam"),
    ("Which structural design pattern converts the interface of a class into another interface clients expect, enabling classes with incompatible interfaces to work together?",
     ["Adapter Pattern", "Bridge Pattern", "Composite Pattern", "Facade Pattern"], 0,
     "The Adapter pattern acts as a wrapper that translates calls from one interface into methods recognized by an incompatible existing class.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Continuous Integration (CI) in modern DevOps pipelines?",
     ["The practice of automating the integration of code changes from multiple contributors into a shared repository frequently, validated by automated builds and tests", "Continuously releasing software to end users every minute", "Continuous video calls between developers", "Writing code without using version control"], 0,
     "CI requires developers to merge code changes regularly into a shared mainline, where automated builds and unit tests immediately verify the integrity.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the difference between Continuous Delivery and Continuous Deployment?",
     ["In Continuous Delivery, code changes are automatically tested and staged for release, but production deployment requires manual approval; in Continuous Deployment, every passing change is deployed to production automatically", "Continuous Delivery only delivers emails", "Continuous Deployment does not run automated tests", "They are identical synonyms"], 0,
     "Continuous Delivery stops before production deployment pending human release sign-off; Continuous Deployment automates the push straight to production.", "Medium", "Software Engineering", "Previous Exam"),
    ("In object-oriented programming, what is Encapsulation?",
     ["Bundling data (attributes) and the methods that operate on that data into a single unit (class), while restricting direct access to internal state (information hiding)", "Writing code in capital letters", "Inheriting from multiple parent classes simultaneously", "Executing code across multiple threads"], 0,
     "Encapsulation hides an object's internal implementation details, exposing operations exclusively through controlled public interfaces.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Polymorphism in object-oriented programming?",
     ["The ability of different classes to respond to the same method call in ways specific to their own data types", "Having multiple computer monitors", "Writing code that compiles on Windows and Linux", "A database containing multiple tables"], 0,
     "Polymorphism allows objects of different subtypes to be treated uniformly through a parent interface while executing class-specific behaviors.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the difference between Composition and Inheritance in object-oriented design?",
     ["Composition ('has-a') models relationships by containing instances of other classes, offering greater runtime flexibility; Inheritance ('is-a') derives subclass behavior from a base class at compile time", "Inheritance is always preferred over composition", "Composition cannot use polymorphism", "Inheritance allows modifying parent classes at runtime"], 0,
     "'Favor composition over inheritance' is a core OOP tenet: composition provides loose coupling and dynamic behavioral replacement without tight inheritance hierarchies.", "Medium", "Software Engineering", "Previous Exam"),

    # 31-40
    ("Which design pattern captures and externalizes an object's internal state without violating encapsulation, so that the object can be restored to this state later (Undo mechanism)?",
     ["Memento Pattern", "State Pattern", "Visitor Pattern", "Template Method"], 0,
     "The Memento pattern stores a snapshot of an object's state inside a memento object, allowing rollbacks without exposing private attributes.", "Medium", "Software Engineering", "Previous Exam"),
    ("Which design pattern allows an object to alter its behavior when its internal state changes, appearing to change its class?",
     ["State Pattern", "Strategy Pattern", "Command Pattern", "Chain of Responsibility"], 0,
     "The State pattern implements state machines by representing states as independent classes that handle actions differently based on current state.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the Template Method design pattern?",
     ["Defines the skeleton of an algorithm in a base class method, deferring some implementation steps to subclasses without changing the algorithm's overall structure", "A method that creates C++ templates", "A design pattern for creating HTML templates", "A pattern that prevents subclassing"], 0,
     "Template Method defines an algorithm workflow in a superclass method, letting derived classes override specific primitive hook steps.", "Medium", "Software Engineering", "Previous Exam"),
    ("Which structural design pattern uses sharing to support large numbers of fine-grained objects efficiently by separating intrinsic state from extrinsic state?",
     ["Flyweight Pattern", "Composite Pattern", "Proxy Pattern", "Decorator Pattern"], 0,
     "Flyweight minimizes memory footprint by sharing common immutable intrinsic data across thousands of similar objects (e.g., character glyphs in word processors).", "Hard", "Software Engineering", "Previous Exam"),
    ("Which behavioral design pattern passes a request along a dynamic chain of potential handler objects until one of them handles it?",
     ["Chain of Responsibility", "Command Pattern", "Mediator Pattern", "Visitor Pattern"], 0,
     "Chain of Responsibility decouples request senders from receivers by giving multiple handlers a chance to process the request (e.g., middleware pipelines).", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the Mediator design pattern used for?",
     ["Define an object that encapsulates how a set of objects interact, preventing direct references between them and promoting loose coupling", "A proxy between client and database", "A pattern for sorting arrays", "A tool for resolving Git merge conflicts"], 0,
     "Mediator centralizes complex inter-object communication into a single mediator object (e.g., a dialog controller coordinating buttons and text fields).", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the Visitor design pattern?",
     ["A behavioral pattern that allows adding new operations to existing class hierarchies without modifying the classes themselves", "A pattern that tracks website visitors", "A pattern that handles guest logins", "A pattern for recursive file deletion"], 0,
     "Visitor uses double-dispatch to separate algorithms from the object structures on which they operate, facilitating new operations without class alterations.", "Hard", "Software Engineering", "Previous Exam"),
    ("What is the Composite design pattern?",
     ["Composes objects into tree structures to represent part-whole hierarchies, allowing clients to treat individual objects and compositions of objects uniformly", "A pattern combining factory and singleton", "A method for merging database tables", "An audio mixing algorithm"], 0,
     "Composite enables recursive tree structures (like UI widget trees or file directory systems) where leaves and containers implement the same interface.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the Proxy design pattern?",
     ["Provides a surrogate or placeholder for another object to control access to it (e.g., Virtual Proxy for lazy loading, Remote Proxy, Protection Proxy)", "A network hardware router", "An automated web scraper", "A compiler optimization technique"], 0,
     "The Proxy pattern controls and intercepts access to an underlying target object, adding caching, access authorization, or lazy initialization.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Bridge design pattern?",
     ["Decouples an abstraction from its implementation so that the two can vary independently", "Connects two computers via Ethernet", "Converts procedural code to OOP", "Bridges SQL and NoSQL databases"], 0,
     "The Bridge pattern replaces inheritance with object composition to separate an abstract class hierarchy from multiple concrete platform implementations.", "Hard", "Software Engineering", "Previous Exam"),

    # 41-50
    ("What is the Prototype design pattern?",
     ["Specifies the kinds of objects to create using a prototypical instance, creating new objects by cloning this existing prototype", "A rough draft of an application UI", "A beta version of software released to testers", "A factory that builds cars"], 0,
     "Prototype enables creating new objects by cloning pre-configured prototypical instances (deep or shallow copying), bypassing complex constructors.", "Easy", "Software Engineering", "Previous Exam"),
    ("In Agile Scrum, what is the Product Backlog?",
     ["An ordered, prioritized list of everything that is known to be needed in the product, owned and maintained by the Product Owner", "A list of past software bugs that were never fixed", "A backup of the source code repository", "The list of tasks completed in the previous sprint"], 0,
     "The Product Backlog is a dynamic, living roadmap of features, user stories, improvements, and fixes prioritized by business value.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is a Sprint Planning meeting in Scrum?",
     ["A collaborative meeting at the beginning of a sprint where the team selects items from the Product Backlog to commit to the Sprint Backlog", "A meeting where developers receive annual bonuses", "A meeting to write marketing materials", "A post-mortem meeting after an outage"], 0,
     "Sprint Planning defines what can be delivered in the upcoming sprint and how that work will be achieved, creating the Sprint Backlog.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is a Sprint Retrospective meeting in Scrum?",
     ["A dedicated team ceremony held at the end of a sprint to inspect team processes, discuss what went well and what didn't, and plan improvements", "A demonstration of working software to external stakeholders", "A code review of all commits", "An employee performance evaluation"], 0,
     "The Retrospective provides continuous team process improvement, inspecting interpersonal dynamics, tools, and workflows to refine the next sprint.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is a Sprint Review (Demo) meeting in Scrum?",
     ["A meeting at the end of the sprint where the Scrum team inspects the Increment of done software with stakeholders and adapts the Product Backlog", "A meeting where developers take written quizzes", "A meeting to plan vacation schedules", "A code refactoring workshop"], 0,
     "Sprint Review showcases working, completed increments to stakeholders to solicit direct feedback and adapt future backlog priorities.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the purpose of WIP (Work in Progress) limits in Kanban methodology?",
     ["Restrict the maximum number of task items allowed in any single workflow column at one time to prevent bottlenecks and improve throughput", "Limit the number of hours developers work per week", "Prevent developers from using external libraries", "Limit the number of git commits per day"], 0,
     "Kanban WIP limits optimize flow and expose system bottlenecks by forbidding teams from pulling new work until active tasks are finished.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the difference between a Stub and a Mock in automated unit testing?",
     ["A stub provides pre-canned dummy responses to method calls made during the test; a mock additionally verifies that specific expected method calls and interactions actually took place", "A stub is for C++, a mock is for Java", "Mocks cannot return values", "Stubs test databases while mocks test UI"], 0,
     "Stubs supply canned state data to satisfy dependencies; mocks set expectations on behavioral interactions and verify method call counts/arguments.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Branch Coverage in unit test suite analysis?",
     ["The percentage of decision outcomes (both TRUE and FALSE branches of every if/conditional) executed by the test suite", "The number of Git branches merged this week", "The percentage of lines of comments in code", "The number of functions tested"], 0,
     "Branch coverage ensures that every branch of every control flow structure (e.g., both branches of an if-else statement) is exercised by tests.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Mutation Testing in software engineering?",
     ["A technique where small semantic bugs (mutants) are deliberately introduced into source code to verify whether the unit test suite catches them", "Testing genetic algorithms in AI", "Testing software under extreme hardware heat", "Writing tests that rewrite themselves"], 0,
     "Mutation testing assesses test suite quality: if introduced mutations (e.g., changing '>' to '<=') pass tests unnoticed, test assertions are inadequate.", "Hard", "Software Engineering", "Previous Exam"),
    ("What is a 'Code Smell' in software refactoring?",
     ["A surface indicator in source code that usually corresponds to a deeper design defect or maintenance liability (e.g., Long Method, God Object)", "A corrupted hard drive sector", "A syntax error that prevents compilation", "An unformatted JSON string"], 0,
     "Code smells (coined by Kent Beck) are diagnostic heuristics indicating code that, while functional, violates design principles and hampers maintainability.", "Easy", "Software Engineering", "Previous Exam"),

    # 51-60
    ("What is the 'God Object' (or Blob) antipattern?",
     ["An antipattern where a single gargantuan class monopolizes most application responsibilities and state, reducing other classes to passive data containers", "A software object with infinite computing power", "A database table with one billion rows", "An operating system superuser account"], 0,
     "The God Object antipattern violates the Single Responsibility Principle by aggregating vast disparate operations into an unmaintainable behemoth.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the DRY (Don't Repeat Yourself) principle?",
     ["Every piece of knowledge or business logic must have a single, unambiguous, authoritative representation within a system", "Never run a unit test more than once", "Do not write code when dehydrated", "Never reuse code from open source libraries"], 0,
     "DRY dictates eliminating duplicate code and logic representations to prevent maintenance synchronization bugs across the codebase.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the YAGNI (You Aren't Gonna Need It) principle?",
     ["A programmer should not add functionality until deemed strictly necessary by current real requirements, avoiding speculative over-engineering", "Delete all code after testing", "Do not document software architecture", "Never write unit tests"], 0,
     "YAGNI (from Extreme Programming) discourages implementing unrequested features based on speculative future requirements.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Law of Demeter (Principle of Least Knowledge)?",
     ["A module should only talk to its immediate friends (avoid chained method calls like a.getB().getC().doSomething()) to minimize coupling", "A law limiting database query sizes", "A principle governing network routing tables", "A software licensing guideline"], 0,
     "The Law of Demeter states that an object should only invoke methods on itself, its fields, method arguments, or objects it creates.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Inversion of Control (IoC)?",
     ["A design paradigm where the custom-written portions of a program receive the flow of control from a generic framework, inverting traditional library calls", "Inverting screen orientation for mobile apps", "Reversing string characters in memory", "Giving end-users root privileges"], 0,
     "IoC (the Hollywood Principle: 'Don't call us, we'll call you') inverts control flow so frameworks dictate execution, invoking user code via hooks.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Dependency Injection (DI)?",
     ["A software design technique where an object receives its dependencies from an external assembler rather than instantiating them internally", "Injecting SQL commands into forms", "Injecting DLLs into other processes maliciously", "Installing dependencies via package managers"], 0,
     "DI supplies dependent objects (via constructor, setter, or interface injection), decoupling classes from concrete dependency construction.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Trunk-Based Development in Git workflow strategies?",
     ["A branching strategy where developers merge small, frequent updates directly into a single shared core branch ('trunk' or 'main'), avoiding long-lived feature branches", "Storing code on wooden storage media", "Creating a new branch for every single line of code", "Freezing code releases for 6 months"], 0,
     "Trunk-based development emphasizes frequent micro-merges into the mainline, preventing painful merge conflicts and accelerating CI/CD velocity.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Git Flow?",
     ["A structured branching model utilizing long-lived 'main' and 'develop' branches alongside dedicated feature, release, and hotfix branches", "A command that cleans git repositories", "A graphical UI for Git built into Linux", "A peer-to-peer Git protocol"], 0,
     "Git Flow is a formalized release-oriented branching model defining specific lifecycles for develop, feature, release, and hotfix branches.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the difference between 'git reset --soft' and 'git reset --hard'?",
     ["--soft resets HEAD to a specified commit while keeping all changes staged in the index; --hard resets HEAD, index, and working tree, completely discarding all uncommitted changes", "--soft deletes files while --hard keeps them", "--hard is used only on hardware servers", "--soft only works on feature branches"], 0,
     "git reset --soft moves the commit pointer back without touching staged files; --hard wipes working directory modifications permanently.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is a Git detached HEAD state?",
     ["HEAD points directly to a specific commit hash rather than to a named branch reference, meaning new commits will not belong to any branch", "A fatal corruption of the git repository", "A headless server with no monitor connected", "A git repository without a remote origin"], 0,
     "Detached HEAD occurs when checking out a specific commit or tag; commits made in this state become orphaned if you switch branches without saving them.", "Medium", "Software Engineering", "Previous Exam"),

    # 61-70
    ("What is Semantic Versioning (SemVer) format MAJOR.MINOR.PATCH?",
     ["MAJOR for breaking API changes, MINOR for backwards-compatible new features, PATCH for backwards-compatible bug fixes", "MAJOR for year, MINOR for month, PATCH for day", "MAJOR for team size, MINOR for sprint count, PATCH for bug count", "Arbitrary marketing numbers"], 0,
     "SemVer (e.g., 2.4.1) establishes clear upgrade expectations: increment MAJOR for breaking changes, MINOR for additive features, PATCH for fixes.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Canary Deployment in software release strategies?",
     ["Rolling out a new software version to a small, isolated subset of real users first to monitor stability before releasing it to the entire user base", "Deploying software to coal mining computers", "Releasing software exclusively on weekends", "Testing software with simulated bots"], 0,
     "Canary deployment exposes a tiny percentage of live traffic to the new version to detect errors early before impacting all users.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Blue-Green Deployment?",
     ["A deployment strategy utilizing two identical production environments (Blue and Green); one serves live traffic while the other is updated, followed by switching router traffic instantly", "A user interface color palette testing method", "Alternating between day and night shifts", "Deploying software only during spring"], 0,
     "Blue-Green deployment ensures near-zero downtime and instantaneous rollback by toggling traffic between active and standby production environments.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Chaos Engineering (e.g., Netflix Chaos Monkey)?",
     ["The discipline of experimenting on a software system in production by intentionally injecting failures to build confidence in system resilience", "Writing code without coding standards", "Deploying uncompiled code directly to servers", "Allowing users to alter database schemas"], 0,
     "Chaos engineering proactively induces infrastructure failures (e.g., terminating random servers) to verify automated self-healing capabilities.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Circuit Breaker pattern in distributed microservices?",
     ["A design pattern that detects failures and encapsulates the logic of preventing a failure from constantly recurring during maintenance or temporary outages, failing fast", "A mechanical fuse inside a datacenter", "A pattern that stops infinite recursive loops", "A firewall rule blocking hackers"], 0,
     "Circuit Breakers wrap network calls to downstream services; when failure thresholds are crossed, the breaker trips to fail fast and prevent cascading system collapse.", "Hard", "Software Engineering", "Previous Exam"),
    ("What is CQRS (Command Query Responsibility Segregation)?",
     ["An architectural pattern that separates read operations (queries) from write/update operations (commands) into distinct data models", "A protocol for sending chat messages", "A security standard for passwords", "A database indexing strategy"], 0,
     "CQRS uses separate models to update information (commands) and read information (queries), allowing independent scaling and optimization for read/write paths.", "Hard", "Software Engineering", "Previous Exam"),
    ("What is Event Sourcing?",
     ["An architectural pattern where all changes to application state are stored as an immutable sequence of historical events rather than just current state", "Finding event tickets online", "Listening to DOM click events in JavaScript", "Sourcing hardware parts from suppliers"], 0,
     "Event Sourcing records every state transition as an append-only event log, enabling full auditability, temporal queries, and event replay.", "Hard", "Software Engineering", "Previous Exam"),
    ("What is Hexagonal Architecture (Ports and Adapters)?",
     ["An architectural pattern that isolates the core application business logic from external dependencies (DBs, UIs, APIs) using ports (interfaces) and adapters", "An app layout with 6-sided buttons", "A networking topology with 6 routers", "A 6-tier client-server model"], 0,
     "Alistair Cockburn's Hexagonal Architecture insulates business logic from I/O mechanisms, making core domains testable without real databases or frameworks.", "Hard", "Software Engineering", "Previous Exam"),
    ("What is the difference between Functional and Non-Functional Requirements?",
     ["Functional requirements define what the system should do (features, behaviors); Non-functional requirements define how the system performs (scalability, security, latency, availability)", "Functional requirements are written in code; Non-functional in English", "Non-functional requirements are optional suggestions", "Functional requirements only apply to databases"], 0,
     "Functional requirements specify behavioral features; non-functional requirements (the '-ilities') define quality attributes like throughput, reliability, and security.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Cyclomatic Complexity in software metrics?",
     ["A quantitative measure of the number of linearly independent paths through a program's source code (calculated as Edges - Nodes + 2P)", "The number of cycles a CPU takes per instruction", "The total number of classes in a project", "The number of nested loops in an algorithm"], 0,
     "Thomas McCabe's Cyclomatic Complexity measures decision logic density; high complexity correlates with defect likelihood and testing difficulty.", "Medium", "Software Engineering", "Previous Exam"),

    # 71-80
    ("In object-oriented design, what is Dynamic Dispatch?",
     ["The runtime mechanism of determining which specific polymorphic method implementation to invoke based on the actual concrete runtime type of the object", "Dispatching emergency service alerts", "Scheduling threads on multiple CPU cores", "Dynamic loading of DLLs at boot"], 0,
     "Dynamic dispatch uses runtime virtual method tables (vtables) to resolve overridden method calls to the appropriate subclass implementation.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is an Abstract Class in object-oriented programming?",
     ["A class that cannot be instantiated directly and is designed to be subclassed, typically containing one or more abstract methods lacking implementation", "A class with no methods or variables", "A class imported from an external library", "A class compiled without optimizations"], 0,
     "Abstract classes define shared structure and default behaviors while enforcing that derived concrete classes implement designated abstract methods.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is an Interface in programming languages like Java, TypeScript, or C#?",
     ["A contract defining a set of method signatures and properties that implementing classes must fulfill, without providing implementation state", "A graphical user interface on screen", "A physical HDMI port on a computer", "A command-line terminal window"], 0,
     "Interfaces specify pure behavioral contracts, decoupling API consumers from concrete class implementations and enabling multi-type polymorphism.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Diamond Problem in object-oriented programming with multiple inheritance?",
     ["Ambiguity arising when a subclass inherits from two parent classes that both inherit from a single common grandparent, duplicating methods and state", "A diamond-shaped database schema", "An encryption algorithm using diamond keys", "A hard drive failure pattern"], 0,
     "The diamond problem occurs when class D inherits from B and C, both inheriting from A; if B and C override a method from A, D's inheritance path is ambiguous.", "Medium", "Software Engineering", "Previous Exam"),
    ("How does Java solve the Diamond Problem regarding state inheritance?",
     ["By disallowing multiple inheritance of classes (single class inheritance only), while permitting multiple interface implementation", "By ignoring inherited methods", "By using C++ templates", "By generating two separate JVM processes"], 0,
     "Java restricts classes to single class inheritance, eliminating state ambiguity while allowing implementation of multiple interfaces.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Static Code Analysis?",
     ["The analysis of computer software performed without actually executing the program, inspecting source code for vulnerabilities, bugs, and style violations", "Analyzing RAM usage while playing games", "Running unit tests with a debugger", "Testing network cable throughput"], 0,
     "Static analysis tools (e.g., ESLint, SonarQube) parse ASTs without running code, detecting security vulnerabilities and anti-patterns early.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Dynamic Analysis in software testing?",
     ["Analyzing a program by executing it with real or simulated inputs on a physical or virtual processor (e.g., memory leak profiling, fuzzing)", "Reading code printed on paper", "Measuring code typing speed", "Reviewing git commit messages"], 0,
     "Dynamic analysis inspects program behavior during execution (profilers, Valgrind, fuzzers), uncovering memory leaks and race conditions.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Smoke Testing in software development?",
     ["A preliminary suite of basic, high-level tests run on initial builds to verify that the most critical functions work before proceeding to deeper testing", "Testing hardware components with high voltage", "Testing a computer in high-smoke environments", "Testing the cooling fans of a server"], 0,
     "Smoke tests (sanity checks) quickly verify whether a build is stable enough to justify rigorous, time-consuming functional testing.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Black-Box Equivalence Partitioning?",
     ["A test design technique dividing input data into valid and invalid partitions where all values in a partition are expected to be treated similarly by the software", "Partitioning hard drives into NTFS and ext4", "Dividing developers into equal teams", "Splitting network packets into equal halves"], 0,
     "Equivalence partitioning reduces necessary test cases by selecting representative values from each equivalence class of input data.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Boundary Value Analysis (BVA)?",
     ["A test design technique focusing on testing values at the boundaries of equivalence partitions (e.g., min, min+1, max-1, max)", "Measuring network bandwidth boundaries", "Testing hard drive physical edges", "Testing CPU overclock limits"], 0,
     "BVA complements equivalence partitioning by concentrating tests on boundaries where off-by-one programming errors cluster most heavily.", "Easy", "Software Engineering", "Previous Exam"),

    # 81-90
    ("What is User Acceptance Testing (UAT)?",
     ["The final phase of software testing where actual end users verify whether the system satisfies business requirements and workflows in real scenarios", "Automated unit testing on developer laptops", "Stress testing database servers", "Testing user password strength"], 0,
     "UAT confirms that the completed software delivers the business value intended by stakeholders before production rollout.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Waterfall Model in software engineering?",
     ["A sequential, linear development lifecycle where each phase (Requirements, Design, Implementation, Verification, Maintenance) must complete before the next begins", "An Agile sprint methodology", "A database replication protocol", "A streaming video protocol"], 0,
     "Waterfall is a rigid, document-driven linear model where progress cascades steadily downward through sequential phases without iterative feedback loops.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Spiral Model of software development?",
     ["A risk-driven process model that combines iterative development with systematic aspects of the waterfall model, emphasizing continuous risk analysis", "A 3D spiral data structure", "A software architecture with circular dependencies", "An agile scrum board shaped like a wheel"], 0,
     "Barry Boehm's Spiral Model repeats planning, risk assessment, engineering, and evaluation phases iteratively to mitigate high-risk project variables.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the V-Model (Validation and Verification Model)?",
     ["An extension of the waterfall model demonstrating the relationship between each development phase and its corresponding testing phase", "A vector graphics rendering engine", "A version control branching strategy", "A virtual machine hypervisor model"], 0,
     "The V-model maps development stages directly to testing counterparts (e.g., Requirements <-> Acceptance Testing; Unit Design <-> Unit Testing).", "Medium", "Software Engineering", "Previous Exam"),
    ("In Git, what does 'git stash' do?",
     ["Temporarily shelves (stashes) uncommitted dirty working directory changes so you can work on a clean branch, allowing changes to be reapplied later", "Permanently deletes untracked files", "Pushes commits to the main branch", "Creates a zip archive of the repository"], 0,
     "git stash saves uncommitted modifications to an internal stack, returning the working tree to a clean HEAD state without losing work.", "Easy", "Software Engineering", "Previous Exam"),
    ("What does 'git blame' (or git annotate) display?",
     ["Shows the author, timestamp, and commit hash for each line of a specified file", "Logs compiler syntax error messages", "Lists team members who missed sprint deadlines", "Lists corrupted git commits"], 0,
     "git blame displays inline file history, identifying who modified each specific line of code and in which commit.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is an Epic in Agile project management?",
     ["A large body of work or broad user requirement that can be broken down into multiple smaller user stories across several sprints", "A bug that crashes the entire production cluster", "A very long sprint lasting 6 months", "A popular game engine"], 0,
     "An Epic captures high-level strategic customer initiatives that are decomposed into manageable, testable user stories.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Definition of Done (DoD) in Scrum?",
     ["A shared, formal checklist of criteria that a product increment must meet before it can be considered complete and releasable", "The time of day developers stop working", "The final date of a software contract", "When all unit tests pass once"], 0,
     "DoD provides team-wide consensus on completeness criteria (e.g., coded, peer-reviewed, unit tested, integrated, documented).", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Velocity of a Scrum team?",
     ["A metric measuring the amount of work (in story points) a development team completes during a typical sprint", "The physical typing speed of programmers", "The network latency of CI/CD runners", "The speed at which bugs are filed"], 0,
     "Velocity tracks historical story points completed per sprint, aiding sprint forecasting and capacity planning.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is Pair Programming in Extreme Programming (XP)?",
     ["A software development technique where two programmers work together at one workstation: one acts as the Driver (writes code) and one as the Navigator (reviews code real-time)", "Two developers sharing a git password", "Working on two computers simultaneously", "Running two programs side-by-side"], 0,
     "Pair programming pairs a Driver who types code with a Navigator who focuses on the bigger picture, continuously reviewing and spotting defects.", "Easy", "Software Engineering", "Previous Exam"),

    # 91-100
    ("What is Refactoring in software engineering?",
     ["The process of restructuring existing computer code without changing its external observable behavior, improving non-functional attributes like readability and maintainability", "Rewriting an entire application from scratch in a new language", "Fixing reported user bugs", "Reinstalling the operating system"], 0,
     "Refactoring cleans internal code structure, simplifies design, and eliminates technical debt without altering functional behavior.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is a Design Pattern in software architecture?",
     ["A reusable, general solution to a commonly occurring problem within a given context in software design", "A visual CSS template for website styling", "A flow chart of database tables", "A proprietary programming language syntax"], 0,
     "Design patterns are codified architectural blueprints describing proven solutions to recurring object-oriented structural and behavioral challenges.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the Open-Closed Principle primarily aimed at preventing?",
     ["Fragile software where modifying existing working code inadvertently introduces bugs into dependent modules", "Users from closing the web browser", "Competitors from viewing source code", "Open-source licensing violations"], 0,
     "OCP prevents regression bugs: by extending behaviors through polymorphism rather than editing mature classes, existing code remains stable.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the Single Responsibility Principle (SRP) definition by Robert C. Martin?",
     ["A class should have one, and only one, reason to change", "A class should contain only one method", "A function should accept only one parameter", "A programmer should work on only one task per day"], 0,
     "SRP states that each module or class should be responsible to a single actor, giving it exactly one reason to change.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the purpose of the Object Pool design pattern?",
     ["Recycle expensive-to-create objects (such as database connections or threads) by maintaining a pool of pre-initialized instances ready for use", "A swimming pool at a tech campus", "A data structure storing memory pointers", "A trash collector for unused variables"], 0,
     "Object Pool reuses reusable instances (e.g., database connection pooling) to avoid repetitive allocation and initialization overhead.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Inversion of Control Containers (IoC Containers) commonly used for in frameworks like Spring or NestJS?",
     ["Manage the creation, configuration, lifecycle, and automatic dependency injection of application objects", "Run Docker containers in the cloud", "Isolate untrusted user code", "Compress compiled JavaScript bundles"], 0,
     "IoC containers act as object assemblers, wiring components together through dependency injection based on configuration or annotations.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is the Anti-Pattern known as 'Spaghetti Code'?",
     ["Source code with a complex, tangled, and unstructured control flow, typically caused by excessive goto statements or uncontrolled branching", "A recipe application written in Python", "Code generated by artificial intelligence", "Code written without comments"], 0,
     "Spaghetti code lacks modular structure, making tracking execution flow and maintaining software exceedingly difficult.", "Easy", "Software Engineering", "Previous Exam"),
    ("What is the 'Shotgun Surgery' code smell?",
     ["A design problem where making a single conceptual change requires making lots of little edits across many different classes", "A fast way to fix emergency bugs", "Splitting one class into 100 files", "Automated code refactoring by AI"], 0,
     "Shotgun Surgery is the opposite of Divergent Change: one modification ripples out into minor edits across numerous disparate classes.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Divergent Change in code smell classification?",
     ["A single class is commonly changed in different ways for different reasons by different stakeholders (violating SRP)", "Code diverging between git branches", "Changing variable names during refactoring", "Compiling code for multiple platforms"], 0,
     "Divergent Change occurs when one class suffers modifications for multiple independent business requirements.", "Medium", "Software Engineering", "Previous Exam"),
    ("What is Feature Envy in object-oriented code smells?",
     ["A method that seems more interested in the data and methods of another class than in the one it actually resides in", "A developer wanting features from another project", "An application copying features from competitors", "A test that tests other modules"], 0,
     "Feature Envy occurs when a method spends most of its execution querying fields and getters of another class, suggesting it belongs in that other class.", "Medium", "Software Engineering", "Previous Exam")
]

print(f"Total Part 5 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part5_data = []
for i, q in enumerate(questions):
    qid = f"p5-q{i+1}"
    part5_data.append({
        "id": qid,
        "part": 5,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part5.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_5_QUESTIONS: Question[] = ")
    json.dump(part5_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 5 successfully to src/data/parts/part5.ts")
