#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("In search algorithms, what condition must a heuristic function h(n) satisfy for the A* search algorithm to be guaranteed to find the optimal shortest path on trees?",
     ["Admissibility: h(n) must never overestimate the true cost to reach the nearest goal state (h(n) <= h*(n))", "Monotonicity only on negative costs", "h(n) must equal 0 for all nodes", "h(n) must be strictly greater than the true path cost"], 0,
     "An admissible heuristic never overestimates the remaining cost to the goal, mathematically guaranteeing the tree-search optimality of A*.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What additional condition must a heuristic function h(n) satisfy for A* graph search (with closed sets) to guarantee optimality without reopening explored nodes?",
     ["Consistency (or Monotonicity): for every node n and successor n' via action a, h(n) <= c(n, a, n') + h(n')", "Symmetry: h(n) = h(start)", "Linearity: h(n) = 2n", "Transitivity: h(n) > h(n')"], 0,
     "Consistency (the triangle inequality for heuristics) guarantees that f(n) values are monotonically non-decreasing along any path, eliminating the need to reopen closed nodes.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In adversarial two-player zero-sum games, what is the best-case time complexity of the Minimax algorithm when optimal Alpha-Beta pruning is applied?",
     ["O(b^(d/2)) where b is branching factor and d is search depth", "O(b * d)", "O(b^d)", "O(d^2)"], 0,
     "Alpha-Beta pruning with optimal move ordering halves the effective search exponent from O(b^d) down to O(b^(d/2)), effectively doubling the search depth.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In machine learning, what does the Bias-Variance tradeoff describe?",
     ["High bias causes Underfitting (oversimplified model failing to capture data trends); High variance causes Overfitting (model modeling training noise)", "The tradeoff between GPU cost and cloud memory", "The tradeoff between dataset size and disk space", "The tradeoff between training speed and download time"], 0,
     "Bias measures systematic prediction error from flawed assumptions (underfitting); variance measures model sensitivity to fluctuations in training data (overfitting).", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the mathematical difference between L1 Regularization (Lasso) and L2 Regularization (Ridge) in linear models?",
     ["L1 adds the sum of absolute values of weights (|w|) to the loss function, producing sparse models with feature selection; L2 adds the sum of squared weights (w^2)", "L2 sets weights to exact zero", "L1 is only used on decision trees", "L2 increases the number of features"], 0,
     "L1 penalizes absolute weights (|w|), driving irrelevant feature weights to exact zero (sparsity); L2 penalizes squared weights (w^2), shrinking weights smoothly.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In binary classification evaluation, what is the formula for Precision?",
     ["True Positives / (True Positives + False Positives)", "True Positives / (True Positives + False Negatives)", "(True Positives + True Negatives) / Total", "True Negatives / (True Negatives + False Positives)"], 0,
     "Precision measures the proportion of predicted positive instances that were truly positive: TP / (TP + FP).", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("In binary classification evaluation, what is the formula for Recall (Sensitivity)?",
     ["True Positives / (True Positives + False Negatives)", "True Positives / (True Positives + False Positives)", "True Negatives / (True Negatives + False Positives)", "False Positives / Total"], 0,
     "Recall measures the proportion of actual positive cases that the model correctly identified: TP / (TP + FN).", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the F1-Score in machine learning evaluation metrics?",
     ["The harmonic mean of Precision and Recall: 2 * (Precision * Recall) / (Precision + Recall)", "The arithmetic average of Accuracy and Loss", "The difference between True Positives and False Positives", "The area of the ROC curve divided by 2"], 0,
     "The F1-Score is the harmonic mean of precision and recall, providing a balanced metric especially on imbalanced datasets.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What does an ROC (Receiver Operating Characteristic) curve plot?",
     ["True Positive Rate (Sensitivity / Recall) on the y-axis against False Positive Rate (1 - Specificity) on the x-axis across various classification thresholds", "Training Loss against Epochs", "Precision against Training Time", "Accuracy against Dataset Size"], 0,
     "The ROC curve visualizes diagnostic tradeoff across all classification thresholds; Area Under Curve (AUC) summarizes aggregate discriminatory power.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In Decision Tree learning algorithms (such as ID3 or C4.5), how is Information Gain calculated?",
     ["Entropy(Parent) - Weighted Average of Entropies of Children", "Parent Accuracy minus Child Accuracy", "Gini index multiplied by variance", "Number of leaf nodes divided by depth"], 0,
     "Information Gain measures the reduction in entropy (uncertainty) achieved by partitioning a dataset on a specific feature attribute.", "Medium", "AI & Machine Learning", "Previous Exam"),

    # 11-20
    ("What is Gini Impurity in CART (Classification and Regression Trees)?",
     ["A metric measuring the probability of incorrectly classifying a randomly chosen element if it were labeled randomly according to class distribution: 1 - sum(p_i^2)", "The impurity of water in datacenter cooling", "The variance of continuous regression targets", "The ratio of errors in training data"], 0,
     "Gini impurity measures distribution heterogeneity: 0 indicates a completely pure node (all items belong to one class).", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the Random Forest algorithm and how does it prevent overfitting?",
     ["An ensemble of decision trees trained using Bagging (Bootstrap Aggregation) and random feature sub-sampling at each split", "A forest of neural networks sharing memory", "A genetic algorithm for training trees", "A single tree grown to maximum depth"], 0,
     "Random Forests combine bootstrap aggregating with random feature subsets at each split node, decorrelating individual trees and lowering ensemble variance.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the primary difference between Bagging and Boosting ensemble methods?",
     ["Bagging trains independent models in parallel and averages their predictions; Boosting trains models sequentially, where each new model focuses on correcting previous errors", "Bagging is for regression; Boosting is for classification", "Boosting runs in parallel on GPUs", "Bagging uses neural networks exclusively"], 0,
     "Bagging (e.g., Random Forest) decreases variance in parallel; Boosting (e.g., AdaBoost, XGBoost) reduces bias sequentially by weighting misclassified instances.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In Support Vector Machines (SVM), what is the 'Kernel Trick'?",
     ["Implicitly mapping input data into a higher-dimensional feature space using an inner-product kernel function (e.g., RBF) without computing explicit coordinates", "A trick to reboot the Linux kernel", "A method for accelerating matrix multiplication on GPUs", "A script that automates parameter tuning"], 0,
     "The kernel trick computes dot products directly in high-dimensional Hilbert spaces using kernel functions (K(x, z) = phi(x) . phi(z)), making non-linear separation computationally feasible.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In the K-Means clustering algorithm, how are data points assigned to clusters during each iteration?",
     ["Each data point is assigned to the nearest cluster centroid based on Euclidean distance, and centroids are recomputed as the arithmetic mean of assigned points", "Points are sorted randomly into K bins", "Clusters are merged using hierarchical trees", "Centroids are assigned based on feature labels"], 0,
     "K-Means alternates between assignment (assign points to closest centroid) and update (recalculate centroids as cluster means) until convergence.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the 'Elbow Method' used for in K-Means clustering?",
     ["Determining the optimal number of clusters (K) by plotting within-cluster sum of squares (inertia) against K and identifying the inflection 'elbow' point", "Calculating CPU elbow angle on motherboards", "Detecting outlier points in the cluster", "Measuring algorithm execution time"], 0,
     "The elbow method graphs inertia versus K; the bend or 'elbow' indicates diminishing returns in variance explanation for additional clusters.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Principal Component Analysis (PCA) primarily used for?",
     ["Unsupervised linear dimensionality reduction by projecting data onto orthogonal axes (principal components) that maximize variance", "Supervised classification of image labels", "Training deep convolutional networks", "Compressing text files on disk"], 0,
     "PCA identifies orthogonal eigenvectors of the data covariance matrix corresponding to the largest eigenvalues, retaining maximum data variance in fewer dimensions.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the mathematical definition of the ReLU (Rectified Linear Unit) activation function in neural networks?",
     ["f(x) = max(0, x)", "f(x) = 1 / (1 + e^(-x))", "f(x) = (e^x - e^(-x)) / (e^x + e^(-x))", "f(x) = log(1 + e^x)"], 0,
     "ReLU returns x for positive values and 0 for negative inputs (f(x) = max(0, x)), speeding up gradient propagation and mitigating vanishing gradients.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the 'Dying ReLU' problem in deep neural networks?",
     ["A scenario where neurons get stuck outputting 0 for all inputs because large negative gradients push weights such that the neuron never activates again", "A CPU overheating while running ReLU", "A network running out of RAM during training", "A division by zero error in ReLU"], 0,
     "When weights update such that a ReLU unit receives negative inputs across the entire dataset, its gradient remains permanently 0, rendering it inactive ('dead').", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("How does the Leaky ReLU activation function address the Dying ReLU problem?",
     ["By assigning a small positive non-zero slope (e.g., 0.01x) to negative input values instead of flat zero: f(x) = max(alpha * x, x)", "By capping positive values at 1.0", "By using a sine wave function", "By squaring negative numbers"], 0,
     "Leaky ReLU maintains a small slope alpha for x < 0, allowing gradients to flow even when the unit is deactivated, preventing permanently dead neurons.", "Easy", "AI & Machine Learning", "Previous Exam"),

    # 21-30
    ("What mathematical rule is the Backpropagation algorithm in neural networks fundamentally based upon?",
     ["The Chain Rule of Calculus for composite function derivatives", "Bayes' Theorem of conditional probability", "Euler's Formula for complex numbers", "Pythagorean Theorem"], 0,
     "Backpropagation applies the calculus chain rule repeatedly from the output loss layer backward through hidden layers to compute partial derivatives dLoss/dWeight.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the Vanishing Gradient problem in deep neural networks, and which activation functions historically exacerbated it?",
     ["Gradients become exponentially small as they propagate backward through many layers, halting weight updates; exacerbated by Sigmoid and Tanh", "Gradients become infinite and overflow float32", "Loss drops to zero on the first epoch", "Memory allocation vanishes"], 0,
     "Sigmoid and Tanh saturate with derivatives <= 0.25; chaining these fractions across deep layers causes backward gradients to vanish exponentially.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the Exploding Gradient problem, and what common technique is used to stabilize training?",
     ["Gradients accumulate into massive values causing unstable updates or NaN overflows; mitigated using Gradient Clipping", "Gradients drop to negative values", "Weights become complex numbers", "Batch size shrinks to zero"], 0,
     "Gradient Clipping caps gradients to a predefined maximum L2 norm threshold, preventing catastrophic numerical overflow during backpropagation.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Dropout in deep neural network regularization?",
     ["Randomly deactivating (setting to zero) a fraction of neurons with probability p during each training forward pass", "Dropping corrupt training images from disk", "Disconnecting GPUs during training", "Removing layers from a network"], 0,
     "Dropout prevents co-adaptation of feature detectors by forcing the network to learn robust redundant representations across thinned sub-networks.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("How does Batch Normalization (BatchNorm) accelerate and stabilize the training of deep neural networks?",
     ["By normalizing layer inputs to zero mean and unit variance for each mini-batch, followed by learnable scale (gamma) and shift (beta) parameters", "By normalizing database rows in SQL", "By converting floating point numbers to 8-bit integers", "By sorting training samples alphabetically"], 0,
     "BatchNorm mitigates internal covariate shift, smooths the optimization loss landscape, and permits substantially higher learning rates.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the Adam (Adaptive Moment Estimation) optimizer?",
     ["An adaptive gradient optimization algorithm that computes individual adaptive learning rates for each parameter by tracking both first moments (mean) and second moments (uncentered variance) of gradients", "An optimizer named after Alan Turing", "A hardware accelerator chip", "A genetic algorithm optimizer"], 0,
     "Adam combines principles of Momentum (exponential moving average of gradients) and RMSProp (moving average of squared gradients) with bias corrections.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In Convolutional Neural Networks (CNNs), what does 'Padding = Same' mean?",
     ["Zero-padding is added to input borders so that the output feature map has the exact same spatial dimensions (height and width) as the input", "The kernel weights are identical to input", "The batch size is kept the same", "All channels have identical values"], 0,
     "'Same' padding adds appropriate zero borders around inputs, preventing spatial dimension shrinkage after convolution operations.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the primary function of a Max Pooling layer in a Convolutional Neural Network?",
     ["Downsample spatial dimensions (height and width), reducing computational parameters while providing translation invariance for detected features", "Multiply input features by maximum weight", "Normalize features to range [0, 1]", "Convert 2D images into 1D vectors"], 0,
     "Max pooling extracts the maximum value within pooling windows, downsampling resolution and retaining dominant localized feature activations.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What architectural innovation allowed Deep Residual Networks (ResNet) to train networks exceeding 100 layers successfully?",
     ["Skip Connections (Residual Connections) that pass the original input identity directly around convolutional blocks: F(x) + x", "Using 1x1 convolutions only", "Replacing all activations with Sigmoid", "Removing all backpropagation"], 0,
     "Skip connections provide unobstructed identity shortcut highways for gradient backpropagation (d(F(x)+x)/dx = dF/dx + 1), conquering vanishing gradients.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What are the three gating mechanisms that regulate information flow inside a Long Short-Term Memory (LSTM) cell?",
     ["Forget Gate, Input Gate, and Output Gate", "Read Gate, Write Gate, and Execute Gate", "Alpha Gate, Beta Gate, and Gamma Gate", "Push Gate, Pop Gate, and Shift Gate"], 0,
     "LSTMs regulate cell state updates via: Forget Gate (discards old info), Input Gate (stores new info), and Output Gate (filters cell state into hidden output).", "Easy", "AI & Machine Learning", "Previous Exam"),

    # 31-40
    ("What is the core mathematical formula for Scaled Dot-Product Attention introduced in the Transformer architecture?",
     ["Attention(Q, K, V) = softmax((Q * K^T) / sqrt(d_k)) * V", "Attention(Q, K, V) = Q * K * V", "Attention = sigmoid(Q + K + V)", "Attention = max(0, Q * K^T)"], 0,
     "Vaswani et al. formulated scaled dot-product attention: querying keys (Q * K^T), scaling by sqrt(d_k), applying softmax, and weighting values V.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("Why is the dot product (Q * K^T) scaled by 1 / sqrt(d_k) in Transformer self-attention?",
     ["To prevent dot products from growing excessively large for large projection dimensions, which would push softmax into regions with extremely small gradients", "To convert matrices into scalars", "To normalize the matrix determinant to 1", "To speed up GPU floating point addition"], 0,
     "For large dimensions d_k, unscaled dot products grow large in magnitude, pushing softmax functions into saturation regions with near-zero gradients.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("Why do Transformer models require Positional Encodings?",
     ["Because self-attention operations are permutation-invariant and contain no inherent recurrence or convolution to encode token sequence order", "To compress sequence lengths", "To translate foreign languages into English", "To compute token word counts"], 0,
     "Unlike RNNs, Transformers process all tokens concurrently; sinusoidal or learned positional embeddings inject spatial sequence order into embeddings.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the difference between BERT and GPT architectural models?",
     ["BERT is an encoder-only model trained bidirectionally using Masked Language Modeling; GPT is an autoregressive decoder-only model using causal masking for next-token prediction", "BERT is for images; GPT is for audio", "GPT cannot generate text", "BERT is trained without backpropagation"], 0,
     "BERT uses bidirectional context to produce text representations; GPT uses unidirectional causal masking to generate text autoregressively.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Causal Masking in autoregressive Transformer decoders (like GPT)?",
     ["Setting attention weights for future token positions to negative infinity (-inf) before softmax, ensuring each token attends only to prior positions", "Masking personal user data in prompts", "Hiding weights during API calls", "Encrypting token embeddings"], 0,
     "Causal masking forces upper-triangular attention values to -inf, preventing tokens from looking ahead at future target tokens during generation.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In Reinforcement Learning, what is a Markov Decision Process (MDP) defined by?",
     ["A 5-tuple: (S, A, P, R, gamma) representing States, Actions, Transition Probabilities, Reward Function, and Discount Factor", "A neural network with 5 layers", "A database schema for storing logs", "A graph of game states without rewards"], 0,
     "MDPs mathematically model decision-making in environments satisfying the Markov property (the future depends solely on the current state and action).", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the Bellman Equation in Reinforcement Learning?",
     ["A recursive equation decomposing a state (or state-action) value function into the immediate expected reward plus the discounted value of successor states", "An equation calculating GPU power consumption", "A formula for training CNN filters", "A rule for sorting game scores"], 0,
     "Richard Bellman's equation decomposes value functions: V(s) = R(s) + gamma * sum(P(s'|s, a) * V(s')), forming the basis of dynamic programming and RL.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("In Q-Learning, what does the Q-value Q(s, a) represent?",
     ["The expected cumulative discounted future reward obtained by taking action 'a' in state 's' and following the optimal policy thereafter", "The probability of winning the game", "The quality of the neural network weights", "The speed of taking action a"], 0,
     "The Q-function (action-value function) evaluates the expected return of selecting action a from state s under optimal downstream execution.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("Why is Q-Learning classified as an 'Off-Policy' Reinforcement Learning algorithm?",
     ["It updates Q-values using the greedy maximum action over next states (max_a' Q(s', a')) regardless of the actual action selected by the exploration policy", "It trains while disconnected from the environment", "It does not use policy gradients", "It can only run offline on disk"], 0,
     "Q-learning is off-policy because its target update uses the maximum future Q-value (optimal policy) rather than the actual exploratory action taken (e.g., epsilon-greedy).", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the Exploration vs Exploitation dilemma in Reinforcement Learning, and how does the Epsilon-Greedy strategy address it?",
     ["Exploration discovers new actions; Exploitation leverages known high-reward actions; Epsilon-Greedy selects random actions with probability epsilon and greedy actions with 1 - epsilon", "Exploitation means hacking servers; Exploration means browsing", "Epsilon-greedy always chooses the worst action", "It reboots the agent when rewards drop"], 0,
     "Agents must balance trying novel choices versus exploiting known rewards; epsilon-greedy chooses random actions with probability epsilon to explore.", "Easy", "AI & Machine Learning", "Previous Exam"),

    # 41-50
    ("What is the MapReduce programming paradigm?",
     ["A distributed computing model that processes large datasets in parallel using a Map function (transforms data into key-value pairs) and a Reduce function (aggregates by key)", "A map for finding datacenters", "A database query language for MongoDB", "A tool for compressing map graphics"], 0,
     "MapReduce (Dean & Ghemawat) partitions large-scale data tasks into parallel Map phases, Shuffle/Sort stages, and aggregated Reduce operations.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("In Apache Spark, what is an RDD (Resilient Distributed Dataset)?",
     ["An immutable, fault-tolerant distributed collection of data elements partitioned across cluster nodes that can be operated on in parallel", "A relational database table on disk", "A machine learning model file", "A real-time display dashboard"], 0,
     "RDDs are Spark's fundamental data abstraction: immutable distributed object collections that recover automatically from node failures via lineage graphs.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("In Apache Spark, what is the difference between Transformations and Actions?",
     ["Transformations are lazily evaluated operations creating new RDDs (e.g., map, filter); Actions trigger execution and return values to the driver (e.g., count, collect)", "Transformations write to disk; Actions delete data", "Actions run on the driver; Transformations run in RAM", "There is no difference in Spark"], 0,
     "Spark computes transformations lazily, building an execution DAG; execution actually commences only when an action (e.g., collect, saveAsTextFile) is called.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the difference between an OLTP (Online Transaction Processing) system and an OLAP (Online Analytical Processing) system?",
     ["OLTP is optimized for high-volume, low-latency concurrent transactional reads/writes on normalized tables; OLAP is optimized for complex aggregation queries across massive historical data", "OLTP is for clouds; OLAP is for desktops", "OLAP only stores text files", "They use identical database architectures"], 0,
     "OLTP powers day-to-day operational transactions (e.g., banking); OLAP powers business intelligence and data warehousing with column-oriented aggregation.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("Why are Columnar Storage formats (such as Apache Parquet or Apache ORC) preferred for OLAP data warehouses over row-oriented formats (CSV, JSON)?",
     ["Queries that scan specific columns only read relevant data from disk, and storing identical data types contiguously achieves drastically higher compression ratios", "Columnar formats are human-readable in Notepad", "Columnar formats do not support numbers", "Row formats cannot be read by Python"], 0,
     "Columnar stores drastically cut I/O for analytical queries (aggregating 3 columns out of 100 skips 97% of data) and compress exceptionally well.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the difference between a Star Schema and a Snowflake Schema in data warehouse dimensional modeling?",
     ["In a Star Schema, dimension tables are denormalized; in a Snowflake Schema, dimension tables are normalized into sub-dimensions", "A Star Schema has no fact table", "A Snowflake schema stores data on ice", "Star schemas cannot use foreign keys"], 0,
     "Star schemas feature a central fact table surrounded by denormalized dimension tables; Snowflake schemas normalize dimensions into hierarchical sub-tables.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Data Lake compared to a Data Warehouse?",
     ["A Data Lake stores raw, unstructured, semi-structured, and structured data at scale using Schema-on-Read; a Data Warehouse stores curated, structured data using Schema-on-Write", "A Data Lake is stored on water cooling systems", "A Data Warehouse only holds spreadsheets", "A Data Lake cannot be queried"], 0,
     "Data Lakes (e.g., S3/HDFS) store raw files flexibly with schema applied when querying (Schema-on-Read); Warehouses require predefined relational schemas.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is a Lakehouse architecture (e.g., Delta Lake, Apache Iceberg)?",
     ["A modern architecture combining the low-cost storage flexibility of data lakes with the ACID transactions, versioning, and governance of data warehouses", "A house built near water with computers", "A server cooled with lake water", "A database for marine biology"], 0,
     "Lakehouses layer transactional metadata tables (Delta/Iceberg/Hudi) over object storage, providing ACID guarantees and time-travel querying on raw lake files.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Overfitting in machine learning, and what are common remedies?",
     ["The model learns training noise and performs poorly on unseen test data; remedied by regularization, cross-validation, data augmentation, and early stopping", "The model fits in too small memory", "The model trains in under 1 second", "The model loss remains at 100%"], 0,
     "Overfitting occurs when high-capacity models memorize idiosyncrasies of training sets; combated with regularization (L1/L2), pruning, dropout, and more data.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is K-Fold Cross-Validation?",
     ["Splitting data into K subsets, training the model K times using K-1 folds for training and the remaining 1 fold for validation, averaging performance", "Training K models simultaneously on K GPUs", "Deleting K random features from data", "Evaluating data using K nearest neighbors"], 0,
     "K-fold cross-validation evaluates model generalization robustly across all data partitions, mitigating evaluation bias from single train-test splits.", "Easy", "AI & Machine Learning", "Previous Exam"),

    # 51-60
    ("What is Gradient Descent in machine learning optimization?",
     ["An iterative first-order optimization algorithm that steps model parameters in the opposite direction of the gradient of the loss function to find a minimum", "A method for descending mountains safely", "A mathematical sorting algorithm", "An image filtering algorithm"], 0,
     "Gradient descent updates weights iteratively: w = w - lr * grad(Loss), descending the loss landscape toward local or global minima.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Stochastic Gradient Descent (SGD) compared to Batch Gradient Descent?",
     ["SGD updates model parameters using the gradient computed from a single random training sample per step; Batch GD computes gradients over the entire dataset", "SGD runs on all CPUs at once", "Batch GD updates weights every millisecond", "SGD is guaranteed to be 100x slower"], 0,
     "Batch GD calculates gradients across entire datasets (slow, memory-intensive); SGD computes updates per single sample, introducing noisy faster convergence.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Mini-Batch Gradient Descent?",
     ["A compromise that computes gradients and updates parameters over small batches of training samples (e.g., 32, 64, 128) per step", "Running gradient descent on mini computers", "Using only 10% of features", "Updating weights only once per epoch"], 0,
     "Mini-batch GD balances the vectorization efficiency and stability of batch GD with the fast convergence and escape capability of SGD.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the Learning Rate in gradient descent, and what happens if it is set too high?",
     ["A hyperparameter scaling step sizes during weight updates; if too high, training may oscillate wildly or diverge rather than converging to a minimum", "The rate at which humans learn to code", "The percentage of data loaded into RAM", "The clock frequency of the processor"], 0,
     "The learning rate dictates gradient step sizes; excessive learning rates cause gradient updates to overshoot minima and diverge towards infinity.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Early Stopping in machine learning model training?",
     ["A regularization technique that halts training when performance on a held-out validation set ceases to improve, preventing overfitting", "Stopping training when the computer runs low on battery", "Terminating code with Ctrl+C", "A pause between epochs to cool down GPUs"], 0,
     "Early stopping monitors validation loss; when validation loss trends upward despite declining training loss, training stops to preserve generalization.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Data Augmentation in deep learning (especially for computer vision)?",
     ["Artificially expanding training dataset size and diversity by applying label-preserving transformations (rotations, flips, crops, color jitter)", "Buying more data from third-party vendors", "Generating random fake labels for images", "Increasing image resolution with AI"], 0,
     "Data augmentation exposes vision models to invariant transformations, regularizing models and significantly boosting out-of-distribution robustness.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Transfer Learning in deep learning?",
     ["Reusing a model pre-trained on a massive general dataset (e.g., ImageNet, web text) as a starting point and fine-tuning it on a specialized target task", "Transferring model weights via USB drive", "Converting Python models into C++", "Translating code from TensorFlow to PyTorch"], 0,
     "Transfer learning leverages generalized representations learned by massive foundational models, requiring far less task-specific data and compute to excel.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Fine-Tuning in foundation models (LLMs and vision models)?",
     ["Continuing the training of a pre-trained model on a domain-specific dataset with a small learning rate to adapt its weights to specific tasks", "Cleaning dust off the GPU fans", "Adjusting screen resolution for viewing models", "Writing comments in model source code"], 0,
     "Fine-tuning adapts broad pre-trained capabilities to specialized domain vocabularies, instructions, or classification tasks.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is LoRA (Low-Rank Adaptation) in parameter-efficient fine-tuning (PEFT) of LLMs?",
     ["Freezing pre-trained model weights and injecting trainable low-rank decomposition matrices into transformer layers, dramatically cutting trainable parameters", "A deep learning model developed in Rome", "An audio compression algorithm for speech", "A method for compressing text prompts"], 0,
     "LoRA decomposes weight updates into rank r matrices (delta_W = B * A where r << d), reducing trainable memory and parameter footprint by over 90%.", "Hard", "AI & Machine Learning", "Previous Exam"),
    ("What is Quantization in deep learning model optimization (e.g., INT8, INT4)?",
     ["Converting high-precision floating-point weights (FP32/FP16) into lower-bit representations (INT8/INT4) to reduce memory usage and accelerate inference", "Counting the number of neurons in a network", "Encrypting model weights with quantum keys", "Deleting unused layers from a model"], 0,
     "Quantization shrinks model footprint 2x to 4x and leverages efficient integer tensor cores, enabling large LLMs to run on edge devices.", "Medium", "AI & Machine Learning", "Previous Exam"),

    # 61-70
    ("What is Retrieval-Augmented Generation (RAG)?",
     ["A framework that retrieves relevant factual documents from an external knowledge base (via vector search) and passes them into an LLM's prompt context", "Generating images using neural networks", "A model that writes computer code", "A tool for compressing PDF documents"], 0,
     "RAG grounds LLM outputs in verified external knowledge stores, eliminating hallucinations and enabling dynamic knowledge access without retraining.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is a Vector Database (e.g., Pinecone, Milvus, Chroma, Weaviate)?",
     ["A specialized database designed to store, index, and rapidly search high-dimensional vector embeddings using Approximate Nearest Neighbor (ANN) algorithms", "A database for 3D vector graphics files", "A database that only stores numbers", "A relational database with vector columns"], 0,
     "Vector databases execute sub-second cosine or Euclidean similarity searches across millions of high-dimensional embeddings using algorithms like HNSW.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is HNSW (Hierarchical Navigable Small World) in vector search indexing?",
     ["A multi-layer graph-based algorithm for approximate nearest neighbor search that provides logarithmic search time complexity", "A high-speed networking cable protocol", "A neural network architecture for images", "A web crawling framework"], 0,
     "HNSW constructs multi-layered proximity graphs for embeddings, balancing rapid traversal across sparse top layers with precise local search on base layers.", "Hard", "AI & Machine Learning", "Previous Exam"),
    ("What is Cosine Similarity between two non-zero vectors A and B?",
     ["The dot product of A and B divided by the product of their Euclidean lengths (magnitudes): (A . B) / (||A|| * ||B||)", "The angle between vectors measured in degrees", "The Euclidean distance between vector tips", "The sum of elements in both vectors"], 0,
     "Cosine similarity measures the cosine of the angle between two vectors, capturing directional orientation irrespective of vector scale (range [-1, 1]).", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is an Embedding in machine learning?",
     ["A continuous, dense vector representation of discrete objects (e.g., words, images, users) where semantically similar items map close together in vector space", "An HTML <iframe> tag embedding a video", "A microscopic computer chip", "An encrypted message hidden in an image"], 0,
     "Embeddings translate high-dimensional discrete tokens into low-dimensional dense continuous vectors capturing semantic and syntactic relationships.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Perplexity in language model evaluation?",
     ["An evaluation metric measuring how well a probability model predicts a sample; defined as the exponentiated average negative log-likelihood per token (lower is better)", "How confused the user is by the model", "The number of grammatical errors per page", "The response time of the language model in seconds"], 0,
     "Perplexity quantifies uncertainty: lower perplexity signifies the model is less 'surprised' by the test sequence, assigning higher probabilities to actual tokens.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Temperature in LLM decoding and text generation?",
     ["A hyperparameter that scales logits before softmax: lower values (<1.0) make responses more deterministic/focused; higher values (>1.0) increase randomness/creativity", "The physical operating temperature of the server GPU", "The ambient temperature of the server room", "The speed of the processor cooling fan"], 0,
     "Dividing logits by temperature T flattens the probability distribution for T > 1 (boosting variety) or sharpens peak probabilities for T -> 0 (deterministic).", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Top-p (Nucleus) Sampling in LLM token generation?",
     ["Sampling tokens exclusively from the smallest subset of candidate tokens whose cumulative probability exceeds the threshold p", "Selecting the top p highest-scoring prompts", "Generating exactly p tokens per second", "Sampling tokens with p letters or fewer"], 0,
     "Nucleus sampling dynamically truncates the long tail of low-probability tokens, restricting candidate selection to the credible probability mass threshold p.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Top-k Sampling in language models?",
     ["Restricting candidate token selection strictly to the 'k' most probable next tokens, discarding all others before sampling", "Running the model on k GPUs in parallel", "Generating k responses simultaneously", "Selecting prompts from the top k users"], 0,
     "Top-k filtering sets a hard upper bound on candidate vocabulary size k, preventing the model from ever picking bizarre low-probability tokens.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Reinforcement Learning from Human Feedback (RLHF)?",
     ["A technique that aligns LLM outputs with human intent by training a reward model on human preference comparisons and optimizing the LLM using PPO", "Asking users to write code for the model", "Employees manually editing training texts", "A human rating every single API query in real time"], 0,
     "RLHF aligns foundation models for helpfulness and safety using human preference ranking data to train reward models that guide policy optimization.", "Medium", "AI & Machine Learning", "Previous Exam"),

    # 71-80
    ("What is the Softmax function, and why is it used in multi-class classification output layers?",
     ["It exponentiates raw logits and normalizes them into a probability distribution where values range between 0 and 1 and sum exactly to 1", "It rounds numbers to the nearest integer", "It calculates the average of inputs", "It filters out negative numbers without scaling"], 0,
     "Softmax maps an unconstrained vector of real values to a valid categorical probability distribution over multiple mutually exclusive classes.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Cross-Entropy Loss (Log Loss) primarily used for?",
     ["Measuring the performance of a classification model whose output is a probability value between 0 and 1, heavily penalizing confident wrong predictions", "Calculating the distance between two points", "Measuring the file size of compressed images", "Computing CPU memory leaks"], 0,
     "Cross-entropy loss quantifies divergence between predicted class probabilities and actual one-hot labels, penalizing confident misclassifications severely.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Mean Squared Error (MSE) loss used for?",
     ["Measuring the average squared difference between estimated values and actual values in regression tasks", "Evaluating text classifications", "Measuring the accuracy of decision trees", "Calculating network latency"], 0,
     "MSE is the standard loss metric for continuous regression problems: (1/n) * sum((y_true - y_pred)^2).", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the difference between Supervised Learning and Unsupervised Learning?",
     ["Supervised learning algorithms train on labeled datasets with target outputs; Unsupervised learning algorithms discover patterns from unlabeled data without targets", "Supervised learning requires human supervision during execution", "Unsupervised learning cannot run on computers", "They are identical in machine learning"], 0,
     "Supervised learning maps inputs x to known targets y; unsupervised learning uncovers inherent groupings, structures, or distributions in unlabelled data.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Semi-Supervised Learning?",
     ["A machine learning approach combining a small amount of labeled data with a large amount of unlabeled data during training", "Training a model halfway and stopping", "A model supervised by two engineers", "Training only on weekends"], 0,
     "Semi-supervised learning leverages cheap, plentiful unlabeled data alongside scarce human-labeled samples to boost classification boundaries.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Active Learning in machine learning workflows?",
     ["An iterative learning framework where the algorithm selectively queries an expert (human annotator) to label the specific data points it is most uncertain about", "Running models while exercising", "A model that learns continuously without sleeping", "A neural network that writes its own code"], 0,
     "Active learning maximizes annotation efficiency by having the model request human labels only for samples situated nearest its decision boundary.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is the Curse of Dimensionality in machine learning?",
     ["As the number of feature dimensions increases, the volume of the feature space grows exponentially, making available data sparse and distances equidistant", "A magical spell in computer games", "A virus that corrupts multi-dimensional arrays", "A bug in 3D rendering engines"], 0,
     "In high dimensions, data becomes exponentially sparse and Euclidean distance metrics lose discriminatory power, degrading model performance.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is One-Hot Encoding in feature preprocessing?",
     ["Representing categorical variables as binary vectors where exactly one element is 1 (hot) and all other elements are 0", "Heating the processor during data loading", "Encoding data into warm color hex codes", "Converting strings to uppercase"], 0,
     "One-hot encoding converts categorical variables into distinct orthogonal binary columns without inadvertently implying arbitrary ordinal mathematical hierarchy.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is the difference between Normalization (Min-Max Scaling) and Standardization (Z-Score Scaling)?",
     ["Normalization rescales features into a fixed range [0, 1]; Standardization rescales features to have zero mean (mean=0) and unit variance (std=1)", "Normalization squares all numbers", "Standardization is only for integers", "They are identical formulas"], 0,
     "Min-Max scaling bounds values to [0, 1]; Z-score scaling (x - mu)/sigma centers data around zero with unit standard deviation, preserving outliers.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Data Leakage (Target Leakage) in machine learning modeling?",
     ["When information from the target variable or test set inadvertently contaminates the training process, leading to unrealistically optimistic training scores", "Data leaking through network firewalls", "A memory leak in Python pandas", "A hard drive spilling data physically"], 0,
     "Data leakage occurs when features contain future information or test statistics (e.g., fitting scalers on the full dataset before splitting), invalidating evaluations.", "Medium", "AI & Machine Learning", "Previous Exam"),

    # 81-90
    ("What is an Autoencoder neural network?",
     ["An unsupervised neural network trained to reconstruct its own input at the output layer, passing data through an informational bottleneck (latent space)", "A tool that writes code automatically", "A network that repairs broken cars", "A compiler for neural network weights"], 0,
     "Autoencoders compress inputs into low-dimensional latent bottleneck representations (encoder) and reconstruct the original input (decoder).", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is a Generative Adversarial Network (GAN)?",
     ["A framework comprising two competing neural networks: a Generator that creates synthetic data and a Discriminator that distinguishes synthetic from real data", "Two computers playing chess against each other", "A network that blocks adversarial attacks", "A firewall that filters network packets"], 0,
     "Ian Goodfellow's GAN pits a generator against a discriminator in a minimax game, driving generation fidelity until synthetic samples mimic reality.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is a Diffusion Model in generative AI (e.g., Stable Diffusion)?",
     ["A generative model that learns to generate data by gradually adding noise to training samples (forward process) and learning to iteratively denoise it (reverse process)", "A model that diffuses light in 3D scenes", "A model that spreads viruses over networks", "A model that dissolves memory leaks"], 0,
     "Diffusion models master reverse-time thermodynamics, iteratively subtracting predicted Gaussian noise from latent representations to synthesize photorealistic outputs.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Multimodal AI?",
     ["An artificial intelligence system capable of processing, understanding, and synthesizing multiple distinct types of data modalities simultaneously (e.g., text, vision, audio)", "An AI with multiple user accounts", "A model that runs on multiple operating systems", "A model that uses multiple monitors"], 0,
     "Multimodal models project heterogeneous modalities (text tokens, image patches, audio spectrograms) into unified shared embedding spaces.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Zero-Shot Learning in AI models?",
     ["The ability of a pre-trained model to accurately classify or solve tasks without having seen any explicit training examples of that specific task", "Training a model with zero lines of code", "A model that requires zero seconds to train", "A model that has zero parameters"], 0,
     "Zero-shot learning relies on broad generalized semantic understanding (e.g., CLIP matching image vectors against text prompts) without task-specific retraining.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Few-Shot Prompting (In-Context Learning) in Large Language Models?",
     ["Providing a few input-output demonstration examples directly within the prompt context window to guide the LLM's response pattern without updating model weights", "Training a model on only a few images", "A model with few parameters", "Prompting an AI in a few seconds"], 0,
     "In-context learning guides generation by showing 2-5 explicit exemplar pairs in the prompt, steering model completion via attention without gradient updates.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Chain-of-Thought (CoT) Prompting?",
     ["Prompting an LLM to explicitly articulate intermediate reasoning steps before arriving at a final answer, substantially improving multi-step reasoning", "Connecting multiple LLMs in a daisy chain", "A blockchain network running AI models", "A sequence of prompts sent every minute"], 0,
     "CoT prompting prompts the model ('think step-by-step'), generating explicit rationales that prevent cascading logical errors on complex deductive tasks.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Hallucination in Large Language Models?",
     ["When an LLM generates statements that appear coherent and plausible but are factually incorrect, ungrounded, or fabricated", "An AI seeing visual ghosts on screen", "A crash of the model server", "An error during model download"], 0,
     "Hallucinations occur because autoregressive LLMs generate statistically plausible token sequences rather than consulting verifiable truth databases.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is catastrophic forgetting in neural network training?",
     ["The tendency of a neural network to completely and abruptly forget previously learned knowledge upon being trained on new, subsequent data tasks", "A hard drive failure deleting weights", "A human developer forgetting how code works", "A loss of power in the datacenter"], 0,
     "When fine-tuning weights on new tasks without preservation constraints, weight adjustments overwrite features learned from historical datasets.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Model Pruning in neural network compression?",
     ["Removing redundant or near-zero weights, connections, or entire channels from a trained neural network with minimal loss in accuracy", "Pruning trees in computer game environments", "Deleting comments from Python code", "Removing old users from a database"], 0,
     "Pruning removes unneeded weights (creating sparse tensors), cutting model memory footprints and accelerating execution on specialized hardware.", "Medium", "AI & Machine Learning", "Previous Exam"),

    # 91-100
    ("What is Knowledge Distillation in deep learning (Teacher-Student framework)?",
     ["Transferring knowledge from a large, complex pre-trained model (Teacher) into a compact, efficient model (Student) by training the student on teacher output probabilities", "Reading textbooks to write code", "Extracting knowledge from Wikipedia", "A chemical process for cleaning server chips"], 0,
     "Geoffrey Hinton's distillation trains lightweight student models to match the soft probability distributions ('dark knowledge') emitted by large teacher ensembles.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is a Transformer's Context Window?",
     ["The maximum number of tokens (input plus generated output) that a Transformer model can process simultaneously in its attention mechanism at one time", "A popup window displaying AI output", "The operating system desktop window", "The time window taken to train an LLM"], 0,
     "The context window bounds the span of text over which self-attention matrices can attend concurrently during a single inference call.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is FlashAttention?",
     ["An exact, I/O-aware self-attention algorithm that computes softmax tiling in fast SRAM to drastically accelerate attention and reduce HBM memory overhead", "A photographic flash for AI cameras", "An old Adobe Flash animation plugin", "A tool for compressing images"], 0,
     "Tri Dao's FlashAttention tiles attention computation into GPU high-speed SRAM, minimizing expensive reads/writes to high-bandwidth memory (HBM).", "Hard", "AI & Machine Learning", "Previous Exam"),
    ("What is Mixture of Experts (MoE) in large language model architecture (e.g., Mixtral)?",
     ["An architecture that replaces dense feedforward layers with multiple specialized expert networks, using a routing gate to activate only a subset of experts per token", "A panel of human software experts reviewing code", "Combining three completely different LLM models into one", "A multi-agent committee system"], 0,
     "MoE achieves massive parameter capacity while keeping per-token compute low by dynamically routing tokens to only top-k (e.g., 2 of 8) expert sub-networks.", "Hard", "AI & Machine Learning", "Previous Exam"),
    ("What is Synthetic Data in machine learning?",
     ["Data generated programmatically or via generative AI models rather than collected from direct real-world measurements or observations", "Fake accounts on social media", "Corrupted data files on disk", "Data stored in encrypted form"], 0,
     "Synthetic data augments sparse real-world datasets, trains models when real data is restricted by privacy regulations, and provides controlled edge cases.", "Easy", "AI & Machine Learning", "Previous Exam"),
    ("What is Concept Drift in machine learning monitoring?",
     ["The statistical property of the target variable changing over time in unforeseen ways, causing a deployed model's accuracy to degrade", "A computer sliding across a desk", "A gradual change in software requirements", "A developer forgetting initial design goals"], 0,
     "Concept drift occurs when real-world relationships evolve (e.g., consumer habits changing post-pandemic), rendering historically trained models inaccurate.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Data Drift in MLOps?",
     ["A shift in the distribution of the input feature data over time, even if the underlying conditional probability distribution P(Y|X) remains constant", "Data moving between cloud regions", "A slow network connection transferring files", "A database migration script"], 0,
     "Data drift flags that production inputs diverge from training distributions, alerting MLOps pipelines to trigger model retraining.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Federated Learning?",
     ["A decentralized machine learning approach where multiple edge devices collaboratively train a model locally and share only weight updates with a central server", "Learning government laws in computer science", "A university course in artificial intelligence", "Training models across 50 internet browsers"], 0,
     "Federated learning preserves data privacy: training data never leaves user mobile devices; only encrypted gradient updates are aggregated centrally.", "Medium", "AI & Machine Learning", "Previous Exam"),
    ("What is Differential Privacy in data science and AI?",
     ["A rigorous mathematical framework quantifying that an algorithm's output does not reveal whether any individual subject's data was included in the dataset", "A copyright law for software algorithms", "A private VPN network", "An access control list for database rows"], 0,
     "Differential privacy injects calibrated noise (Laplace/Gaussian), mathematically guaranteeing an adversary cannot reconstruct individual records from aggregate queries.", "Hard", "AI & Machine Learning", "Previous Exam"),
    ("What is Prompt Injection in Large Language Model security?",
     ["A vulnerability where untrusted user input alters the intended instructions or safety guardrails of an LLM prompt, hijacking the model's behavior", "Injecting SQL into a prompt", "A syntax error in a system prompt", "A fast way to type prompts"], 0,
     "Prompt injection manipulates the LLM's natural language instruction parser into ignoring developer constraints and following attacker commands.", "Easy", "AI & Machine Learning", "Previous Exam")
]

print(f"Total Part 10 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part10_data = []
for i, q in enumerate(questions):
    qid = f"p10-q{i+1}"
    part10_data.append({
        "id": qid,
        "part": 10,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part10.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_10_QUESTIONS: Question[] = ")
    json.dump(part10_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 10 successfully to src/data/parts/part10.ts")
