#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("What does the CAP Theorem (Brewer's Theorem) state about distributed data stores?",
     ["It is impossible for a distributed data store to simultaneously provide more than two out of three guarantees: Consistency, Availability, and Partition Tolerance", "Computers must be rebooted every 3 days", "Cloud networks must always prioritize Performance over Cost", "Distributed transactions require 3 independent clouds"], 0,
     "Eric Brewer's CAP theorem proves that in the presence of a network partition (P), a distributed system must choose between Consistency (C) or Availability (A).", "Easy", "Distributed Systems", "Previous Exam"),
    ("What does the PACELC theorem add to the traditional CAP theorem?",
     ["If there is a Partition (P), how does the system trade Availability (A) vs Consistency (C); Else (E), how does it trade Latency (L) vs Consistency (C)?", "It incorporates Cost and Energy efficiency metrics", "It guarantees 100% fault tolerance in private networks", "It measures packet loss in fiber optics"], 0,
     "Daniel Abadi's PACELC theorem notes that even in normal non-partitioned states, distributed stores must trade off between latency (L) and consistency (C).", "Medium", "Distributed Systems", "Previous Exam"),
    ("In the Raft distributed consensus algorithm, what are the three possible states a server node can be in?",
     ["Leader, Follower, and Candidate", "Master, Worker, and Scribe", "Proposer, Acceptor, and Learner", "Active, Idle, and Disconnected"], 0,
     "Raft breaks consensus into explicit roles: a single elected Leader, Candidates competing during elections, and passive Followers responding to RPCs.", "Easy", "Distributed Systems", "Previous Exam"),
    ("How does the Raft consensus algorithm handle a split-vote during leader election?",
     ["Nodes employ randomized election timeouts to ensure that split-vote ties are broken quickly in the subsequent term", "The node with the lowest IP address is declared leader", "The cluster administrator manually picks a leader", "All nodes crash and restart"], 0,
     "Randomized election timeouts stagger candidate declarations, ensuring one node initiates election and collects a quorum before others time out.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Consistent Hashing and why is it used in distributed caching systems (like Dynamo or Memcached)?",
     ["A hashing technique where nodes and keys are mapped to a circular hash ring, minimizing key remapping to K/N keys when nodes are added or removed", "A hash function that never produces collisions", "Encrypting database keys with AES", "A sorting algorithm for hash tables"], 0,
     "Consistent hashing organizes servers along a 360-degree ring; adding or removing a node only impacts adjacent keys rather than rehashing the entire keyspace.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What problem do 'Virtual Nodes' (vnodes) solve in a Consistent Hashing ring?",
     ["They ensure a more balanced and uniform distribution of keys across physical machines to prevent hot spots and load imbalance", "They emulate virtual machines on cloud servers", "They duplicate RAM for faster lookups", "They prevent network cable disconnections"], 0,
     "Virtual nodes assign each physical server multiple points across the ring, preventing clustering and ensuring uniform load distribution.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the primary vulnerability of the classic Two-Phase Commit (2PC) protocol?",
     ["It is a blocking protocol: if the coordinator crashes after nodes vote 'Yes' in the prepare phase, participating nodes are left blocked holding locks indefinitely", "It does not work on relational databases", "It sends passwords in plaintext", "It requires fiber optic cables"], 0,
     "2PC blocks participants if the coordinator fails during the decision phase, holding database locks until coordinator recovery.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the SAGA pattern in microservice distributed transactions?",
     ["A sequence of local transactions across services where each transaction updates its own database and triggers the next step, with compensating transactions to rollback on failure", "A hardware raid configuration", "A database backup schedule", "A programming language for clouds"], 0,
     "SAGAs replace distributed two-phase commit locks with asynchronous event-driven steps, rolling back state via explicitly coded compensating transactions.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the difference between SAGA Choreography and SAGA Orchestration?",
     ["In Choreography, services react autonomously to domain events emitted by peers; in Orchestration, a centralized orchestrator tells participating services which local transactions to execute", "Choreography is for frontends; Orchestration is for databases", "Orchestration cannot handle rollbacks", "There is no functional difference"], 0,
     "Choreography is decentralized and event-driven; Orchestration uses a centralized coordinator state machine to manage workflow transitions.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What are Vector Clocks used for in distributed systems?",
     ["Determining the partial causal ordering of events and detecting concurrent conflicting updates in a distributed system", "Measuring CPU clock speeds across computers", "Synchronizing system time with GPS satellites", "Calculating 3D vector graphics"], 0,
     "Vector clocks maintain an array of logical clocks per node, enabling systems (e.g., Dynamo) to identify whether two events are causally related or concurrent.", "Medium", "Distributed Systems", "Previous Exam"),

    # 11-20
    ("What is Linearizability (Strong Consistency) in distributed systems?",
     ["Every read operation must return the value of the most recent write, appearing as if there were only a single global copy of the data updated instantaneously", "Data is consistent only on weekends", "Reads and writes take exactly 1 millisecond", "Data is stored on linear magnetic tape"], 0,
     "Linearizability guarantees that operations take effect atomically at a discrete linearization point between their invocation and response.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is Eventual Consistency?",
     ["A weak consistency model guaranteeing that if no new updates are made, all replicas will eventually converge and return the identical latest value", "Data is never consistent", "Data becomes consistent only when the server reboots", "A guarantee that writes are rejected if not instantaneous"], 0,
     "Eventual consistency allows transient read staleness across replicas in exchange for high availability, converging asynchronously.", "Easy", "Distributed Systems", "Previous Exam"),
    ("In the Byzantine Generals Problem, what proportion of faulty or traitorous nodes can an asynchronous system tolerate under Byzantine Fault Tolerance (BFT)?",
     ["Up to f faulty nodes out of a total of at least 3f + 1 nodes (less than one-third)", "Up to 50% faulty nodes", "Up to f faulty nodes out of 2f + 1 nodes", "Zero faulty nodes"], 0,
     "Lamport, Shostak, and Pease proved that reaching consensus against arbitrary Byzantine (malicious) failures requires at least 3f + 1 total nodes.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is the Circuit Breaker pattern in microservice architecture?",
     ["A design pattern that monitors remote service calls and trips open to fail fast when error thresholds are exceeded, preventing cascading outages across the system", "A physical electrical switch in a datacenter", "A firewall that cuts internet access", "A software tool that resets passwords"], 0,
     "Circuit breakers cycle through Closed (normal), Open (fail immediately without calling downstream), and Half-Open (test probe) states.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What are the three states of a Circuit Breaker in software design?",
     ["Closed (normal operation), Open (requests fail immediately), and Half-Open (trial requests allowed through to test recovery)", "On, Off, and Standby", "Green, Yellow, and Red", "Connected, Listening, and Closed"], 0,
     "When Closed, calls proceed normally; repeated failures trip the breaker to Open; after a timeout, it enters Half-Open to test downstream health.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the Bulkhead pattern in distributed system design?",
     ["Isolating system resources (e.g., thread pools, memory, connections) into distinct compartments so that the failure of one component does not exhaust resources and sink the entire application", "Building waterproof walls around server rooms", "A data compression algorithm", "Using metal chassis for computers"], 0,
     "Named after ship compartments: isolating resource pools prevents one misbehaving client or endpoint from consuming all server worker threads.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is an API Gateway in microservices architecture?",
     ["A single entry point for client requests that handles routing, protocol translation, authentication, rate limiting, and request aggregation across backend microservices", "A physical network router installed on an office desk", "A software library for drawing web buttons", "A database server that runs queries"], 0,
     "API Gateways decouple external clients from internal service topographies, centralizing cross-cutting concerns like JWT auth and throttling.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Service Discovery in microservices environments?",
     ["A mechanism that allows services to dynamically find and locate the network IP addresses and ports of other microservice instances (e.g., via Consul, Eureka, or Kubernetes DNS)", "Searching for APIs on Google", "Installing new microservices on Linux", "Monitoring server CPU temperatures"], 0,
     "Because cloud microservice containers scale dynamically with ephemeral IP addresses, service registries track live host addresses in real time.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is the difference between Horizontal Scaling (Scaling Out) and Vertical Scaling (Scaling Up)?",
     ["Horizontal scaling adds more machine nodes to the cluster pool; Vertical scaling adds more computing resources (RAM, CPU cores) to a single existing server", "Horizontal scaling is cheaper for single laptops", "Vertical scaling involves stacking servers vertically", "Horizontal scaling replaces software with hardware"], 0,
     "Scaling out adds more nodes linearly (cloud native); scaling up upgrades a single machine's hardware specs (subject to physical hardware ceilings).", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is the difference between IaaS, PaaS, and SaaS cloud computing models?",
     ["IaaS provides raw infrastructure (VMs, storage); PaaS provides a managed application platform/runtime; SaaS provides fully managed software applications directly to users", "SaaS is for hardware; IaaS is for websites", "PaaS provides only physical cabling", "There is no difference in cloud models"], 0,
     "Cloud shared responsibility tiers: IaaS (AWS EC2), PaaS (Google App Engine, Heroku), and SaaS (Google Workspace, Salesforce).", "Easy", "Distributed Systems", "Previous Exam"),

    # 21-30
    ("What is a 'Cold Start' in Serverless / Function-as-a-Service (FaaS) platforms (e.g., AWS Lambda, Cloud Functions)?",
     ["The initial latency delay incurred when a function is invoked after inactivity, requiring the cloud provider to provision a new container runtime environment", "Booting a server in a cold datacenter room", "Rebooting a server with liquid nitrogen", "A server crashing due to low temperatures"], 0,
     "Cold starts happen when spinning up fresh container sandboxes for idle functions, adding execution delay compared to warm instances.", "Medium", "Distributed Systems", "Previous Exam"),
    ("How does Docker achieve container isolation without running a full guest operating system hypervisor?",
     ["By leveraging Linux kernel namespaces (for process, network, and mount isolation) and cgroups (for CPU and memory resource limits)", "By emulating hardware CPU instructions in software", "By running virtual machines inside RAM", "By encrypting application source code"], 0,
     "Containers share the host Linux kernel, using namespaces for process boundary isolation and cgroups (control groups) for resource throttling.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is an image layer in Docker and how does the Union File System (UnionFS) utilize it?",
     ["Each Dockerfile command creates a read-only immutable layer; running containers add a single thin writable layer on top using Copy-on-Write (CoW)", "Each layer is a separate virtual hard drive", "Layers are compressed zip files that must be unpacked on boot", "Layers represent CPU clock states"], 0,
     "Docker stacks immutable read-only image layers via UnionFS; containers share underlying layers and write changes to a top ephemeral writable layer.", "Medium", "Distributed Systems", "Previous Exam"),
    ("In Kubernetes architecture, what is a Pod?",
     ["The smallest deployable unit of computing in Kubernetes, consisting of one or more co-located containers sharing storage, network IP, and localhost namespaces", "A physical datacenter rack", "A virtual machine running Linux", "A cluster backup file"], 0,
     "Pods encapsulate tightly coupled container groups (e.g., an app container and a sidecar proxy) sharing network namespaces and storage volumes.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is the role of 'etcd' in a Kubernetes control plane?",
     ["A consistent and highly available distributed key-value store used as Kubernetes' backing store for all cluster state data and configuration", "An antivirus scanner for pods", "A load balancer for user traffic", "A container runtime engine"], 0,
     "etcd utilizes the Raft consensus algorithm to persist cluster states, node manifests, secrets, and deployment specifications reliably.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the difference between a Kubernetes ClusterIP Service and a NodePort Service?",
     ["ClusterIP exposes the service internally within the cluster network only; NodePort exposes the service on each node's static port accessible externally", "ClusterIP is for databases only", "NodePort is internal only", "They are identical in Kubernetes"], 0,
     "ClusterIP (default) is internal to the cluster; NodePort opens a dedicated port (30000-32767) on all cluster nodes for external routing.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is a Kubernetes Ingress?",
     ["An API object that manages external access to services within a cluster, typically HTTP/HTTPS routing, SSL termination, and name-based virtual hosting", "An egress firewall rule", "A tool for deleting pods", "A network cable connection"], 0,
     "Ingress acts as a smart reverse proxy (e.g., NGINX Ingress Controller) routing external internet domain traffic to appropriate internal Services.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the primary architectural model of Apache Kafka compared to traditional message queues like RabbitMQ?",
     ["Kafka is a distributed, partitioned, replicated append-only commit log where consumers manage their own read offsets; RabbitMQ delivers messages to queues and deletes them upon ack", "Kafka deletes messages immediately upon delivery", "RabbitMQ stores messages on disk forever", "Kafka does not support multiple consumers"], 0,
     "Kafka persists events as immutable append-only distributed partition logs, allowing consumers to stream and replay messages by updating offset pointers.", "Medium", "Distributed Systems", "Previous Exam"),
    ("In Apache Kafka, what is a Consumer Group?",
     ["A set of consumers that cooperate to consume data from a topic, where each partition is assigned to exactly one consumer within the group", "A group of servers hosting topics", "A list of users subscribed to a newsletter", "A backup cluster"], 0,
     "Consumer groups allow parallel stream processing by dividing topic partitions evenly among group members for scalable horizontal throughput.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Head-of-Line (HoL) Blocking in HTTP/1.1 pipelining?",
     ["A condition where a slow or stalled response to an earlier HTTP request blocks all subsequent queued responses on the same single TCP connection", "A line of people waiting for a server", "A collision on a Wi-Fi router", "A full cache memory block"], 0,
     "HTTP/1.1 pipelining required server responses to arrive strictly in the order requested; a slow first request blocked all subsequent responses on that socket.", "Medium", "Distributed Systems", "Previous Exam"),

    # 31-40
    ("How does HTTP/2 solve the application-layer Head-of-Line blocking problem present in HTTP/1.1?",
     ["By introducing binary framing and request multiplexing, allowing multiple independent streams of interleaved request/response frames over a single TCP connection", "By opening 100 parallel TCP connections", "By compressing images with gzip", "By removing headers completely"], 0,
     "HTTP/2 multiplexes interleaved binary data frames tagged with Stream IDs over one TCP connection, eliminating application-layer queuing stalls.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What protocol does HTTP/3 use as its underlying transport layer instead of TCP, and why?",
     ["QUIC over UDP; to eliminate transport-layer TCP Head-of-Line blocking and provide faster 0-RTT handshakes and connection migration", "SCTP over IP", "Raw ICMP packets", "Bluetooth Low Energy"], 0,
     "HTTP/3 utilizes QUIC running on UDP, ensuring packet loss on one stream does not stall independent concurrent streams (solving TCP HoL blocking).", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Connection Migration in HTTP/3 (QUIC)?",
     ["The ability to maintain an active connection seamlessly when a client switches network interfaces (e.g., Wi-Fi to cellular) using a 64-bit Connection ID instead of IP/port 4-tuple", "Migrating web servers to a new cloud", "Moving databases between datacenters", "Switching between browser tabs"], 0,
     "QUIC identifies connections via unique Connection IDs rather than source IP/port combinations, surviving mobile network network handoffs without reconnecting.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is the primary difference between WebSockets and Server-Sent Events (SSE)?",
     ["WebSockets provide full-duplex bidirectional communication over a persistent TCP connection; SSE provides unidirectional streaming (server-to-client only) over standard HTTP", "SSE is bidirectional; WebSockets are unidirectional", "WebSockets only work on mobile devices", "SSE requires custom browser plugins"], 0,
     "WebSockets enable simultaneous two-way messaging for interactive gaming/chat; SSE streams unidirectional server push over standard HTTP connections.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is the N+1 Query Problem in database and GraphQL APIs?",
     ["Executing 1 query to fetch a parent list of N items followed by N individual subsequent queries to fetch child details for each item, severely degrading performance", "Querying a table with N+1 columns", "A database query that takes N+1 seconds", "A syntax error in SQL"], 0,
     "N+1 queries inundate databases with sequential round-trips; resolved using SQL joins or batching mechanisms (such as Facebook DataLoader).", "Medium", "Distributed Systems", "Previous Exam"),
    ("How does the DataLoader pattern resolve the N+1 problem in GraphQL servers?",
     ["By batching individual load requests made within a single execution tick and caching them, fetching all requested IDs in a single batch query (WHERE id IN (...))", "By disabling GraphQL schemas", "By pre-calculating all possible queries", "By caching HTML files on CDNs"], 0,
     "DataLoader coalesces individual fetch calls within an event-loop tick into a single bulk lookup, slashing database round-trips.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the purpose of the HTTP 'Cache-Control: no-cache' directive?",
     ["The browser or proxy may store the cached response, but MUST revalidate it with the origin server (using ETag/If-None-Match) before serving it to clients", "The browser is forbidden from storing any copy of the response on disk", "The page is deleted from the web", "The server disables all caches worldwide"], 0,
     "Contrary to intuitive naming, 'no-cache' allows local caching but forces the browser to send a conditional HTTP validation request before each reuse.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the purpose of the HTTP 'Cache-Control: no-store' directive?",
     ["Caches (browsers and intermediate proxies) are strictly prohibited from storing any version of the request or response in any non-volatile or persistent storage", "The response cannot be opened in online stores", "The response can be stored for 10 days", "The server must reboot after responding"], 0,
     "'no-store' mandates that sensitive content (e.g., banking portals) must never be written to browser disk or intermediate proxy caches.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is an ETag (Entity Tag) in HTTP headers?",
     ["An opaque string identifier (e.g., hash or version) assigned by a web server to a specific version of a resource, used for conditional revalidation (If-None-Match)", "A tag used for website SEO", "A barcode on server hardware", "An HTML metadata element"], 0,
     "ETags act as resource fingerprints: clients send If-None-Match with the ETag; if unmodified, servers reply with lightweight '304 Not Modified'.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is a Content Delivery Network (CDN) and how does it reduce latency for global web users?",
     ["A geographically distributed network of proxy servers (Edge Points of Presence - PoPs) that cache static and dynamic content close to end users", "A cable television broadcasting network", "A high-speed hard drive in the user PC", "A satellite internet provider"], 0,
     "CDNs terminate TLS connections and serve cached media from nearby local edge nodes, slashing round-trip transmission latency.", "Easy", "Distributed Systems", "Previous Exam"),

    # 41-50
    ("What is HATEOAS (Hypermedia As The Engine Of Application State) in RESTful architecture?",
     ["A REST architectural constraint where a client interacts with a network application entirely through hypermedia links dynamically provided within server responses", "A hate crime monitoring protocol", "An API documentation generator", "A database indexing method"], 0,
     "HATEOAS allows clients to navigate application workflows dynamically by following hypermedia URIs returned inside JSON/XML responses.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Idempotence in HTTP methods?",
     ["An operation is idempotent if executing it multiple times produces the exact same side-effect on the server as executing it once (e.g., GET, PUT, DELETE)", "An operation that runs in zero time", "An operation that can only be executed by root", "An operation that cannot be cached"], 0,
     "PUT and DELETE are idempotent (repeated calls leave state identical); POST is non-idempotent (repeated calls create multiple distinct resources).", "Easy", "Distributed Systems", "Previous Exam"),
    ("Why is HTTP POST considered non-idempotent whereas PUT is idempotent?",
     ["Submitting multiple identical POST requests creates multiple distinct child resources; submitting multiple identical PUT requests updates the exact same targeted resource repeatedly", "POST cannot carry body data", "PUT is deprecated in HTTP/2", "There is no difference between them"], 0,
     "POST appends new subordinate entries (e.g., orders); PUT replaces the target entity at a specific URI, making repeated executions safe.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Webhook in modern web application architecture?",
     ["A user-defined HTTP POST callback mechanism allowing one application to provide real-time notifications to another when a specific event occurs", "A physical hook for holding cables", "A tool for phishing passwords", "A browser extension for surfing"], 0,
     "Webhooks invert request polling: rather than clients polling servers repeatedly, the provider pushes event payloads via HTTP POST instantly.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Cross-Origin Resource Sharing (CORS)?",
     ["A browser security mechanism using HTTP headers to permit or restrict resources on a web page from being requested by a domain outside the origin domain", "A protocol for sharing hard drives over LAN", "A cross-platform programming language", "A tool for merging Git repositories"], 0,
     "Enforced by browsers to relax the strict Same-Origin Policy, CORS uses headers like Access-Control-Allow-Origin to govern cross-domain AJAX.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is a CORS Preflight Request?",
     ["An HTTP OPTIONS request sent by the browser prior to the actual request to verify that the target server permits the method and custom headers", "A flight simulator on the web", "A preliminary DNS lookup", "A request to preheat server caches"], 0,
     "Browsers send preflight OPTIONS requests for 'non-simple' requests (e.g., methods like DELETE/PUT or custom Authorization headers) to verify permissions.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is gRPC and what serialization format does it use by default?",
     ["A high-performance open-source RPC framework developed by Google that uses Protocol Buffers (Protobuf) as its Interface Definition Language and binary format over HTTP/2", "A JSON API framework over HTTP/1", "A database query language", "A graphical user interface toolkit"], 0,
     "gRPC uses compact binary Protobuf serialization and multiplexed HTTP/2 transport, delivering superior speed compared to JSON REST APIs.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Protocol Buffers (Protobuf)?",
     ["Google's language-neutral, platform-neutral, extensible mechanism for serializing structured data into compact binary representations", "A buffer in printer hardware", "A network routing protocol", "An encryption key generator"], 0,
     "Protobuf compiles schema (.proto) definitions into strongly-typed code in multiple languages, serializing data much more compactly than JSON/XML.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Distributed Tracing (e.g., OpenTelemetry, Jaeger, Zipkin)?",
     ["A method used to profile and monitor microservice applications by propagating trace and span IDs to trace requests as they journey through distributed services", "Tracing drawing sketches on a tablet", "Tracing electrical wires in datacenters", "Logging mouse clicks on a website"], 0,
     "Distributed tracing correlates logs across microservices using shared Trace IDs, pinpointing latency bottlenecks in complex call graphs.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Service Mesh (e.g., Istio, Linkerd) in cloud microservices?",
     ["A dedicated infrastructure layer for handling service-to-service communication, providing load balancing, mutual TLS (mTLS), and observability via sidecar proxies", "A mesh Wi-Fi network in an office", "A 3D modeling tool for web", "A database clustering tool"], 0,
     "Service meshes inject sidecar proxies (like Envoy) beside each microservice container, transparently handling encryption, retries, and metrics.", "Medium", "Distributed Systems", "Previous Exam"),

    # 51-60
    ("What is Mutual TLS (mTLS) in microservice architectures?",
     ["A process where BOTH the client and the server authenticate each other's digital X.509 certificates simultaneously before establishing a TLS session", "Using two TLS certificates on one domain", "Encrypting passwords with two keys", "A TLS handshake that takes twice as long"], 0,
     "mTLS provides bidirectional authentication and encryption, guaranteeing that zero-trust microservice nodes communicate only with verified peers.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Edge Computing?",
     ["A distributed computing paradigm that brings computation, storage, and data processing closer to the location where it is needed (at edge devices/gateways)", "Running software on the edge of a desk", "Computing without an operating system", "Running calculations on cutting-edge CPUs"], 0,
     "Edge computing reduces latency and bandwidth costs by processing sensor and user telemetry locally rather than routing everything to central clouds.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Sharding in distributed databases?",
     ["A horizontal database partitioning technique that splits rows of a large dataset across multiple independent database server nodes", "Backing up database tables to tape", "Encrypting database column names", "Creating duplicate indexes"], 0,
     "Sharding partitions massive datasets based on a shard key, enabling databases to scale horizontally beyond single-machine limits.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is a Hot Shard (or Hot Spotting) in distributed database architectures?",
     ["A condition where an uneven shard key distribution routes an overwhelming majority of read/write requests to a single server node, bottlenecking the cluster", "A server room overheating", "A shard containing popular memes", "A database shard with encrypted data"], 0,
     "Poorly chosen shard keys (e.g., sequential timestamps) concentrate traffic onto one node, negating the throughput benefits of sharding.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Read Replica in relational database architecture?",
     ["A read-only copy of the primary database that asynchronously synchronizes with the primary, offloading query load from the master write instance", "A duplicate keyboard for typing queries", "A backup hard drive stored offline", "A cache running in the user browser"], 0,
     "Read replicas scale read-heavy applications by distributing SELECT queries across multiple replica nodes while the primary handles writes.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Replication Lag in distributed database systems?",
     ["The delay between an update being committed on the primary database node and that update becoming visible on read replica nodes", "A slow network cable connecting databases", "The time taken to buy new servers", "A pause between database backups"], 0,
     "Due to asynchronous replication, read replicas lag slightly behind the primary, occasionally serving stale data (eventual consistency).", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Split-Brain in a distributed high-availability cluster?",
     ["A failure state where a network partition isolates cluster nodes into two disconnected groups, each believing the other is dead and acting as the primary master", "A computer with two CPU chips", "A user running two operating systems", "A broken monitor displaying two screens"], 0,
     "Split-brain causes catastrophic data divergence and corruption when both sub-clusters accept concurrent conflicting writes without coordination.", "Medium", "Distributed Systems", "Previous Exam"),
    ("How do distributed clusters prevent Split-Brain scenarios during network partitions?",
     ["By requiring a Quorum: a sub-cluster is only permitted to elect a leader and accept writes if it contains a strict majority (> 50%) of total cluster nodes", "By turning off all servers immediately", "By assigning the master role to the oldest computer", "By disabling network switches"], 0,
     "Strict majority quorum rules (e.g., 2 of 3, 3 of 5) ensure that only one partition can ever hold the majority required to operate.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is a Quorum Write and Quorum Read in distributed storage (e.g., Cassandra)?",
     ["Configuring replication factor N such that Write Quorum (W) + Read Quorum (R) > N, mathematically guaranteeing that read quorums intersect at least one up-to-date replica", "Requiring 100% of all servers to agree on every single read", "Voting on database schema changes", "Writing data in four languages"], 0,
     "When W + R > N, the Pigeonhole Principle guarantees that any read quorum will overlap with at least one node containing the latest write.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is Cassandra's Snitch in distributed database topology?",
     ["A component that determines the relative network topology (racks and datacenters) of nodes to route requests efficiently and place replicas across fault domains", "A security spy logging user queries", "A tool that detects corrupted data blocks", "A firewall module"], 0,
     "Snitches map IP addresses to physical racks and datacenters, ensuring Cassandra places replica copies across independent power and network failure zones.", "Hard", "Distributed Systems", "Previous Exam"),

    # 61-70
    ("What is Bloom Filter used for in distributed database storage engines (e.g., LSM-trees in Cassandra and RocksDB)?",
     ["A space-efficient probabilistic data structure used to rapidly test whether an element is definitely NOT present in an SSTable on disk, avoiding expensive disk reads", "A filter that cleans dust inside server cases", "A search algorithm for sorting strings", "An image processing filter for websites"], 0,
     "Bloom filters provide fast in-memory lookups: they never produce false negatives (if it says 'not present', it's guaranteed), saving disk I/O.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is an LSM-Tree (Log-Structured Merge-tree)?",
     ["A storage engine architecture optimized for high write throughput that buffers writes in an in-memory MemTable before flushing sequentially to immutable on-disk SSTables", "A binary search tree saved in memory", "A file system used on Linux laptops", "A network routing protocol"], 0,
     "LSM-trees convert random disk writes into sequential disk flushes and background merges (compaction), outperforming B-trees for write-heavy workloads.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is an SSTable (Sorted String Table) in storage engines?",
     ["An immutable disk file containing a set of key-value pairs sorted in lexicographical order by key, with associated index blocks", "A table stored in HTML format", "A table in Microsoft Excel", "A temporary table in RAM"], 0,
     "SSTables are read-only sequential disk files; because keys are sorted, finding keys requires only sparse index lookups and sequential reads.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is WAL (Write-Ahead Logging) in database systems?",
     ["A technique where all data modifications are appended sequentially to a persistent log on disk BEFORE being applied to in-memory tables, guaranteeing crash durability", "Writing data to a wall on a whiteboard", "A log of all user login attempts", "A protocol for sending emails"], 0,
     "WAL ensures durability (the D in ACID): if power fails, the database re-reads the WAL on reboot to recover committed in-memory transactions.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Idempotency Key in payment processing APIs (e.g., Stripe)?",
     ["A unique client-generated token sent in HTTP headers that the server records so that network retries of the payment request do not result in duplicate charges", "The encryption key for credit card numbers", "A password for the API account", "A certificate used in SSL handshakes"], 0,
     "Idempotency keys ensure safety during network timeouts: clients safely retry the exact same request without charging the customer twice.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Rate Limiting and what is the Token Bucket algorithm?",
     ["A traffic management algorithm where tokens are added to a bucket at a fixed rate; requests consume a token to proceed, rejecting or queuing requests when empty", "A bucket used to collect water in datacenters", "A method for counting website visitors", "A tool for compressing images"], 0,
     "Token bucket permits configurable bursts of traffic up to the bucket capacity while maintaining a smooth long-term average request throughput.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is the Leaky Bucket algorithm in network rate limiting?",
     ["Requests enter a bucket of fixed capacity and are processed/leaked at a constant, uniform output rate, smoothing out erratic traffic bursts", "A bucket that has a hole leaking water", "A memory leak bug in C programs", "A firewall that drops random packets"], 0,
     "Unlike token bucket (which allows bursts up to bucket size), leaky bucket strictly smooths traffic output to a constant predictable rate.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the difference between Load Balancing Layer 4 (L4) and Layer 7 (L7)?",
     ["L4 balances traffic based on transport layer IP addresses and TCP/UDP ports without inspecting packet payloads; L7 inspects application layer data (HTTP headers, URLs, cookies)", "L4 is for software; L7 is for hardware", "L7 cannot balance web traffic", "There is no difference in load balancing layers"], 0,
     "L4 (e.g., AWS NLB) is ultra-fast packet-level routing; L7 (e.g., AWS ALB, NGINX) enables content-based routing (e.g., /api to service A, /static to service B).", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Dark Launching in web deployment strategies?",
     ["Releasing new software features to production silently to test backend scalability and performance on real user traffic without enabling the user-facing UI", "Launching a website during nighttime hours", "Deploying software on the dark web", "Shutting down the monitor during deployment"], 0,
     "Dark launching exposes new backend services to production load by duplicating or mirroring live traffic without exposing frontend UI to users.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Canary Deployment?",
     ["Gradually rolling out a new software release to a tiny subset of real production users (e.g., 2%), monitoring error metrics before routing all traffic", "Testing software in coal mines", "Deploying software to mobile phones first", "A deployment that uses yellow banners"], 0,
     "Canary releases expose minimal blast radius: if errors spike among the 2% canary cohort, automated systems revert changes before widespread impact.", "Easy", "Distributed Systems", "Previous Exam"),

    # 71-80
    ("What is Rolling Deployment?",
     ["Progressively updating instances of an application across a server pool by taking down a fraction of nodes, updating them, and returning them to service sequentially", "Rolling computer chassis across a floor", "A deployment done every Sunday morning", "A deployment that loops continuously"], 0,
     "Rolling updates update nodes incrementally (e.g., 25% at a time), keeping the service available throughout the deployment without duplicate hardware.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is a Service Level Indicator (SLI) in Site Reliability Engineering?",
     ["A carefully defined quantitative measure of some aspect of the level of service provided (such as latency, error rate, or throughput)", "A dashboard indicator light on the server rack", "An employee satisfaction survey", "The number of lines of code deployed per day"], 0,
     "An SLI is a concrete metric (e.g., request latency < 200ms) that is tracked against a Service Level Objective (SLO).", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Infrastructure as Code (IaC) (e.g., Terraform, Ansible)?",
     ["Managing and provisioning computing infrastructure (servers, networks, storage) through machine-readable definition files rather than manual physical configuration or web portals", "Writing operating systems in Python", "Building server hardware from scratch", "Printing network schematics on paper"], 0,
     "IaC treats infrastructure declarations with software best practices: version-controlled in Git, peer-reviewed, reproducible, and automated.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is Immutable Infrastructure?",
     ["An infrastructure paradigm where servers and containers are never modified or patched in-place; updates are performed by deploying brand-new pre-configured images and destroying old ones", "Servers made of solid metal", "Datacenters that cannot be closed", "Hard drives that cannot be written to"], 0,
     "Immutable infrastructure prevents configuration drift: servers are completely replaced on every release rather than patched incrementally.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Configuration Drift in server management?",
     ["The gradual diverging of server configurations from their intended baseline over time due to ad-hoc manual changes, hotfixes, and package updates", "Computers sliding across server racks", "Network cables bending over time", "A change in user interface colors"], 0,
     "Manual tweaks on production nodes lead to untracked differences (drift), making deployments unpredictable and debugging nearly impossible.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is the Twelve-Factor App methodology principle regarding configuration?",
     ["Strict separation of config from code: store configuration in environment variables rather than hardcoding them in source code", "Store all passwords in text files in Git", "Configure servers using GUI wizards", "Config files must be compiled into binaries"], 0,
     "Factor III mandates config in environment variables: identical code repos can be deployed across dev, staging, and prod simply by varying env vars.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is the Twelve-Factor App methodology principle regarding processes?",
     ["Execute the app as one or more stateless processes that share nothing and persist all stateful data to external backing services (databases, caches)", "Applications must run in a single process", "Processes must never be terminated", "Processes should store user sessions in local disk files"], 0,
     "Factor VI states processes are stateless and share-nothing: any persistent state resides in stateful datastores, enabling seamless horizontal scaling.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Sticky Sessions (Session Affinity) in load balancers, and why is it generally discouraged in cloud architectures?",
     ["Routing all requests from a specific client to the same backend server; it prevents even load distribution and loses user sessions if that server crashes", "Sticking server cables with tape", "A session that never logs out", "A feature that speeds up internet cables"], 0,
     "Sticky sessions create stateful coupling to specific servers; modern designs store sessions in shared caches (Redis) to allow true stateless load balancing.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is a Reverse Proxy (e.g., NGINX, HAProxy)?",
     ["A server that sits in front of backend web servers and forwards client requests to those servers, handling SSL termination, compression, caching, and security", "A client that downloads files backwards", "A proxy used by end users to bypass school firewalls", "A cable connecting two monitors"], 0,
     "Forward proxies act on behalf of clients; Reverse proxies act on behalf of origin servers, shielding them and optimizing traffic flow.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is SSL/TLS Termination at a reverse proxy or load balancer?",
     ["Decrypting incoming encrypted HTTPS traffic at the load balancer and passing unencrypted HTTP requests to internal backend servers within the private network", "Shutting down the SSL certificate authority", "An error during an SSL handshake", "Deleting SSL keys from disk"], 0,
     "TLS termination relieves backend application servers from the computational overhead of cryptographic handshakes, centralizing certificate renewals.", "Medium", "Distributed Systems", "Previous Exam"),

    # 81-90
    ("What is Database Read-Your-Writes Consistency (Immediate Consistency for Author)?",
     ["A consistency guarantee where a user is always guaranteed to immediately observe their own updates, even if other users might temporarily see stale data", "A database that reads aloud to users", "A requirement that all database updates be printed on paper", "A database that only accepts read commands"], 0,
     "Read-your-writes prevents confusing user UX (e.g., submitting a comment and not seeing it on page refresh due to replica lag) by routing author reads to the primary.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Monotonic Read Consistency in distributed storage?",
     ["If a client reads a particular value of a data item, the client will never subsequently observe an older or previous value of that item", "Reading data at a constant musical pitch", "Reading data using only one CPU core", "Reading database tables from top to bottom"], 0,
     "Monotonic reads ensure time does not appear to move backward for a client moving between different lagging read replicas.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Monotonic Write Consistency?",
     ["A system guarantee that a given user's writes are processed and serialized strictly in the order that they were submitted", "Writing database code without functions", "A single-threaded write database", "Writing data in one font size"], 0,
     "Monotonic writes guarantee that dependent updates (e.g., update profile then upload picture) are never applied out-of-order on any replica.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Causal Consistency in distributed systems?",
     ["Operations that are causally related must be seen by every node in the same order, while concurrent operations unrelated causally may be seen in different orders", "A consistency model based on causal clothing", "All events must have a reason in logs", "A system without network partitions"], 0,
     "Causal consistency is the strongest consistency model achievable in an available and partition-tolerant (AP) distributed system.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is a Gossip Protocol (Epidemic Protocol)?",
     ["A decentralized peer-to-peer communication mechanism where nodes periodically share state information with a few randomly selected peers, propagating data like a virus", "Employees talking in an office hallway", "A virus that infects social media accounts", "A security vulnerability leaking gossip"], 0,
     "Gossip protocols (used in Cassandra, Consul) provide robust, fault-tolerant cluster membership and failure detection in O(log N) rounds.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the Phi (phi) Accrual Failure Detector?",
     ["A failure detection algorithm that outputs a continuous scale of suspicion (phi value) rather than a binary up/down state based on historical heartbeat intervals", "A tool for detecting hardware short circuits", "A formula for calculating server cost", "A method for checking broken links"], 0,
     "Instead of rigid timeout flags, phi accrual measures statistical heartbeat variance, adapting flexibly to fluctuating network latency.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is a Dead Letter Queue (DLQ) in messaging architectures?",
     ["A dedicated queue that stores messages that cannot be successfully processed or delivered after reaching a maximum retry threshold", "A queue of deleted emails", "A broken network cable queue", "A queue containing spam messages"], 0,
     "DLQs isolate problematic or poison-pill messages for developer inspection without blocking the processing pipeline of legitimate messages.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is a Poison Pill message in message queues?",
     ["A malformed or unexpected message that consistently causes the consumer application to crash or throw an unhandled exception whenever processing is attempted", "A computer virus disguised as a game", "An expired database record", "A corrupt hard drive sector"], 0,
     "Poison pills trigger infinite crash-and-redelivery loops unless captured and diverted to a Dead Letter Queue.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Exactly-Once Processing (EOP) in stream processing systems (e.g., Kafka Streams, Apache Flink)?",
     ["The guarantee that stream processing logic affects downstream state and output exactly once, typically achieved via idempotent writes and two-phase commits", "Processing a message in 1 millisecond", "A system that allows only 1 user", "Deleting a message immediately upon arrival"], 0,
     "True end-to-end exactly-once coordinates source offsets, state snapshots, and sink commits (e.g., using transactional producers) to eliminate duplicate effects.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is At-Least-Once Delivery compared to At-Most-Once Delivery?",
     ["At-Least-Once guarantees messages will never be lost but may be delivered multiple times; At-Most-Once guarantees messages are never duplicated but may be lost", "At-Least-Once is for email; At-Most-Once is for video", "At-Most-Once guarantees 100% reliability", "They are identical delivery guarantees"], 0,
     "At-Least-Once retries unacknowledged transmissions (requiring idempotence on the receiver); At-Most-Once fires and forgets without retrying.", "Easy", "Distributed Systems", "Previous Exam"),

    # 91-100
    ("What is Event Sourcing in distributed data architectures?",
     ["Storing the state of a business entity as an append-only sequence of immutable state-changing domain events rather than just the current state", "Recording sound events in a software application", "Tracking mouse clicks on websites", "Saving calendar appointments in a database"], 0,
     "Event Sourcing maintains an immutable audit log of all domain events; the current application state is reconstructed by replaying events from inception.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the CQRS (Command Query Responsibility Segregation) pattern?",
     ["Separating read and write operations into distinct models, using commands to update data and separate queries to read data", "Using separate computer screens for typing and reading", "A command prompt interface for SQL", "A database that only accepts queries"], 0,
     "CQRS decouples write-side business invariants from read-side query optimizations (often pairing with Event Sourcing and materialized views).", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is Change Data Capture (CDC, e.g., Debezium)?",
     ["A software pattern that monitors and captures row-level database changes directly from transaction commit logs and streams them to event brokers (like Kafka)", "A camera capturing computer screen changes", "A tool for recording mouse movements", "A database backup utility"], 0,
     "CDC streams database inserts, updates, and deletes directly from database WALs to downstream caches and search indices without modifying application code.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is the WebSocket Handshake mechanism?",
     ["An initial HTTP GET request with 'Upgrade: websocket' and 'Connection: Upgrade' headers, resulting in a '101 Switching Protocols' response from the server", "Shaking hands between system administrators", "A 3-way TCP handshake between routers", "Exchanging public keys over UDP"], 0,
     "WebSockets initiate over standard HTTP/1.1; upon receiving HTTP 101, the underlying TCP connection transitions into a bi-directional WebSocket stream.", "Easy", "Distributed Systems", "Previous Exam"),
    ("What is a Distributed Lock (e.g., Redlock in Redis, or Apache ZooKeeper recipes)?",
     ["A synchronization mechanism that ensures mutually exclusive access to shared resources across multiple independent processes running on different machines", "A physical padlock on a server rack", "An encrypted hard drive on the cloud", "A password required to open a database"], 0,
     "Distributed locks prevent concurrent workers across clusters from simultaneously modifying the same shared external resource or executing duplicate batch jobs.", "Medium", "Distributed Systems", "Previous Exam"),
    ("In Apache ZooKeeper, what is an Ephemeral Znode?",
     ["A temporary znode that is automatically deleted by ZooKeeper when the client session that created it disconnects or times out", "A znode stored only on floppy disks", "A znode with no data", "A znode that cannot be modified"], 0,
     "Ephemeral nodes automatically disappear upon client session expiration, serving as the foundational building block for leader election and failure detection.", "Hard", "Distributed Systems", "Previous Exam"),
    ("What is BGP Anycast routing and how is it used by modern CDNs and DNS providers (e.g., Cloudflare 1.1.1.1, Google 8.8.8.8)?",
     ["Announcing the exact same IP address from multiple geographically distributed datacenters worldwide, routing users automatically to the nearest datacenter via BGP", "Broadcasting radio signals to all internet users", "Sending packets to all IP addresses simultaneously", "A private VPN protocol for companies"], 0,
     "Anycast assigns one IP to hundreds of worldwide PoPs; internet BGP routing automatically sends user packets to the topologically closest healthy edge node.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is the difference between Write-Through and Write-Behind (Write-Back) distributed caching?",
     ["Write-Through writes to the cache and backing database synchronously before returning; Write-Behind writes to cache immediately and flushes to database asynchronously", "Write-Through is only for SSDs", "Write-Behind deletes data after writing", "They are identical caching strategies"], 0,
     "Write-Through guarantees data consistency at the expense of higher write latency; Write-Behind delivers ultra-fast writes but risks data loss on cache crash.", "Medium", "Distributed Systems", "Previous Exam"),
    ("What is a Service Level Objective (SLO) compared to a Service Level Agreement (SLA)?",
     ["An SLO is an internal target metric for service reliability (e.g., 99.9% uptime); an SLA is an external legal agreement with customers carrying financial penalties", "An SLA is internal; an SLO is external", "SLO measures CPU temperature; SLA measures network speed", "There is no difference in site reliability engineering"], 0,
     "SLOs are engineering goals that guide alerting and error budgets; SLAs are external contractual agreements specifying business penalties if violated.", "Easy", "Distributed Systems", "Previous Exam"),
    ("In Site Reliability Engineering (SRE), what is an Error Budget?",
     ["The maximum allowable downtime or error rate a service can accumulate over a time period (100% minus the SLO) before halting new feature releases", "The money set aside to pay for server repairs", "The total number of bugs found by QA", "A tax penalty paid for server crashes"], 0,
     "Error budgets quantify acceptable risk: if a 99.9% SLO allows 0.1% errors, teams deploy features aggressively until the budget is depleted, then prioritize reliability.", "Medium", "Distributed Systems", "Previous Exam")
]

print(f"Total Part 9 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part9_data = []
for i, q in enumerate(questions):
    qid = f"p9-q{i+1}"
    part9_data.append({
        "id": qid,
        "part": 9,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part9.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_9_QUESTIONS: Question[] = ")
    json.dump(part9_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 9 successfully to src/data/parts/part9.ts")
