#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("Which of the following is NOT one of the four necessary Coffman conditions required for a deadlock to occur in an operating system?",
     ["Mutual Exclusion", "Hold and Wait", "Preemptive Resource Allocation", "Circular Wait"], 2,
     "Deadlock requires No Preemption, not preemptive resource allocation. The four conditions are Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait.", "Medium", "Operating Systems", "Previous Exam"),
    ("Which CPU scheduling algorithm can suffer from the 'Convoy Effect' where short processes queue behind a long CPU-bound process?",
     ["Round Robin (RR)", "First-Come, First-Served (FCFS)", "Shortest Job First (SJF)", "Multi-Level Feedback Queue (MLFQ)"], 1,
     "In FCFS scheduling, a long CPU-burst process at the head of the ready queue delays all subsequent short I/O-bound processes (Convoy Effect).", "Easy", "Operating Systems", "Previous Exam"),
    ("What phenomenon describes a situation where increasing the number of page frames allocated to a process results in an INCREASE in the number of page faults?",
     ["Thrashing", "Belady's Anomaly", "Aging", "Starvation"], 1,
     "Belady's Anomaly occurs in FIFO page replacement, where providing more physical page frames unexpectedly causes more page faults.", "Medium", "Operating Systems", "Previous Exam"),
    ("In UNIX-like operating systems, what is the return value of the fork() system call in the newly created child process?",
     ["The Process ID (PID) of the parent process", "0", "-1", "A newly generated unique file descriptor"], 1,
     "Upon successful creation, fork() returns 0 to the child process and returns the child's PID to the parent process.", "Easy", "Operating Systems", "Previous Exam"),
    ("Which synchronization primitive is a variable that is accessed only through two standard atomic operations: wait() (or P) and signal() (or V)?",
     ["Mutex lock", "Semaphore", "Condition variable", "Monitor"], 1,
     "A semaphore is an integer variable accessed exclusively through atomic wait() and signal() operations.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is thrashing in virtual memory management?",
     ["A process spending more time paging in and out of swap space than executing instructions", "Sudden mechanical failure of the hard disk drive", "A deadlock between kernel threads", "High fragmentation in heap memory"], 0,
     "Thrashing happens when system page fault rates become so high that the OS spends nearly all CPU time swapping pages rather than executing application code.", "Medium", "Operating Systems", "Previous Exam"),
    ("Which disk scheduling algorithm services requests by moving the read/write head continuously from one end of the disk to the other, reversing direction at the end (the Elevator algorithm)?",
     ["SSTF (Shortest Seek Time First)", "SCAN", "C-SCAN (Circular SCAN)", "LOOK"], 1,
     "SCAN moves the disk arm across all cylinders in one direction servicing requests, and reverses direction when reaching the disk end.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is an 'orphan process' in UNIX operating systems?",
     ["A process whose parent process terminated before calling wait()", "A process that has finished execution but still has an entry in the process table", "A process running with root privileges", "A background daemon process with no terminal"], 0,
     "An orphan process is a running process whose parent has terminated; it is automatically adopted by PID 1 (init/systemd).", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a 'zombie process' in operating systems?",
     ["A process executing an infinite loop", "A terminated process whose parent has not yet read its exit status via wait()", "A malicious virus payload", "A suspended process swapped entirely to disk"], 1,
     "A zombie process has finished execution and released its memory, but retains its process table entry until the parent reaps its exit code.", "Medium", "Operating Systems", "Previous Exam"),
    ("Which memory allocation strategy allocates the smallest available free memory hole that is large enough to satisfy the request?",
     ["First Fit", "Best Fit", "Worst Fit", "Next Fit"], 1,
     "Best Fit searches the entire free list to find the smallest hole that fits the requested size, minimizing leftover fragment size.", "Easy", "Operating Systems", "Previous Exam"),

    # 11-20
    ("What is the primary function of the Translation Lookaside Buffer (TLB)?",
     ["Store file system metadata", "Speed up virtual-to-physical address translation by caching page table entries in hardware", "Schedule threads across CPU cores", "Prevent stack overflow attacks"], 1,
     "The TLB is a high-speed associative hardware cache that retains recent page-to-frame translations to avoid main-memory page table walks.", "Medium", "Operating Systems", "Previous Exam"),
    ("In the Banker's Algorithm for deadlock avoidance, a system is in a 'safe state' if:",
     ["There are zero pending resource requests", "There exists at least one safe execution sequence that allows all processes to finish without deadlocking", "No processes share any resources", "Total available resources exceed 50%"], 1,
     "A state is safe if there exists a safe sequence of processes such that each can satisfy its maximum resource claims with currently available and released resources.", "Hard", "Operating Systems", "Previous Exam"),
    ("Which page replacement algorithm is theoretically optimal but impossible to implement in practice because it requires future knowledge?",
     ["Least Recently Used (LRU)", "Optimal Page Replacement (OPT / MIN)", "Second-Chance (Clock)", "Least Frequently Used (LFU)"], 1,
     "The Optimal algorithm replaces the page that will not be used for the longest period in the future, serving as an impossible benchmark.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is internal fragmentation in memory management?",
     ["Unallocated memory holes distributed between allocated memory partitions", "Memory allocated to a partition or frame that remains unused by the process occupying it", "Fragmentation of files on a secondary disk drive", "Corrupted memory sectors in RAM"], 1,
     "Internal fragmentation occurs when fixed-size blocks (like pages) are allocated and the process data does not fill the entire allocated block.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is external fragmentation?",
     ["Storage space within a page frame that remains empty", "Total free memory space is sufficient to satisfy a request, but it is divided into non-contiguous scattered holes", "Swapping memory to an external USB drive", "Memory leaks in user-space applications"], 1,
     "External fragmentation arises when dynamic partitions leave many small unusable free blocks scattered across memory.", "Easy", "Operating Systems", "Previous Exam"),
    ("In UNIX, what does the execve() system call do?",
     ["Creates a new concurrent child process", "Replaces the current process image, code, and data with a new program", "Suspends process execution until a timer expires", "Terminates the operating system kernel"], 1,
     "The exec() family of system calls replaces the current process address space, text, and data with an entirely new executable program.", "Medium", "Operating Systems", "Previous Exam"),
    ("Which component of the operating system is responsible for switching the CPU core from one process context to another during multitasking?",
     ["Job scheduler (Long-term scheduler)", "Dispatcher", "Page fault handler", "File system inode manager"], 1,
     "The dispatcher gives control of the CPU to the process selected by the short-term scheduler, performing context switching and mode switching.", "Medium", "Operating Systems", "Previous Exam"),
    ("What are the three mandatory criteria a valid solution to the Critical Section Problem must satisfy?",
     ["Atomicity, Consistency, Isolation", "Mutual Exclusion, Progress, Bounded Waiting", "Preemption, Starvation, Deadlock", "Fairness, Throughput, Latency"], 1,
     "Any correct critical section solution must guarantee Mutual Exclusion, Progress (no deadlock among contending processes), and Bounded Waiting (no starvation).", "Hard", "Operating Systems", "Previous Exam"),
    ("What is an inode in a POSIX/UNIX file system?",
     ["The name of a directory in the root partition", "A data structure that stores all file metadata (permissions, ownership, size, block pointers) except file name and data", "A software interrupt used to mount filesystems", "The master boot record of the disk"], 1,
     "An inode stores file attributes, permissions, timestamps, and direct/indirect block pointers; the file name is stored separately in the directory entry.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the primary purpose of a spinlock?",
     ["A lock where a waiting thread repeatedly checks a condition in a loop ('busy waiting') rather than sleeping", "A lock that spins the hard drive platter faster", "A lock used exclusively in single-tasking operating systems", "A lock that encrypts disk blocks"], 0,
     "Spinlocks use busy-waiting to acquire locks, suitable for multiprocessor systems where expected wait times are shorter than context-switch overhead.", "Medium", "Operating Systems", "Previous Exam"),

    # 21-30
    ("Which CPU scheduling metric represents the elapsed time from process submission to its complete termination?",
     ["Waiting Time", "Response Time", "Turnaround Time", "Throughput"], 2,
     "Turnaround time is the total duration spent from the moment a process enters the system until it finishes execution.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the difference between a user-level thread (ULT) and a kernel-level thread (KLT)?",
     ["ULT management is handled entirely by a user-space library without kernel intervention, while KLT is scheduled directly by the OS kernel", "ULTs are faster because they run with root hardware privileges", "KLTs cannot be executed on multicore processors", "ULTs cannot perform arithmetic calculations"], 0,
     "User threads are scheduled in user space without kernel awareness, whereas kernel threads are managed and scheduled directly by the OS kernel.", "Medium", "Operating Systems", "Previous Exam"),
    ("In paging systems, what hardware feature enables protection against unauthorized memory writes to code pages?",
     ["Dirty bit", "Valid/Invalid and Read/Write/Execute permission bits in page table entries", "TLB size limitation", "Paging file size limit"], 1,
     "Page table entries include permission bits (Read, Write, Execute) and valid/invalid bits enforced by hardware during address translation.", "Easy", "Operating Systems", "Previous Exam"),
    ("What happens during a context switch?",
     ["The CPU converts source code into machine code", "The state of the currently executing process is saved in its PCB and the saved state of the next process is restored", "The computer switches from battery to AC power", "RAM contents are wiped clean"], 1,
     "Context switching saves the register state, program counter, and CPU status of the active process into its PCB, and loads another process's state.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the role of the dirty bit (modified bit) in a page table entry?",
     ["Indicates whether the page has been modified since it was loaded into RAM", "Indicates that the page contains malware", "Marks the page as eligible for garbage collection", "Indicates the page is locked in cache"], 0,
     "The dirty bit is set by hardware whenever the page is written to; if set, the page must be written back to disk before frame reuse.", "Medium", "Operating Systems", "Previous Exam"),
    ("Which inter-process communication (IPC) mechanism allows two or more processes to access the same physical memory addresses directly without kernel copying?",
     ["Pipes", "Message Queues", "Shared Memory", "UNIX Domain Sockets"], 2,
     "Shared memory allows multiple processes to map the same physical memory region into their virtual address spaces, enabling zero-copy high-speed IPC.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the Working Set Model in operating systems used for?",
     ["Determining process working hours in enterprise software", "Estimating a process's page locality over a parameter window to allocate adequate frames and prevent thrashing", "Balancing thread load on GPU shaders", "Organizing desktop windows"], 1,
     "Peter Denning's Working Set Model defines the set of pages referenced by a process within a given time delta to prevent thrashing.", "Hard", "Operating Systems", "Previous Exam"),
    ("In the dining philosophers problem, what dangerous condition can occur if every philosopher simultaneously picks up their left fork?",
     ["Segmentation fault", "Deadlock (every philosopher waits indefinitely for the right fork)", "Buffer overflow", "Hardware clock drift"], 1,
     "If all philosophers pick up their left fork simultaneously, circular wait occurs and none can acquire their right fork, resulting in deadlock.", "Medium", "Operating Systems", "Previous Exam"),
    ("Which disk scheduling algorithm selects pending requests that require the least head movement from the current cylinder position?",
     ["FCFS", "SSTF (Shortest Seek Time First)", "SCAN", "C-LOOK"], 1,
     "SSTF chooses the request with minimum seek distance from the current arm position, though it can cause starvation for distant requests.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the primary difference between SCAN and C-SCAN disk scheduling?",
     ["C-SCAN reverses direction and services requests on the way back", "C-SCAN services requests in only one direction; upon reaching the end, it immediately returns to the start without servicing on the return trip", "SCAN cannot be implemented on modern SSDs", "C-SCAN requires circular disk tracks"], 1,
     "C-SCAN (Circular SCAN) treats cylinders as a circular list, servicing requests in one direction only to provide more uniform waiting times.", "Medium", "Operating Systems", "Previous Exam"),

    # 31-40
    ("What is a race condition in concurrent programming?",
     ["Two threads competing for CPU time in round-robin scheduling", "A situation where multiple threads access and manipulate shared data concurrently and the outcome depends on execution order", "A race between disk read and network transmission", "A compiler race to optimize bytecode"], 1,
     "A race condition occurs when concurrent threads access shared state without synchronization and the final result depends on non-deterministic timing.", "Easy", "Operating Systems", "Previous Exam"),
    ("What does the Peterson's algorithm achieve in computer science?",
     ["A software-based mutual exclusion algorithm for two concurrent processes", "A sorting algorithm with O(n log n) runtime", "A file compression algorithm", "A network routing protocol"], 0,
     "Peterson's algorithm is a classic software solution ensuring mutual exclusion, progress, and bounded waiting for two processes.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the purpose of the Test-and-Set hardware instruction?",
     ["Perform atomic read-modify-write operation on a memory word to implement mutual exclusion locks", "Verify if a RAM chip is physically defective", "Test network latency", "Benchmark CPU instruction rates"], 0,
     "Test-and-Set atomically reads a memory location and sets it to true in a single uninterruptible hardware cycle, enabling lock implementation.", "Hard", "Operating Systems", "Previous Exam"),
    ("What is a counting semaphore as opposed to a binary semaphore?",
     ["A semaphore whose integer value can range over an unrestricted integer domain to manage pools of identical resources", "A semaphore that counts CPU clock cycles", "A semaphore restricted to values 0 and 1 only", "A hardware counter on the motherboard"], 0,
     "A counting semaphore holds an integer count representing the number of available resource units, whereas a binary semaphore holds only 0 or 1.", "Medium", "Operating Systems", "Previous Exam"),
    ("In modern microkernel operating systems, what is moved out of the kernel space into user space?",
     ["Low-level hardware interrupts and basic IPC", "Device drivers, file systems, and network protocol stacks", "CPU context switching logic", "Virtual memory page frame tables"], 1,
     "Microkernels retain only minimal essential services (IPC, basic scheduling, primitive memory) in kernel mode, running drivers and file systems in user space.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the function of the swap space on a secondary storage drive?",
     ["Store deleted user files temporarily", "Hold pages or entire processes moved out of RAM when physical memory is overcommitted", "Store operating system kernel source code", "Backup the BIOS configuration"], 1,
     "Swap space is a dedicated disk partition or file used by virtual memory to hold evicted memory pages when physical RAM is full.", "Easy", "Operating Systems", "Previous Exam"),
    ("In UNIX permissions, what does the octal permission mode '754' grant?",
     ["rwxr-xr-- (Owner: rwx, Group: r-x, Others: r--)", "rwxrwxrwx", "rw-r--r--", "r-xr-xr-x"], 0,
     "7 = 4+2+1 (rwx), 5 = 4+0+1 (r-x), 4 = 4+0+0 (r--). Therefore, 754 corresponds to rwxr-xr--.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the function of the dup2() system call in UNIX?",
     ["Duplicate an open file descriptor onto a specified target descriptor number", "Double the size of a disk partition", "Fork two identical child processes simultaneously", "Create a duplicate user account"], 0,
     "dup2(oldfd, newfd) duplicates an open file descriptor to newfd, commonly used for standard I/O redirection (stdin/stdout).", "Medium", "Operating Systems", "Previous Exam"),
    ("What is an inverted page table?",
     ["A page table indexed by physical frame number rather than virtual page number, containing one entry per physical frame", "A page table sorted in reverse alphabetical order", "A page table stored on disk swap space", "A page table with inverted permissions"], 0,
     "An inverted page table has one entry per physical frame in RAM, substantially reducing memory consumption on 64-bit systems.", "Hard", "Operating Systems", "Previous Exam"),
    ("Which RAID configuration uses block-level striping across disks with distributed parity?",
     ["RAID 0", "RAID 1", "RAID 5", "RAID 10"], 2,
     "RAID 5 stripes data and distributes parity information evenly across all member disks, tolerating the failure of any single drive.", "Medium", "Operating Systems", "Previous Exam"),

    # 41-50
    ("What does RAID 0 provide?",
     ["Data mirroring for fault tolerance", "Block-level striping without parity or redundancy, maximizing performance at the cost of zero fault tolerance", "Dual distributed parity", "Dedicated parity disk"], 1,
     "RAID 0 splits data across multiple drives without parity; if any drive fails, all data is lost.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the function of the nice value in UNIX process scheduling?",
     ["Adjusts process scheduling priority; higher nice values lower process priority, being 'nice' to others", "Measures the code beauty score", "Controls screen brightness", "Limits disk write bandwidth"], 0,
     "The nice value ranges from -20 (highest priority) to +19 (lowest priority), adjusting the dynamic CPU scheduling weight.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the purpose of the mmap() system call?",
     ["Map files or anonymous memory directly into the process's virtual address space", "Display physical memory chips on screen", "Install new network drivers", "Convert IP addresses to MAC addresses"], 0,
     "mmap() maps a file or device directly into virtual memory, allowing memory-mapped file I/O using regular pointer dereferencing.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is an atomic operation in operating systems?",
     ["An operation that executes completely without any interruption or intermediate state visible to other threads", "An operation involving radioactive elements", "An operation that takes zero clock cycles", "A background cron task"], 0,
     "An atomic operation executes as a single indivisible unit: it either runs to completion or has no effect, with no observable intermediate state.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is copy-on-write (COW) used for during process creation via fork()?",
     ["Postpone duplicating physical pages until either parent or child attempts to write to a page", "Copy all RAM contents to secondary storage immediately", "Encrypt memory pages upon copy", "Write logs to disk synchronously"], 0,
     "Copy-On-Write shares physical memory pages read-only between parent and child until one modifies a page, avoiding wasteful copying.", "Hard", "Operating Systems", "Previous Exam"),
    ("What causes a page fault interrupt to occur in a computer system?",
     ["A process attempts to access a virtual page marked invalid in the page table (not currently resident in physical RAM)", "Physical RAM power failure", "Stack pointer pointing to heap", "Division by zero in CPU"], 0,
     "A page fault occurs when the hardware MMU encounters a non-present (invalid) page entry, trapping to the OS kernel to load it from disk.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is priority inversion in real-time operating systems?",
     ["A higher-priority task is indirectly blocked by a lower-priority task holding a shared resource, while an intermediate-priority task runs", "Inverting screen colors for accessibility", "Reversing priority queue order", "Swapping kernel and user mode"], 0,
     "Priority inversion occurs when a low-priority task holds a lock needed by a high-priority task, and medium tasks prevent the low-priority task from finishing.", "Hard", "Operating Systems", "Previous Exam"),
    ("Which protocol resolves the priority inversion problem in real-time systems?",
     ["Priority Inheritance Protocol", "Shortest Job First Protocol", "Two-Phase Commit Protocol", "Round-Robin Protocol"], 0,
     "Priority inheritance elevates the priority of the lower-priority lock holder to that of the highest-priority waiting task until the lock is released.", "Hard", "Operating Systems", "Previous Exam"),
    ("What is the difference between monolithic kernels and microkernels?",
     ["Monolithic kernels run all OS services (file system, drivers, scheduler) in supervisor space; microkernels minimize kernel space code", "Monolithic kernels cannot support networking", "Microkernels are always slower than virtual machines", "Microkernels do not support multi-threading"], 0,
     "Monolithic kernels bundle core services in one supervisor space for speed; microkernels separate services into user space for stability.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is an unbuffered pipe in UNIX?",
     ["A unidirectional communication channel connecting stdout of one process to stdin of another via kernel memory", "A physical copper pipe inside the chassis", "A network socket over TCP", "A temporary file saved on the hard drive"], 0,
     "A pipe is a unidirectional IPC byte stream in kernel memory providing FIFO data transmission between related processes.", "Easy", "Operating Systems", "Previous Exam"),

    # 51-60
    ("What is the function of the sync() system call in UNIX?",
     ["Flush all dirty filesystem cache buffers from RAM onto persistent storage", "Synchronize computer clock with NTP server", "Lock CPU threads into lockstep execution", "Kill background processes"], 0,
     "sync() forces all modified file and inode buffers in kernel cache to be written immediately to physical disk storage.", "Easy", "Operating Systems", "Previous Exam"),
    ("What does POSIX stand for?",
     ["Portable Operating System Interface", "Public Operating Standard for Internet eXchange", "Protected Open System Interface for Xenix", "Processor Optimized System Instruction eXtension"], 0,
     "POSIX (Portable Operating System Interface) is an IEEE standard family maintaining software compatibility across operating systems.", "Easy", "Operating Systems", "Previous Exam"),
    ("In memory management, what is compaction?",
     ["Shuffling allocated memory partitions together to merge all scattered free holes into one large contiguous block", "Compressing text files with gzip", "Reducing process stack size", "Deleting old operating system logs"], 0,
     "Compaction relocates in-use memory segments dynamically to eliminate external fragmentation, combining free memory holes.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a semaphore's value when initialized to 1?",
     ["It acts as a binary semaphore (mutex) providing mutual exclusion", "It allows infinite concurrent processes", "It indicates the system has deadlocked", "It halts process execution"], 0,
     "A semaphore initialized to 1 functions as a binary semaphore (mutex) where only one process can enter the critical region at a time.", "Easy", "Operating Systems", "Previous Exam"),
    ("What happens if a process attempts to execute a privileged CPU instruction in user mode?",
     ["The hardware generates a trap/exception and transfers control to the kernel handler", "The CPU executes it normally without restriction", "The motherboard shuts down immediately", "The instruction is silently skipped"], 0,
     "Attempting to execute privileged instructions in user mode triggers a hardware protection trap, terminating or signaling the offending process.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the role of the short-term CPU scheduler (CPU scheduler)?",
     ["Select from among ready processes in memory and allocate CPU execution time to one of them", "Select jobs from disk pool and load them into memory", "Manage swap space sizing", "Format disk sectors"], 0,
     "The short-term scheduler runs frequently (milliseconds) to decide which ready process in memory gets CPU execution time next.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the role of the long-term scheduler (job scheduler)?",
     ["Determine which programs are admitted into the system/memory for processing to regulate the degree of multiprogramming", "Switch registers during context switches", "Handle mouse and keyboard interrupts", "Manage L1 CPU cache lines"], 0,
     "The long-term scheduler controls the degree of multiprogramming by deciding when to admit new jobs into the ready queue.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is starvation in operating system scheduling?",
     ["A process being indefinitely denied necessary resources or CPU time due to continuous higher-priority competition", "Out of memory error during malloc()", "A thread crashing due to memory corruption", "Loss of disk storage space"], 0,
     "Starvation (indefinite blocking) occurs when a process is continually bypassed by the scheduler in favor of other processes.", "Easy", "Operating Systems", "Previous Exam"),
    ("Which technique is commonly used to prevent starvation in priority scheduling systems?",
     ["Aging (gradually increasing the priority of processes that wait in the system for a long time)", "Terminating long-running processes", "Disabling CPU interrupts", "Decreasing time slice quantum to zero"], 0,
     "Aging prevents starvation by incrementally raising the scheduling priority of jobs as they spend more time waiting.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a trap (software interrupt) in operating systems?",
     ["A software-generated interrupt caused by an error (e.g., division by zero) or a user-mode request for kernel services (system call)", "A malicious rootkit", "A memory leak that crashes the system", "A physical break on the motherboard"], 0,
     "A trap is a synchronous software interrupt triggered by an instruction error or explicit system call instruction (e.g., syscall / int 0x80).", "Medium", "Operating Systems", "Previous Exam"),

    # 61-70
    ("What is the primary role of the spooling (Simultaneous Peripheral Operations On-Line) mechanism?",
     ["Buffer I/O data onto disk so devices with differing speeds can operate asynchronously (e.g., print spooling)", "Encrypt files before transmission", "Compress RAM memory pages", "Manage virtual memory swap files"], 0,
     "Spooling queues data on disk storage, allowing fast processors to write data without waiting for slow peripherals like printers.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is thrashing caused by in multiprogrammed systems?",
     ["The degree of multiprogramming is too high, causing the sum of processes' working sets to exceed total physical RAM", "CPU clock speed running too fast", "Hard drive spinning backwards", "Too many network cables connected"], 0,
     "Thrashing occurs when too many processes compete for physical RAM and their aggregate working sets exceed available memory frames.", "Medium", "Operating Systems", "Previous Exam"),
    ("In UNIX, which system call is used to wait for a child process to change state or terminate?",
     ["wait() or waitpid()", "pause()", "sleep()", "halt()"], 0,
     "wait() and waitpid() block the calling parent process until one of its child processes exits or changes execution state.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the function of the chroot system call?",
     ["Changes the apparent root directory for the current running process and its children", "Changes file ownership permissions", "Reboots the operating system into recovery mode", "Formats the root hard drive"], 0,
     "chroot changes the apparent root filesystem directory (/), isolating the process from accessing files outside that path (chroot jail).", "Medium", "Operating Systems", "Previous Exam"),
    ("What distinguishes preemptive scheduling from non-preemptive scheduling?",
     ["In preemptive scheduling, the OS can forcibly interrupt and suspend a running process to allocate CPU to another process", "Non-preemptive scheduling never allows a process to finish", "Preemptive scheduling requires manual user intervention", "Non-preemptive scheduling uses multiple CPU cores only"], 0,
     "Preemptive scheduling allows the OS kernel to interrupt currently executing tasks when higher-priority events or time-slice expirations occur.", "Easy", "Operating Systems", "Previous Exam"),
    ("In page tables, what does the 'valid/invalid' bit signify?",
     ["Whether the page is currently loaded in physical RAM (valid) or not in RAM/illegal address (invalid)", "Whether the page has read permissions", "Whether the process has root privileges", "Whether the CPU clock is synchronized"], 0,
     "A 'valid' bit indicates the page is resident in physical memory; an 'invalid' bit indicates the page is on disk swap or outside the legal address space.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is a daemon in UNIX operating systems?",
     ["A background service process that runs continuously without direct control from an interactive terminal", "A computer virus targeting boot sectors", "A user account with restricted privileges", "A corrupted inode pointer"], 0,
     "A daemon is a background process (typically ending with 'd', like sshd or httpd) that handles system tasks without an attached terminal.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the function of the kill() system call in UNIX?",
     ["Send a specified signal to a process or process group", "Delete an executable file from disk", "Wipe the physical RAM", "Terminate the entire operating system"], 0,
     "kill(pid, sig) sends a designated software signal (such as SIGTERM, SIGKILL, SIGINT) to the targeted process.", "Easy", "Operating Systems", "Previous Exam"),
    ("What does the signal SIGKILL (signal 9) do?",
     ["Immediately and unconditionally terminates the process; it cannot be caught, blocked, or ignored", "Asks the process politely to save data", "Suspends the process into the background", "Increases process CPU priority"], 0,
     "SIGKILL forces immediate kernel termination of a process and cannot be caught, handled, or masked by user code.", "Medium", "Operating Systems", "Previous Exam"),
    ("What does the signal SIGTERM (signal 15) do?",
     ["Requests graceful termination of the process, allowing it to catch the signal and clean up resources before exiting", "Immediately powers down the server", "Freezes process threads permanently", "Dumps core memory to disk unconditionally"], 0,
     "SIGTERM is the standard termination request, permitting processes to intercept the signal, close open files, and terminate cleanly.", "Medium", "Operating Systems", "Previous Exam"),

    # 71-80
    ("What is the primary advantage of multi-level page tables over single-level page tables on modern 64-bit systems?",
     ["They avoid storing entire sparse page tables in memory by allocating second/third levels only for mapped address regions", "They eliminate all TLB misses", "They make address translation instantaneous", "They prevent page faults completely"], 0,
     "Multi-level paging saves massive RAM by allocating lower-level page tables only for virtual address regions that are actually in use.", "Hard", "Operating Systems", "Previous Exam"),
    ("What is the purpose of the init process (PID 1) in UNIX-based systems?",
     ["The first user-space process spawned by the kernel, serving as the ancestor of all processes and adopting orphaned processes", "The kernel debugger", "The swap space disk partition", "The BIOS firmware loader"], 0,
     "PID 1 (init or systemd) is the parent of all user processes, responsible for bringing up services and reaping orphaned processes.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a hard link in UNIX file systems?",
     ["A direct directory entry pointing to an existing inode number on the same filesystem", "A special file containing a path string to another file", "A shortcut pointing across network shares", "A physical wire linking two disk drives"], 0,
     "A hard link points directly to the file's inode; deleting the original filename does not delete the data until all hard links are removed.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a symbolic (soft) link in UNIX file systems?",
     ["A special file that contains the text path to another file or directory, capable of spanning across different filesystems", "An identical copy of the file's data blocks", "A direct pointer to a physical disk cylinder", "An unencrypted network socket"], 0,
     "A symbolic link is a separate file containing a pathname reference; if the target file is deleted, the symlink becomes broken (dangling).", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the main problem solved by the Readers-Writers synchronization problem formulation?",
     ["Allowing multiple readers to access shared data concurrently while ensuring exclusive access for writers", "Balancing CPU temperature during heavy reads", "Preventing disk drives from over-spinning", "Formatting flash drives"], 0,
     "The Readers-Writers problem coordinates concurrent read access without conflict while enforcing exclusive mutual exclusion for write operations.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is the function of the cron daemon in UNIX systems?",
     ["Execute scheduled commands or scripts automatically at specified recurring dates and times", "Monitor CPU temperature continuously", "Manage display monitors", "Synchronize time via atomic clocks"], 0,
     "Cron is a time-based job scheduler daemon that executes scheduled tasks (cron jobs) defined in crontab files.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the difference between synchronous and asynchronous I/O?",
     ["In synchronous I/O, the calling thread blocks until I/O finishes; in asynchronous I/O, the thread continues executing while I/O proceeds in background", "Synchronous I/O uses no memory buffers", "Asynchronous I/O cannot be used for disk files", "Synchronous I/O requires a GPU"], 0,
     "Synchronous I/O suspends the requesting process until data is ready; asynchronous I/O notifies the process via signal/callback upon completion.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a critical section in a concurrent program?",
     ["A segment of code where shared resources (such as shared variables or files) are accessed, requiring mutual exclusion", "A section of code that causes hardware crashes", "The bootstrap code in BIOS", "The root partition on disk"], 0,
     "A critical section is code that accesses shared data; only one process must execute in its critical section at any given time to avoid race conditions.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the bounded waiting requirement in the Critical Section problem?",
     ["There must be a bound on the number of times other processes can enter their critical sections after a process has requested entry", "Processes must terminate within 10 seconds", "Waiting time must be zero milliseconds", "The CPU must execute only one thread per second"], 0,
     "Bounded waiting guarantees that no process waits indefinitely (starves) to enter its critical section after making an entry request.", "Medium", "Operating Systems", "Previous Exam"),
    ("In memory management, what is a page?",
     ["A fixed-size block of virtual memory used as the unit of transfer between disk and main memory", "A printed document", "A contiguous sequence of physical cylinders on a disk", "A sector on a magnetic tape"], 0,
     "A page is a fixed-size contiguous block of virtual memory (typically 4 KB) mapped onto a physical page frame in RAM.", "Easy", "Operating Systems", "Previous Exam"),

    # 81-90
    ("In memory management, what is a frame (page frame)?",
     ["A fixed-size block of physical RAM memory identical in size to a virtual memory page", "A picture border on the desktop", "A network packet header", "A time slice allocated by the CPU scheduler"], 0,
     "A frame is a fixed-size block of physical memory that holds one virtual page.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is segmentation in memory management?",
     ["A memory management scheme that divides address space into variable-sized logical segments reflecting program modules (code, data, stack)", "Dividing memory into equal 4 KB chunks", "Splitting disk tracks into sectors", "Encrypting memory blocks"], 0,
     "Segmentation organizes memory into variable-sized logical units (e.g., functions, arrays, stack) rather than arbitrary fixed-size pages.", "Medium", "Operating Systems", "Previous Exam"),
    ("What happens when an operating system uses pure segmentation without paging?",
     ["It suffers from external fragmentation as segments of varying lengths are loaded and unloaded from memory", "It suffers from severe internal fragmentation", "It cannot support shared libraries", "Virtual memory cannot exceed 1 MB"], 0,
     "Pure segmentation allocates variable-length memory segments, leading to external fragmentation over time as gaps appear between segments.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is segmented paging (combining segmentation and paging)?",
     ["Each logical segment is divided into fixed-size pages, eliminating external fragmentation while preserving logical segmentation", "Paging without a TLB", "Using two hard drives for swap", "Allocating memory without an MMU"], 0,
     "Segmented paging paginates each logical segment, providing programmers with logical modularity while preventing external fragmentation.", "Hard", "Operating Systems", "Previous Exam"),
    ("What is the Ostrich Algorithm in deadlock handling?",
     ["Ignoring the possibility of deadlocks altogether on the premise that they occur rarely and prevention is too costly", "Terminating all running processes immediately", "Rebooting the server every hour", "Allocating unlimited virtual memory"], 0,
     "The Ostrich algorithm sticks its head in the sand: it ignores deadlocks, a practical trade-off used by general-purpose OSs like UNIX and Windows.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a monitor in concurrent programming?",
     ["A high-level synchronization construct that encapsulates shared variables and provides implicit mutual exclusion for its procedures", "A computer display screen", "A background network packet sniffer", "A hardware temperature gauge"], 0,
     "A monitor is an abstract data type containing shared data and procedures where compiler-generated locks guarantee that only one thread executes inside at a time.", "Medium", "Operating Systems", "Previous Exam"),
    ("What are condition variables inside a monitor used for?",
     ["Allowing threads to wait (block) until a specific condition becomes true, and signaling other threads when it changes", "Controlling screen resolution", "Checking CPU voltage levels", "Declaring variable data types"], 0,
     "Condition variables provide wait() and signal() primitives inside monitors, allowing threads to sleep until notified by another thread.", "Medium", "Operating Systems", "Previous Exam"),
    ("In UNIX, what does the umask command control?",
     ["Sets the default permission mask that restricts file permissions upon creation", "Changes the root password", "Sets network subnet mask", "Hides user processes from top"], 0,
     "umask specifies the file mode creation mask; bits set in umask are automatically stripped from permissions when new files are created.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the purpose of the top or htop utility in Linux?",
     ["Provide a dynamic, real-time view of running processes, CPU usage, memory consumption, and system load", "Edit system configuration files", "Test hard drive write speeds", "Compile C programs"], 0,
     "top/htop monitors running processes in real time, displaying CPU, memory, thread counts, and load averages.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the resident set size (RSS) of a process?",
     ["The portion of a process's memory currently held in physical RAM", "The total size of the executable file on disk", "The amount of virtual address space allocated", "The size of the process's swap file"], 0,
     "RSS measures the exact amount of physical memory (RAM) allocated and actively occupied by a process.", "Medium", "Operating Systems", "Previous Exam"),

    # 91-100
    ("What is the primary role of the Device Driver in an operating system?",
     ["Provide a standardized software interface between the operating system kernel and specific hardware peripheral controllers", "Assemble machine code from source", "Manage user logins and passwords", "Display graphical windows on screen"], 0,
     "A device driver translates generic OS I/O requests (like read/write) into device-specific commands understood by peripheral hardware controllers.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is direct I/O (raw I/O)?",
     ["I/O operations that bypass the operating system's page cache and transfer data directly between user buffer and storage device", "Connecting directly to a serial port", "Writing code without compiling", "Accessing memory without virtual addresses"], 0,
     "Direct I/O bypasses OS buffer caching, allowing high-performance applications like database engines to manage their own caching.", "Hard", "Operating Systems", "Previous Exam"),
    ("What is the Second-Chance (Clock) page replacement algorithm?",
     ["An approximation of LRU using a circular queue and a reference bit to give referenced pages a second chance before eviction", "An algorithm that runs every 2 hours", "An algorithm that replaces two pages at a time", "A backup algorithm if FIFO fails"], 0,
     "The clock algorithm inspects pages cyclically; if the reference bit is 1, it clears it to 0 and advances; if 0, the page is selected for replacement.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a load average on UNIX systems (displayed as 1, 5, and 15-minute averages)?",
     ["The average number of runnable processes either running on CPU or waiting in the ready/uninterruptible queue", "The percentage of memory consumed", "The network download speed in MB/s", "The average CPU operating temperature"], 0,
     "Load average represents the average count of processes actively executing or waiting in the runnable queue over 1, 5, and 15-minute intervals.", "Medium", "Operating Systems", "Previous Exam"),
    ("What is a reentrant function (thread-safe function)?",
     ["A function that can be interrupted and re-entered concurrently by multiple threads without corrupting execution state", "A function that calls itself recursively", "A function that restarts the computer", "A function with no parameters"], 0,
     "A reentrant function does not rely on shared or static mutable state, allowing multiple concurrent threads to safely execute it simultaneously.", "Medium", "Operating Systems", "Previous Exam"),
    ("What does the core dump file represent in operating systems?",
     ["A recorded snapshot of a process's memory address space and register state at the moment of an abnormal crash", "A backup of the operating system kernel", "A log of deleted user emails", "A corrupted hard drive sector table"], 0,
     "A core dump is a memory image recorded upon an unhandled fatal signal (e.g., SIGSEGV), used for post-mortem debugging with tools like gdb.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is the function of the select() or epoll() system call in asynchronous network servers?",
     ["Monitor multiple file descriptors concurrently to determine if any are ready for non-blocking reading or writing", "Select the fastest network interface", "Poll the CPU for clock interrupts", "Format network packets"], 0,
     "select() and epoll() provide I/O multiplexing, allowing a single event-loop thread to monitor thousands of network socket descriptors efficiently.", "Hard", "Operating Systems", "Previous Exam"),
    ("What is meant by the 'degree of multiprogramming'?",
     ["The number of active processes currently resident in memory", "The number of programming languages supported by the compiler", "The number of monitors connected to the system", "The number of threads per core"], 0,
     "The degree of multiprogramming is the total number of processes simultaneously residing in main memory.", "Easy", "Operating Systems", "Previous Exam"),
    ("What is a microcode update in modern operating systems?",
     ["A patch loaded into the CPU at boot time by the kernel to fix hardware errata and processor bugs (e.g., Spectre/Meltdown)", "A patch to the BIOS splash screen", "A script that speeds up Python programs", "A user-space driver update"], 0,
     "CPU microcode updates allow operating systems to apply processor vendor errata fixes to CPU instruction decoders during boot.", "Medium", "Operating Systems", "Previous Exam"),
    ("What does the 'uninterruptible sleep' (D state) in Linux process states indicate?",
     ["The process is waiting for a critical hardware event (typically disk I/O) and cannot be awakened even by SIGKILL until I/O finishes", "The process is paused by the user", "The process is running on the GPU", "The process has terminated successfully"], 0,
     "D state (Disk sleep / Uninterruptible sleep) indicates a process blocked in a kernel system call waiting for hardware I/O that cannot be interrupted by signals.", "Hard", "Operating Systems", "Previous Exam")
]

print(f"Total Part 2 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part2_data = []
for i, q in enumerate(questions):
    qid = f"p2-q{i+1}"
    part2_data.append({
        "id": qid,
        "part": 2,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part2.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_2_QUESTIONS: Question[] = ")
    json.dump(part2_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 2 successfully to src/data/parts/part2.ts")
