#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("In a 5-stage classic RISC pipeline (IF, ID, EX, MEM, WB), which hazard occurs when an instruction depends on the result of an earlier instruction that has not completed execution?",
     ["Structural hazard", "Data hazard", "Control hazard", "Branch hazard"], 1,
     "A data hazard occurs when execution depends on the outcome of previous instructions that are still progressing through the pipeline.", "Medium", "Computer Architecture", "Previous Exam"),
    ("Which CPU register holds the memory address of the next instruction to be fetched from main memory?",
     ["Instruction Register (IR)", "Memory Address Register (MAR)", "Program Counter (PC)", "Accumulator (AC)"], 2,
     "The Program Counter (PC) contains the address of the next instruction to be fetched from memory.", "Easy", "Computer Architecture", "Previous Exam"),
    ("In cache memory design, which write policy updates main memory only when a dirty cache block is replaced?",
     ["Write-through", "Write-back", "Write-allocate", "No-write-allocate"], 1,
     "Write-back updates main memory only when a modified (dirty) block is evicted from the cache.", "Hard", "Computer Architecture", "Previous Exam"),
    ("Which digital logic gate is classified as universal because any Boolean logic function can be constructed using it exclusively?",
     ["AND gate", "OR gate", "NAND gate", "XOR gate"], 2,
     "NAND and NOR gates are universal gates because they can be combined to implement AND, OR, and NOT functions.", "Easy", "Digital Logic", "Previous Exam"),
    ("What is the primary objective of data forwarding (operand bypassing) in pipelined processors?",
     ["Prevent branch mispredictions", "Resolve Read-After-Write (RAW) data hazards without inserting pipeline stalls", "Increase cache line size", "Double the clock frequency"], 1,
     "Data forwarding routes the output of the EX or MEM stage directly to subsequent stages needing the operand, avoiding stalls.", "Medium", "Computer Architecture", "Previous Exam"),
    ("How many select lines are required for a 16-to-1 multiplexer?",
     ["2", "3", "4", "8"], 2,
     "A 16-to-1 multiplexer requires n select lines where 2^n = 16, so n = 4 select lines.", "Medium", "Digital Logic", "Previous Exam"),
    ("In the IEEE 754 single-precision (32-bit) floating-point format, how many bits are allocated for the biased exponent?",
     ["7 bits", "8 bits", "11 bits", "23 bits"], 1,
     "IEEE 754 single-precision uses 1 bit for sign, 8 bits for exponent (with a bias of 127), and 23 bits for the mantissa.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the main architectural principle of RISC processors compared to CISC processors?",
     ["Variable-length complex instructions", "Uniform fixed-length instructions with load-store architecture", "Microcoded multi-cycle instructions", "Direct memory-to-memory arithmetic"], 1,
     "RISC systems prioritize simple, uniform instructions executed in single clock cycles using load-store operations.", "Easy", "Computer Architecture", "Previous Exam"),
    ("Which category of cache misses cannot be avoided even with an infinitely large cache?",
     ["Conflict miss", "Capacity miss", "Compulsory (Cold) miss", "Coherence miss"], 2,
     "Compulsory (cold) misses occur on the very first access to a block of data, regardless of cache size or associativity.", "Hard", "Computer Architecture", "Previous Exam"),
    ("In Boolean algebra, what is the simplified form of the expression X + X'Y?",
     ["X", "Y", "X + Y", "X'Y"], 2,
     "Using distributive simplification: X + X'Y = (X + X')(X + Y) = 1 * (X + Y) = X + Y.", "Medium", "Digital Logic", "Previous Exam"),
    
    # 11-20
    ("Which flip-flop resolves the undetermined/forbidden state of the SR latch when both inputs are asserted high?",
     ["T flip-flop", "JK flip-flop", "D latch", "Clocked SR latch"], 1,
     "The JK flip-flop toggles its output state when J=1 and K=1, eliminating the undefined SR condition.", "Medium", "Digital Logic", "Previous Exam"),
    ("In Direct Memory Access (DMA), what occurs during 'cycle stealing' mode?",
     ["DMA halts the CPU for the entire multi-megabyte transfer", "DMA acquires the system bus for one bus cycle at a time between CPU cycles", "The CPU controls every byte transfer", "Data is transmitted through the ALU"], 1,
     "Cycle stealing allows the DMA controller to interleave single-word bus transfers with CPU cycles without monopolizing the bus.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is the primary role of the Translation Lookaside Buffer (TLB)?",
     ["Cache instruction opcodes", "Cache recent virtual-to-physical address translations", "Store branch prediction histories", "Buffer disk read sectors"], 1,
     "The TLB is a high-speed associative hardware cache that speeds up virtual-to-physical page address translations.", "Hard", "Computer Architecture", "Previous Exam"),
    ("Which register in the CPU holds the data fetched from memory or data ready to be written to memory?",
     ["Memory Address Register (MAR)", "Memory Data Register (MDR)", "Instruction Register (IR)", "Program Status Word (PSW)"], 1,
     "The Memory Data Register (MDR), also called Memory Buffer Register (MBR), buffers data to or from the memory bus.", "Easy", "Computer Architecture", "Previous Exam"),
    ("Which addressing mode specifies the operand constant directly inside the instruction itself?",
     ["Direct addressing", "Indirect addressing", "Immediate addressing", "Indexed addressing"], 2,
     "In immediate addressing, the operand value is an explicit constant embedded within the instruction word.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What causes a control hazard (branch hazard) in a pipelined CPU?",
     ["Contention for the memory bus", "Delay in determining the branch outcome and target address", "A register RAW dependency", "Cache line replacement delay"], 1,
     "Control hazards arise because the pipeline must fetch the next instruction before conditional branch outcomes are evaluated.", "Medium", "Computer Architecture", "Previous Exam"),
    ("Which combinational circuit converts an n-bit input code into a maximum of 2^n unique output lines?",
     ["Encoder", "Decoder", "Multiplexer", "Comparator"], 1,
     "A binary decoder takes n input lines and asserts one of 2^n distinct output lines.", "Medium", "Digital Logic", "Previous Exam"),
    ("What is the effect of increasing cache block size on spatial locality and miss penalty?",
     ["Improves spatial locality initially, but excessively large blocks increase miss penalty", "Destroys spatial locality completely", "Decreases miss penalty under all conditions", "Has no effect on cache behavior"], 0,
     "Larger blocks fetch neighboring data (exploiting spatial locality), but take longer to transfer from RAM upon a miss.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In 2's complement binary representation, what is the negation of the 8-bit number 00101100 (44 in decimal)?",
     ["11010011", "11010100", "11010101", "00101101"], 1,
     "Inverting all bits yields 11010011; adding 1 gives 11010100 (-44 in 2's complement).", "Medium", "Computer Architecture", "Previous Exam"),
    ("Which cache architecture allows a memory block to be placed in any cache line without fixed index restrictions?",
     ["Direct-mapped cache", "2-way set-associative cache", "Fully associative cache", "Sector-mapped cache"], 2,
     "A fully associative cache enables any memory block to reside in any cache slot, maximizing hit rate at the expense of comparator hardware.", "Medium", "Computer Architecture", "Previous Exam"),

    # 21-30
    ("What does Amdahl's Law calculate in computer engineering?",
     ["The maximum potential speedup of a system when only a portion of the task is accelerated", "The clock frequency limit of silicon", "The bandwidth of an optical fiber", "The probability of soft errors in DRAM"], 0,
     "Amdahl's Law formulates the theoretical limit of execution speedup when a fraction of a workload is parallelized.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is a superscalar processor?",
     ["A processor with a clock frequency exceeding 5 GHz", "A CPU capable of issuing and executing multiple independent instructions per clock cycle", "A CPU with only one register", "A processor with an optical ALU"], 1,
     "Superscalar processors have multiple parallel execution units to dispatch and retire multiple instructions per clock cycle.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the function of the Instruction Register (IR)?",
     ["Store the memory address of the next instruction", "Hold the instruction currently being decoded and executed", "Count the number of clock pulses", "Save return addresses of function calls"], 1,
     "The IR holds the instruction word fetched from memory while the control unit decodes its opcode and operands.", "Easy", "Computer Architecture", "Previous Exam"),
    ("Which digital component is formed by cascading an inverter directly after an OR gate?",
     ["NOR gate", "NAND gate", "XOR gate", "XNOR gate"], 0,
     "An OR gate followed by an inverter (NOT gate) produces the NOR logic function.", "Easy", "Digital Logic", "Previous Exam"),
    ("What is the setup time (t_setup) requirement for a clocked flip-flop?",
     ["The minimum time the input data must remain stable before the triggering clock edge", "The time data must stay stable after the clock edge", "The delay between clock edge and output transition", "The total duration of the clock pulse"], 0,
     "Setup time is the minimum duration the data signal must be held stable prior to the active clock transition.", "Medium", "Digital Logic", "Previous Exam"),
    ("Which high-speed bus traditionally links the CPU directly to the Northbridge/memory controller?",
     ["Front-Side Bus (FSB) / System Bus", "PCI bus", "SATA bus", "LPC bus"], 0,
     "The Front-Side Bus (or modern direct interconnect like QPI/Infinity Fabric) interfaces the processor core directly to memory controllers.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In Booth's multiplication algorithm, what operation is performed when the current bit pair (Q_i, Q_{i-1}) is '10'?",
     ["Add multiplicand to accumulator and shift", "Subtract multiplicand from accumulator and shift", "Shift right only with no arithmetic", "Double the multiplicand"], 1,
     "A '10' bit pattern indicates the end of a string of ones, requiring subtraction of the multiplicand followed by an arithmetic shift.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is the primary advantage of a Carry-Lookahead Adder (CLA) over a Ripple-Carry Adder (RCA)?",
     ["Fewer logic gates and lower power", "Carry propagation delay is significantly reduced through parallel carry generation", "Zero propagation delay", "Simultaneous division capability"], 1,
     "CLA calculates carry signals in parallel using generate and propagate logic, bypassing serial ripple delays.", "Hard", "Computer Architecture", "Previous Exam"),
    ("In Very Long Instruction Word (VLIW) architectures, which component is responsible for identifying instruction parallelism?",
     ["Hardware dynamic dispatch logic", "The static compiler during code generation", "The operating system dispatcher", "The branch target buffer"], 1,
     "VLIW relies on the optimizing compiler to schedule independent operations into single wide instruction packets.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What is the primary function of a Branch Target Buffer (BTB)?",
     ["Cache the predicted target address of branch instructions to avoid pipeline bubbles", "Store return addresses of recursive calls", "Buffer memory writes to L3 cache", "Queue external I/O interrupts"], 0,
     "A BTB stores branch instruction addresses and their predicted target addresses to eliminate fetch delays.", "Hard", "Computer Architecture", "Previous Exam"),

    # 31-40
    ("Which memory technology retains stored bits using bistable latches without requiring periodic electrical refreshes?",
     ["DRAM", "SRAM", "SDRAM", "Flash NAND"], 1,
     "Static RAM (SRAM) uses 6-transistor cross-coupled inverters to store bits stably without refresh cycles as long as power remains.", "Medium", "Computer Architecture", "Previous Exam"),
    ("How many Hamming parity bits are required to provide single-bit error detection and correction for 4 bits of data?",
     ["2 bits", "3 bits", "4 bits", "5 bits"], 1,
     "The formula 2^p >= p + d + 1 with d=4 gives 2^3 = 8 >= 3 + 4 + 1 = 8, so exactly 3 parity bits are required.", "Hard", "Computer Architecture", "Previous Exam"),
    ("How many 512 x 8 RAM chips are required to build a 2K x 16 memory module?",
     ["4 chips", "6 chips", "8 chips", "16 chips"], 2,
     "Depth: 2K / 512 = 4 banks. Width: 16 / 8 = 2 chips per bank. Total = 4 * 2 = 8 chips.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In memory interleaving, what is the architectural advantage of low-order interleaving?",
     ["Consecutive memory addresses are spread across different memory banks, enabling concurrent access", "RAM speed is reduced to save power", "Eliminates the need for cache tags", "Requires zero address decoding logic"], 0,
     "Low-order interleaving places sequential memory addresses across alternating memory banks to allow simultaneous pipelined access.", "Hard", "Computer Architecture", "Previous Exam"),
    ("Under what condition does the race-around condition occur in a level-triggered JK flip-flop?",
     ["When J=0 and K=0 with clock active", "When J=1, K=1, and the clock pulse duration is longer than the flip-flop propagation delay", "When power supply voltage fluctuates", "When J and K inputs are floating"], 1,
     "In level-triggered JK flip-flops with J=K=1, if the clock remains high longer than the gate propagation delay, the output toggles unpredictably.", "Hard", "Digital Logic", "Previous Exam"),
    ("What is the primary role of the MESI protocol in symmetric multiprocessing (SMP)?",
     ["Maintain cache coherence across private CPU caches sharing main memory", "Manage virtual memory paging to disk", "Encrypt bus transactions across PCI lanes", "Schedule multi-threaded processes"], 0,
     "The MESI (Modified, Exclusive, Shared, Invalid) protocol enforces cache coherence across multiple processor caches.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What does the fan-out metric of a logic gate represent?",
     ["The maximum number of standard input loads that the gate's output can drive reliably", "The number of inputs connected to the gate", "The thermal dissipation in milliwatts", "The switching frequency of the gate"], 0,
     "Fan-out is the maximum number of digital inputs that can be connected to the gate output without degrading voltage levels.", "Medium", "Digital Logic", "Previous Exam"),
    ("Which CPU register points to the topmost allocated frame on the execution call stack?",
     ["Program Counter (PC)", "Instruction Register (IR)", "Stack Pointer (SP)", "Link Register (LR)"], 2,
     "The Stack Pointer (SP) points to the last allocated memory address on the runtime call stack.", "Easy", "Computer Architecture", "Previous Exam"),
    ("How does the Harvard architecture differ fundamentally from the von Neumann architecture?",
     ["It uses separate physical memory and buses for instructions and data", "It has no Arithmetic Logic Unit", "It requires all instructions to be 8 bits", "It cannot execute conditional jumps"], 0,
     "Harvard architecture maintains physically distinct memories and signal pathways for instructions and operands.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In a 4-variable Karnaugh Map (K-map), grouping 8 adjacent cells simplifies how many Boolean variables?",
     ["1 variable", "2 variables", "3 variables", "4 variables"], 2,
     "Grouping 2^m cells eliminates m variables. For 8 cells (2^3), exactly 3 variables are eliminated.", "Medium", "Digital Logic", "Previous Exam"),

    # 41-50
    ("Which addressing mode is specifically designed to facilitate position-independent code (PIC)?",
     ["Absolute addressing", "PC-relative addressing", "Direct addressing", "Immediate addressing"], 1,
     "PC-relative addressing computes branch and data locations as an offset from the Program Counter, allowing code relocation anywhere in memory.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In computer organization, what is an atomic micro-operation?",
     ["A basic hardware operation executed within a single clock cycle", "A high-level language function", "An operating system daemon", "A compiler optimization flag"], 0,
     "A micro-operation is an elementary physical operation (e.g., register transfer, ALU addition) performed in a single clock cycle.", "Medium", "Computer Architecture", "Previous Exam"),
    ("In Flynn's taxonomy of computer architectures, what does SIMD stand for?",
     ["Single Instruction Multiple Data", "Synchronous Instruction Memory Device", "Sequential Input Multiplexed Division", "Single Interface Multi Driver"], 0,
     "SIMD (Single Instruction, Multiple Data) executes one instruction simultaneously across vector data streams.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What problem does a Master-Slave flip-flop configuration eliminate in sequential digital circuits?",
     ["Excessive propagation delay", "Race-around condition occurring in level-triggered flip-flops", "Power dissipation", "The requirement of clock pulses"], 1,
     "Master-Slave flip-flops isolate input sampling (master) from output updating (slave) to eliminate race-around toggling.", "Medium", "Digital Logic", "Previous Exam"),
    ("Which bus arbitration scheme determines bus ownership through a serial chain passing from device to device?",
     ["Centralized parallel arbitration", "Daisy-chaining", "Independent request arbitration", "Time-sliced round robin"], 1,
     "In daisy-chain arbitration, the grant signal propagates sequentially through devices in descending priority order.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What are the primary operational tasks executed by the Arithmetic Logic Unit (ALU)?",
     ["Address translation and page fault handling", "Integer arithmetic operations (addition, subtraction) and bitwise logical operations", "Reading sectors from secondary magnetic disks", "Scheduling user processes in memory"], 1,
     "The ALU executes fundamental arithmetic (add, subtract) and logical (AND, OR, NOT, XOR, shift) operations.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What characterizes memory-mapped I/O in computer architecture?",
     ["I/O device registers share the same address space as RAM and are accessed using standard memory load/store instructions", "I/O devices use a distinct address space requiring dedicated IN and OUT instructions", "I/O requires physical switches on the motherboard", "Memory is mapped directly onto hard drive sectors"], 0,
     "In memory-mapped I/O, device registers are assigned regular memory addresses, allowing standard memory instructions to control peripherals.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the purpose of an instruction prefetch buffer in CPU hardware?",
     ["Store completed calculation results before cache write-back", "Fetch upcoming sequential instructions from memory ahead of time to hide latency", "Queue interrupt requests from external devices", "Maintain virtual-to-physical address mappings"], 1,
     "Prefetch buffers load instructions from memory into a fast internal queue before the execution engine demands them.", "Medium", "Computer Architecture", "Previous Exam"),
    ("Which CPU subsystem generates timing and control signals to sequence all internal processor operations?",
     ["Arithmetic Logic Unit (ALU)", "Control Unit (CU)", "Memory Controller", "Floating-Point Unit (FPU)"], 1,
     "The Control Unit (CU) orchestrates CPU operations by decoding instructions and generating hardware control pulses.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the main advantage of dynamic branch prediction over static branch prediction?",
     ["It adapts branch decisions at runtime based on past execution history and branch pattern tables", "It eliminates all branch penalties unconditionally", "It requires zero hardware transistors", "It guarantees 100% prediction accuracy"], 0,
     "Dynamic branch prediction uses runtime history counters to adjust predictions dynamically based on execution trends.", "Medium", "Computer Architecture", "Previous Exam"),

    # 51-60
    ("What is gate propagation delay in digital electronics?",
     ["The physical time interval required for a change at the input to cause a corresponding change at the output", "The time a signal takes to travel through a 1-meter wire", "The duration of one full clock cycle", "The time taken to discharge a decoupling capacitor"], 0,
     "Propagation delay is the physical latency between an input transition and the stabilized output transition of a gate.", "Easy", "Digital Logic", "Previous Exam"),
    ("Which type of Read-Only Memory can be erased by exposing the chip to ultraviolet (UV) light through a quartz window?",
     ["PROM", "EPROM", "EEPROM", "Flash memory"], 1,
     "EPROM (Erasable Programmable ROM) is erased by shining intense UV light through its quartz window to neutralize floating gates.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What error detection capability is provided by a single parity bit appended to a data word?",
     ["Correction of single-bit errors", "Detection of any odd number of bit errors (typically single-bit error detection)", "Detection of 2-bit burst errors with certainty", "Encryption of data against tampering"], 1,
     "A parity bit detects odd numbers of bit errors (e.g., single-bit flips), but cannot detect even numbers of errors or correct them.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is out-of-order execution (OoOE) designed to accomplish in high-performance processors?",
     ["Execute ready instructions ahead of earlier stalled instructions to maximize hardware resource utilization", "Decrease the physical number of registers required", "Prevent branch mispredictions entirely", "Eliminate the need for cache memory"], 0,
     "OoOE reorders instruction execution dynamically to prevent stalls caused by long-latency cache misses or dependencies.", "Hard", "Computer Architecture", "Previous Exam"),
    ("In digital hardware design, what is the 'critical path'?",
     ["The path with the highest current draw", "The combinational path with the longest total propagation delay between sequential registers", "The shortest wire connection on the motherboard", "The power supply rail providing 3.3V"], 1,
     "The critical path is the longest delay path between sequential elements, determining the maximum clock frequency of the circuit.", "Medium", "Digital Logic", "Previous Exam"),
    ("Which architectural technique eliminates false data dependencies (Write-After-Read and Write-After-Write) in out-of-order CPUs?",
     ["Branch prediction", "Register renaming", "Cache write-through", "Instruction prefetching"], 1,
     "Register renaming maps architectural register names to a larger pool of physical registers, resolving WAR and WAW false hazards.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What output state does a tri-state buffer produce when its enable control line is inactive?",
     ["Logic 0 (Ground)", "Logic 1 (Vdd)", "High impedance (Hi-Z)", "Continuous oscillation"], 2,
     "When disabled, a tri-state buffer enters a high-impedance (Hi-Z) state, electrically disconnecting its output from the shared bus.", "Medium", "Digital Logic", "Previous Exam"),
    ("In processor performance evaluation, what does the CPI metric stand for?",
     ["Cycles Per Instruction", "Central Processing Interface", "Clock Pulses per Interconnect", "Core Processing Index"], 0,
     "CPI (Cycles Per Instruction) measures the average number of clock cycles required to execute an instruction.", "Easy", "Computer Architecture", "Previous Exam"),
    ("Which combinational circuit adds two 1-bit binary inputs, producing Sum and Carry outputs without accepting an incoming carry bit?",
     ["Half adder", "Full adder", "Carry-lookahead adder", "BCD adder"], 0,
     "A half adder performs 1-bit addition of two operands, generating Sum (A XOR B) and Carry (A AND B), with no Carry-in.", "Easy", "Digital Logic", "Previous Exam"),
    ("What is the primary role of the Memory Management Unit (MMU)?",
     ["Perform hardware arithmetic operations on matrices", "Translate virtual addresses into physical addresses and enforce access protection", "Manage hard drive partitioning", "Encode video frames for display"], 1,
     "The MMU performs virtual-to-physical address translation and verifies memory segment access permissions.", "Medium", "Computer Architecture", "Previous Exam"),

    # 61-70
    ("In multi-processor architectures, what characterizes Non-Uniform Memory Access (NUMA)?",
     ["Memory access latency varies depending on whether the targeted memory bank is local or attached to a remote CPU socket", "All CPUs experience identical access latency to any RAM location", "Memory blocks are volatile and refreshed non-uniformly", "Only one CPU is permitted to access RAM at a time"], 0,
     "In NUMA systems, accessing memory local to a processor's socket is faster than accessing memory attached to other sockets.", "Hard", "Computer Architecture", "Previous Exam"),
    ("Which digital circuit takes 2^n input lines and asserts an n-bit binary code representing the active line?",
     ["Binary Decoder", "Priority Encoder", "Multiplexer", "Demultiplexer"], 1,
     "An encoder produces an n-bit binary code corresponding to which of its 2^n input lines is currently active.", "Medium", "Digital Logic", "Previous Exam"),
    ("What is the primary function of a hardware shift register?",
     ["Multiply numbers by zero", "Store and shift binary bits sequentially to the left or right on successive clock pulses", "Decode assembly opcodes into control words", "Generate system clock square waves"], 1,
     "A shift register is a chain of flip-flops that shifts its stored bits by one position per clock transition.", "Easy", "Digital Logic", "Previous Exam"),
    ("What is an interrupt vector in computer architecture?",
     ["A geometric line on a circuit board", "The memory address of the Interrupt Service Routine (ISR) designated to handle a specific interrupt", "The priority number of a hardware fault", "A CPU register storing instruction counts"], 1,
     "An interrupt vector is the memory address pointing to the handler routine (ISR) for a designated interrupt.", "Medium", "Computer Architecture", "Previous Exam"),
    ("Which IEEE standard specifies wired Ethernet networking at the physical and data link layers?",
     ["IEEE 802.3", "IEEE 802.11", "IEEE 802.15", "IEEE 754"], 0,
     "IEEE 802.3 governs wired Ethernet network standards and media specifications.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What distinguishes a synchronous counter from an asynchronous (ripple) counter?",
     ["In a synchronous counter, all flip-flops are clocked simultaneously by a common clock signal", "In a synchronous counter, each stage is clocked by the output of the preceding stage", "Synchronous counters do not require power", "Synchronous counters can only count down"], 0,
     "Synchronous counters connect the master clock line directly to every flip-flop, ensuring simultaneous state transitions.", "Medium", "Digital Logic", "Previous Exam"),
    ("What does pipeline depth denote in CPU microarchitecture?",
     ["The total physical number of distinct sequential stages through which an instruction passes", "The length of the data bus in centimeters", "The size of the L2 cache in megabytes", "The number of core execution threads"], 0,
     "Pipeline depth is the number of sequential stages an instruction traverses from fetch to retirement.", "Easy", "Computer Architecture", "Previous Exam"),
    ("How is the negative equivalent of a two's complement integer computed?",
     ["Inverting every bit and adding 1 to the least significant bit", "Inverting every bit without adding anything", "Shifting all bits left by one position", "Setting the sign bit to 1 while leaving other bits unchanged"], 0,
     "Two's complement negation is accomplished by bitwise NOT followed by adding 1.", "Easy", "Computer Architecture", "Previous Exam"),
    ("Which semiconductor logic technology is predominantly chosen for modern processors due to its near-zero static power consumption?",
     ["Transistor-Transistor Logic (TTL)", "Emitter-Coupled Logic (ECL)", "Complementary Metal-Oxide-Semiconductor (CMOS)", "Resistor-Transistor Logic (RTL)"], 2,
     "CMOS consumes negligible static power because its complementary pMOS/nMOS pairs are never simultaneously on in steady states.", "Medium", "Digital Logic", "Previous Exam"),
    ("What is the function of a snooping cache controller on a shared memory bus?",
     ["Monitoring bus memory transactions to invalidate or update outdated cached blocks", "Logging user keystrokes for surveillance", "Inspecting network packets for malware", "Compressing RAM contents in the background"], 0,
     "Snooping cache controllers monitor bus transactions to maintain cache consistency across multi-core processors.", "Hard", "Computer Architecture", "Previous Exam"),

    # 71-80
    ("What was the original purpose of a branch delay slot in early RISC architectures (like MIPS)?",
     ["Executing the instruction immediately following a branch unconditionally while the branch target was fetched", "Preventing interrupts from executing", "Buffering branch history tables in RAM", "Holding return values from system calls"], 0,
     "Branch delay slots allowed the instruction immediately following the branch to execute, hiding the branch target fetch latency.", "Hard", "Computer Architecture", "Previous Exam"),
    ("What was the primary function of the Accumulator register in classic CPU designs?",
     ["Implicitly store one operand and the result of arithmetic and logic computations", "Store operating system kernel page directories", "Hold interrupt request flags", "Track program execution time"], 0,
     "The Accumulator (AC) is a register where arithmetic and logic results are automatically accumulated.", "Easy", "Computer Architecture", "Previous Exam"),
    ("How does an asynchronous bus coordinate data transfers without a central shared clock?",
     ["By using two-way or four-way request and acknowledge handshaking protocol lines", "By relying on GPS time synchronization", "By transmitting continuously at fixed baud rates", "By using optical fiber links"], 0,
     "Asynchronous buses use handshaking control signals (REQ and ACK) to coordinate transfers between sender and receiver.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the basic physical storage cell composition of Dynamic RAM (DRAM)?",
     ["One transistor and one capacitor (1T-1C)", "Six cross-coupled transistors (6T)", "Two diodes and a resistor", "A magnetic toroidal ring"], 0,
     "DRAM stores each data bit as an electrical charge in a capacitor accessed via a single MOSFET (1T-1C structure).", "Medium", "Computer Architecture", "Previous Exam"),
    ("Which unit is standard for expressing processor clock frequencies in modern desktop computing?",
     ["Gigahertz (GHz)", "Megabytes per second (MB/s)", "Nanoseconds (ns)", "MFLOPS"], 0,
     "Processor clock speed is standardly measured in Gigahertz (GHz), denoting billions of clock cycles per second.", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the function of a Demultiplexer (DEMUX)?",
     ["Route data from a single input line onto one of several output lines based on select lines", "Combine several input signals onto a single wire", "Perform hardware multiplication", "Store data during clock cycles"], 0,
     "A DEMUX directs a single input channel to one of 2^n output channels determined by n selection control bits.", "Easy", "Digital Logic", "Previous Exam"),
    ("According to De Morgan's theorem, what is the equivalent of (A + B)'?",
     ["A' . B'", "A' + B'", "A . B", "(A . B)'"], 0,
     "De Morgan's theorem states: (A + B)' = A' . B' (the complement of an OR is the AND of the complements).", "Easy", "Digital Logic", "Previous Exam"),
    ("What does instruction-level parallelism (ILP) mean?",
     ["Executing multiple instructions from a single program thread simultaneously in hardware", "Running multiple operating systems on virtual machines", "Distributing jobs across internet servers", "Transferring packets across routers"], 0,
     "ILP refers to CPU hardware capabilities (like pipelining and superscalar execution) that execute multiple instructions concurrently.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What distinguishes a separate L1 instruction cache and L1 data cache (split Harvard L1)?",
     ["Allows simultaneous instruction fetching and data memory access without structural hazards", "Doubles total physical RAM capacity", "Prevents memory from ever being written", "Eliminates cache tag checking"], 0,
     "Split L1 caches provide independent pathways, enabling concurrent instruction fetch and memory load/store operations.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is an instruction opcode?",
     ["The portion of a machine instruction specifying the operation to be performed", "The memory address where the operand is stored", "The line number in source code", "The register holding the result"], 0,
     "The opcode (operation code) defines the CPU operation (such as ADD, SUB, JUMP, LOAD) to be executed.", "Easy", "Computer Architecture", "Previous Exam"),

    # 81-90
    ("What does the byte ordering term 'little-endian' mean?",
     ["The least significant byte is stored at the lowest memory address", "The most significant byte is stored at the lowest memory address", "Bits within a byte are inverted", "Data is compressed using Huffman encoding"], 0,
     "Little-endian systems place the least significant byte (LSB) at the lowest numerical byte address.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is 'register spilling' during program compilation and execution?",
     ["Storing register variables onto the memory stack when all hardware registers are occupied", "Electrical short circuit inside the register file", "Accidental overwriting of registers due to power surge", "Duplicating register contents into cache"], 0,
     "Register spilling occurs when the compiler has more active variables than CPU registers and must save some to memory.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the function of a barrel shifter in a CPU datapath?",
     ["Shift or rotate a data word by an arbitrary number of bit positions within a single clock cycle", "Spin hard drive platters at variable speeds", "Buffer interrupt requests from peripherals", "Convert floating-point numbers to integers"], 0,
     "A barrel shifter is a combinational circuit that shifts data by any specified number of bits in one clock cycle.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the dual of the Boolean algebraic expression A . (B + C) = (A . B) + (A . C)?",
     ["A + (B . C) = (A + B) . (A + C)", "A . (B . C) = A + B + C", "A' . (B' + C') = A' + B'", "A + B + C = 1"], 0,
     "The dual is formed by swapping AND with OR, and OR with AND: A + (B . C) = (A + B) . (A + C).", "Medium", "Digital Logic", "Previous Exam"),
    ("What does the term Instruction Set Architecture (ISA) describe?",
     ["The abstract programmer-visible specification of instructions, registers, and memory models of a CPU", "The microscopic semiconductor lithography layout", "The brand of the motherboard chipset", "The BIOS configuration utility"], 0,
     "The ISA is the conceptual software-hardware interface defining instructions, registers, and memory addressing modes.", "Easy", "Computer Architecture", "Previous Exam"),
    ("Why must flash memory erase operations be conducted in blocks rather than single bytes?",
     ["Due to the physical architecture where floating-gate transistors share common substrate erase lines", "To comply with software copyright laws", "Because bytes are too small to receive electric charge", "To prevent overheating of the CPU"], 0,
     "Flash memory can be read and programmed in words/bytes, but block architecture requires erasing entire multi-kilobyte sectors at once.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the duty cycle of a symmetric square-wave system clock?",
     ["50%", "25%", "75%", "100%"], 0,
     "A symmetric square wave spends equal time high and low, giving a 50% duty cycle.", "Easy", "Digital Logic", "Previous Exam"),
    ("What is an edge-triggered flip-flop?",
     ["A bistable multivibrator that changes state only on the rising or falling voltage transition of the clock", "A gate that switches continuously whenever power is applied", "An unclocked combinational latch", "A memory buffer that requires manual reset"], 0,
     "Edge-triggered flip-flops sample input data and update outputs strictly during the clock signal voltage transition.", "Easy", "Digital Logic", "Previous Exam"),
    ("Which instruction format requires zero explicit memory operand addresses because it operates on a stack?",
     ["Zero-address instruction format", "One-address instruction format", "Two-address instruction format", "Three-address instruction format"], 0,
     "Zero-address instructions implicitly pop their operands from and push results onto the top of the execution stack.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the primary role of a bus transceiver?",
     ["Facilitate bidirectional data transfer between two buses with high-impedance isolation capability", "Amplify radio frequencies in wireless networks", "Convert optical signals to electrical audio", "Generate system clock signals"], 0,
     "A bus transceiver allows bidirectional signal communication between buses and provides high-impedance isolation when disabled.", "Medium", "Digital Logic", "Previous Exam"),

    # 91-100
    ("What is the principle of temporal locality in memory hierarchies?",
     ["Data accessed recently is highly likely to be accessed again in the near future", "Data stored in adjacent memory addresses will be accessed soon", "Memory access speed increases with temperature", "Instruction execution speed depends on clock time"], 0,
     "Temporal locality states that memory locations accessed recently are likely to be referenced again soon (e.g., in loops).", "Easy", "Computer Architecture", "Previous Exam"),
    ("What is the principle of spatial locality in memory hierarchies?",
     ["Data items with memory addresses near recently accessed data are likely to be accessed soon", "Data items accessed recently will be accessed repeatedly", "Data stored in the cloud travels faster", "Memory addresses are distributed uniformly"], 0,
     "Spatial locality states that when an address is accessed, nearby contiguous addresses are likely to be referenced shortly (e.g., array traversal).", "Easy", "Computer Architecture", "Previous Exam"),
    ("Which hardware hazard arises when two instructions need the same hardware resource simultaneously?",
     ["Structural hazard", "Data hazard", "Control hazard", "Branch penalty"], 0,
     "Structural hazards occur when hardware resource conflicts prevent concurrent execution of pipeline stages.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is an asynchronous interrupt in processor terminology?",
     ["An interrupt caused by an external hardware event independent of instruction execution (e.g., timer, I/O)", "A trap caused by dividing by zero", "An invalid opcode exception", "A software system call"], 0,
     "Asynchronous interrupts are triggered by external hardware events (such as disk I/O completion or timer ticks) independent of the CPU clock.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is a synchronous interrupt (trap or exception)?",
     ["An event caused directly by the execution of the current instruction (e.g., divide by zero, page fault)", "An interrupt triggered by a network packet arrival", "A keyboard keypress signal", "A hardware cooling fan alert"], 0,
     "Synchronous interrupts (traps/exceptions) occur synchronously with CPU instruction execution when conditions like page faults or division errors occur.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is microprogramming in CPU control unit design?",
     ["A method where control signals are generated by executing elementary microinstructions stored in a control ROM", "Writing assembly language programs", "Developing firmware for microcontrollers", "Pipelining high-level language loops"], 0,
     "Microprogrammed control units decode instructions by sequencing micro-operations retrieved from an internal control memory (ROM).", "Hard", "Computer Architecture", "Previous Exam"),
    ("What distinguishes hardwired control units from microprogrammed control units?",
     ["Hardwired units use fixed combinational logic gates for faster execution speed, whereas microprogrammed units use ROM tables for flexibility", "Hardwired units are slower and require more memory", "Microprogrammed units cannot execute jumps", "Hardwired units cannot be used in RISC CPUs"], 0,
     "Hardwired control units generate control signals directly through combinational logic for maximum speed, though they are harder to modify.", "Hard", "Computer Architecture", "Previous Exam"),
    ("In a direct-mapped cache, how is the cache line index determined from a memory address?",
     ["By taking address bits modulo the total number of cache lines", "By performing a full associative search across all tags", "By selecting a random number", "By looking up the page table in RAM"], 0,
     "In direct-mapped caches, a specific bit field in the memory address directly identifies the single cache line where the block must map.", "Medium", "Computer Architecture", "Previous Exam"),
    ("What is the primary role of the Status Register (Flags Register / PSW)?",
     ["Record condition codes resulting from arithmetic/logic operations (Zero, Carry, Overflow, Sign)", "Store the memory address of the next instruction", "Count the number of clock pulses", "Hold the memory buffer data"], 0,
     "The Status Register records condition flags (such as Zero flag Z, Carry flag C, Sign flag S, Overflow flag V) for conditional branching.", "Easy", "Computer Architecture", "Previous Exam"),
    ("In digital logic, how many minterms exist for a Boolean function with 4 input variables?",
     ["16", "8", "4", "32"], 0,
     "A function with n Boolean variables has 2^n possible minterms. For n=4, 2^4 = 16 minterms exist.", "Easy", "Digital Logic", "Previous Exam")
]

print(f"Total Part 1 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part1_data = []
for i, q in enumerate(questions):
    qid = f"p1-q{i+1}"
    part1_data.append({
        "id": qid,
        "part": 1,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part1.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_1_QUESTIONS: Question[] = ")
    json.dump(part1_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 1 successfully to src/data/parts/part1.ts")
