#!/usr/bin/env python3
import json, os

questions = [
    # 1-10
    ("In relational database design, what is Boyce-Codd Normal Form (BCNF)?",
     ["A relation where every non-prime attribute is partially dependent on the primary key", "A relation where for every functional dependency X -> Y, X is a superkey", "A relation with no multi-valued attributes", "A relation where tables contain at most 10 columns"], 1,
     "BCNF is a stricter version of 3NF requiring that for every non-trivial functional dependency X -> Y, the determinant X must be a candidate key (superkey).", "Medium", "Databases", "Previous Exam"),
    ("Which of the following ACID transaction properties guarantees that once a transaction has committed, its changes will never be lost, even in the event of an immediate power outage or system crash?",
     ["Atomicity", "Consistency", "Isolation", "Durability"], 3,
     "Durability guarantees that the recorded effects of a committed transaction survive hardware and software crashes, typically enforced via Write-Ahead Logging (WAL).", "Easy", "Databases", "Previous Exam"),
    ("What is the primary difference between a B-Tree and a B+ Tree index in relational database engines?",
     ["B-Trees do not allow duplicate values, while B+ Trees do", "In a B+ Tree, all data record pointers reside strictly in the leaf nodes, and leaf nodes are linked sequentially for efficient range scans", "B-Trees are stored in RAM, whereas B+ Trees are stored on tape", "B+ Trees have variable tree heights"], 1,
     "B+ Trees store data records exclusively in leaf nodes linked as a doubly-linked list, optimizing sequential range queries and keeping non-leaf nodes small.", "Medium", "Databases", "Previous Exam"),
    ("Which SQL clause is used to filter records resulting from an aggregate function (e.g., COUNT, AVG) after GROUP BY grouping has occurred?",
     ["WHERE", "HAVING", "FILTER BY", "ORDER BY"], 1,
     "WHERE filters individual rows before grouping occurs; HAVING filters grouped rows after aggregation.", "Easy", "SQL", "Previous Exam"),
    ("What concurrency phenomenon occurs when Transaction T1 reads uncommitted data written by Transaction T2, and Transaction T2 subsequently rolls back?",
     ["Lost Update", "Dirty Read", "Non-Repeatable Read", "Phantom Read"], 1,
     "A Dirty Read occurs when a transaction reads modifications made by another uncommitted transaction that ultimately aborts.", "Medium", "Databases", "Previous Exam"),
    ("Which ANSI SQL transaction isolation level prevents Dirty Reads and Non-Repeatable Reads, but still allows Phantom Reads?",
     ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"], 2,
     "Repeatable Read prevents dirty reads and fuzzy non-repeatable reads by locking read rows, but phantom reads (new rows inserted by others) can still appear unless Serializable is used.", "Hard", "Databases", "Previous Exam"),
    ("In relational algebra, which operator computes the Cartesian product of two relations R and S?",
     ["Selection (sigma)", "Projection (pi)", "Cross Product (times)", "Natural Join (bowtie)"], 2,
     "The Cartesian Product (R x S) combines every tuple of relation R with every tuple of relation S, producing degree(R) + degree(S) attributes.", "Easy", "Databases", "Previous Exam"),
    ("What is a Foreign Key constraint designed to enforce in a relational schema?",
     ["Entity integrity", "Referential integrity", "Domain integrity", "Column uniqueness"], 1,
     "A foreign key enforces referential integrity, ensuring that values in the referencing table exist as primary key values in the referenced table.", "Easy", "Databases", "Previous Exam"),
    ("What is the difference between TRUNCATE and DELETE in SQL?",
     ["DELETE is a DML statement that removes rows one by one and can be rolled back; TRUNCATE is a DDL statement that deallocates data pages quickly and resets auto-increments", "TRUNCATE deletes the table schema entirely", "DELETE cannot use a WHERE clause", "TRUNCATE only works on temporary tables"], 0,
     "DELETE logs row deletions individually and fires triggers; TRUNCATE deallocates table extents directly in metadata, making it faster but non-row-selective.", "Medium", "SQL", "Previous Exam"),
    ("What does a Clustered Index do to the physical storage of rows in a database table?",
     ["Stores index keys in a separate file without altering table storage", "Physically sorts and stores the actual table data rows in the order of the clustered index key", "Encrypts table data using AES-256", "Creates an in-memory hash map"], 1,
     "A table can have only one clustered index because it dictates the physical on-disk sorting order of data rows.", "Medium", "Databases", "Previous Exam"),

    # 11-20
    ("What does the Second Normal Form (2NF) require beyond satisfying 1NF?",
     ["No multi-valued dependencies", "No partial functional dependencies of non-prime attributes on any candidate key", "All columns must be integers", "Every determinant must be a candidate key"], 1,
     "2NF requires that the relation be in 1NF and that every non-key attribute is fully functionally dependent on the primary key, eliminating partial dependencies.", "Medium", "Databases", "Previous Exam"),
    ("What does Third Normal Form (3NF) require beyond 2NF?",
     ["No transitive functional dependencies (no non-prime attribute depends on another non-prime attribute)", "All tables must have at least 3 rows", "Every table must have a foreign key", "No composite primary keys allowed"], 0,
     "3NF eliminates transitive dependencies: non-prime attributes must depend directly on the candidate key, not through other non-prime attributes.", "Medium", "Databases", "Previous Exam"),
    ("In Two-Phase Locking (2PL), what occurs during the 'shrinking phase'?",
     ["The transaction may acquire new locks but cannot release any", "The transaction may release locks, but can acquire NO new locks", "The database shrinks disk files", "All locks are converted to exclusive locks"], 1,
     "Under 2PL, once a transaction releases its first lock, it enters the shrinking phase and is strictly prohibited from acquiring any new locks.", "Hard", "Databases", "Previous Exam"),
    ("What is the Strict Two-Phase Locking (Strict 2PL) protocol?",
     ["All exclusive (write) locks acquired by a transaction must be held until the transaction explicitly commits or aborts", "Transactions are limited to 2 seconds", "No shared locks are permitted", "Transactions must lock the entire database"], 0,
     "Strict 2PL holds all exclusive write locks until transaction completion (COMMIT/ROLLBACK), preventing cascading aborts.", "Hard", "Databases", "Previous Exam"),
    ("What is the Write-Ahead Logging (WAL) protocol in database management systems?",
     ["Log records describing changes must be flushed to persistent storage before the corresponding data pages are written to disk", "All queries are logged to text files for auditing", "Writing data only ahead of schedule", "Backing up tables to tape drives"], 0,
     "WAL dictates that redo/undo log entries must hit non-volatile disk before dirty database pages are written, guaranteeing crash recoverability.", "Hard", "Databases", "Previous Exam"),
    ("What is the difference between UNION and UNION ALL in SQL?",
     ["UNION removes duplicate rows from the combined result set, whereas UNION ALL retains all duplicates and runs faster", "UNION ALL only works on numerical columns", "UNION can only join two tables", "UNION ALL is an aggregate function"], 0,
     "UNION performs an internal distinct/sort operation to eliminate duplicate tuples; UNION ALL simply concatenates result sets without deduplication.", "Easy", "SQL", "Previous Exam"),
    ("Which SQL command is categorized as Data Definition Language (DDL)?",
     ["INSERT INTO", "ALTER TABLE", "UPDATE", "GRANT"], 1,
     "ALTER TABLE defines or modifies schema structures, classifying it as DDL. INSERT and UPDATE are DML; GRANT is DCL.", "Easy", "SQL", "Previous Exam"),
    ("What is a Correlated Subquery in SQL?",
     ["A subquery that can be executed independently once before the outer query", "A subquery that references columns from the outer query, evaluating once for each row processed by the outer query", "A subquery that returns multiple columns in the SELECT clause", "A subquery inside an INSERT statement"], 1,
     "A correlated subquery depends on values from the outer query and must be evaluated repeatedly for each candidate row of the outer query.", "Medium", "SQL", "Previous Exam"),
    ("What is the purpose of an SQL View?",
     ["A virtual table based on the result set of a stored SQL statement, providing security, abstraction, and simplified queries", "A tool for visualizing database ER diagrams", "A physical backup stored in cloud storage", "An index that speeds up INSERT statements"], 0,
     "A view is a stored virtual query representation presenting tailored data perspectives without storing duplicate physical data rows (unless materialized).", "Easy", "Databases", "Previous Exam"),
    ("What is a Materialized View compared to a standard View?",
     ["A view whose underlying query result is physically computed and stored on disk, requiring refresh strategies when base data changes", "A view that only contains images", "A temporary table that drops after every query", "A view that cannot be indexed"], 0,
     "Materialized views persist query outputs physically on disk, allowing fast querying at the expense of periodic refresh overhead.", "Medium", "Databases", "Previous Exam"),

    # 21-30
    ("In database recovery, what does a checkpoint do?",
     ["Forces all dirty in-memory database buffers and log records to persistent disk, marking a point before which recovery logs need not be inspected", "Halts the database permanently", "Checks for syntax errors in stored procedures", "Validates user passwords"], 0,
     "Checkpoints flush memory state to disk, limiting the volume of transaction log records that must be replayed during crash recovery.", "Hard", "Databases", "Previous Exam"),
    ("In Armstrong's Axioms for functional dependencies, what is the Reflexivity rule?",
     ["If Y is a subset of X, then X -> Y", "If X -> Y, then XZ -> YZ", "If X -> Y and Y -> Z, then X -> Z", "If X -> Y, then Y -> X"], 0,
     "Reflexivity states that any attribute set functionally determines any of its own subsets (i.e., if Y <= X, then X -> Y).", "Medium", "Databases", "Previous Exam"),
    ("What is the Transitivity rule in Armstrong's Axioms?",
     ["If X -> Y and Y -> Z, then X -> Z", "If X -> Y, then Y -> X", "If X -> Y, then XZ -> YZ", "If X -> Y and X -> Z, then X -> YZ"], 0,
     "Transitivity asserts that if attribute set X determines Y, and Y determines Z, then X directly determines Z.", "Easy", "Databases", "Previous Exam"),
    ("What does the database constraint 'ON DELETE CASCADE' accomplish?",
     ["Automatically deletes dependent child rows in a foreign key table when the referenced parent row is deleted", "Prevents deletion of parent rows", "Sets child foreign keys to NULL", "Deletes all tables in the database"], 0,
     "ON DELETE CASCADE propagates parent deletions down to referencing foreign key rows, maintaining referential integrity automatically.", "Easy", "SQL", "Previous Exam"),
    ("What is the result of any arithmetic operation or comparison with NULL in SQL (e.g., 5 + NULL, NULL = NULL)?",
     ["Returns 0", "Returns FALSE", "Returns NULL (or UNKNOWN in three-valued boolean logic)", "Throws a fatal runtime syntax exception"], 2,
     "In SQL's three-valued logic, NULL represents unknown data; any scalar operation involving NULL evaluates to NULL, and boolean comparisons evaluate to UNKNOWN.", "Medium", "SQL", "Previous Exam"),
    ("How do you correctly check for NULL values in an SQL WHERE clause?",
     ["WHERE column = NULL", "WHERE column == NULL", "WHERE column IS NULL", "WHERE column.isNull()"], 2,
     "Because NULL represents an unknown value, direct equality (=) fails; SQL requires the IS NULL or IS NOT NULL operators.", "Easy", "SQL", "Previous Exam"),
    ("What is a Candidate Key in relational database theory?",
     ["A superkey with no redundant attributes (a minimal superkey capable of uniquely identifying any tuple in a relation)", "Any column with integer data types", "A foreign key pointing to another database", "The first column defined in a CREATE TABLE script"], 0,
     "A candidate key is a minimal set of attributes that uniquely distinguishes every tuple in a relation.", "Medium", "Databases", "Previous Exam"),
    ("What is a Primary Key?",
     ["A candidate key officially chosen by the database designer to uniquely identify tuples in a relation, forbidding NULL values", "The largest column in the table", "A key generated by hashing passwords", "A composite foreign key"], 0,
     "A primary key is the designated unique identifier for rows in a table; it strictly enforces uniqueness and non-nullability.", "Easy", "Databases", "Previous Exam"),
    ("What is an Alternate Key?",
     ["Any candidate key that was not chosen as the primary key", "A backup key kept on paper", "A primary key in another table", "A key that changes daily"], 0,
     "Candidate keys not selected as the primary key are designated as alternate (secondary) candidate keys.", "Easy", "Databases", "Previous Exam"),
    ("What is a Superkey?",
     ["Any set of attributes that uniquely identifies a tuple within a relation (which may include redundant attributes)", "A key that bypasses database passwords", "A key with administrator privileges", "A primary key combined with all foreign keys"], 0,
     "A superkey is any attribute set whose values uniquely identify table tuples; candidate keys are minimal superkeys.", "Medium", "Databases", "Previous Exam"),

    # 31-40
    ("In the CAP theorem for distributed data stores, what does 'P' represent?",
     ["Performance", "Partition Tolerance (the system continues to operate despite arbitrary network message drops or partitions)", "Persistence", "Parallelism"], 1,
     "Partition Tolerance guarantees that the distributed cluster continues to function even when network communication breaks between nodes.", "Medium", "Databases", "Previous Exam"),
    ("According to the CAP theorem, what trade-off must a distributed system make in the presence of a network partition?",
     ["It must choose between Consistency (all nodes see identical data) and Availability (every request receives a response)", "It must shut down all storage disks", "It must convert to relational SQL", "It loses all stored data"], 0,
     "Eric Brewer's CAP theorem proves that when network partitions occur, a distributed database must choose either Consistency or Availability.", "Medium", "Databases", "Previous Exam"),
    ("Which type of NoSQL database is MongoDB categorized as?",
     ["Key-Value store", "Document store (storing BSON documents with dynamic schemas)", "Wide-column store", "Graph database"], 1,
     "MongoDB stores data as flexible, self-describing JSON-like BSON documents, making it a document-oriented database.", "Easy", "Databases", "Previous Exam"),
    ("Which NoSQL database model is specifically optimized for storing highly interconnected entities and traversing relationships (e.g., Neo4j)?",
     ["Graph database", "Document database", "Columnar database", "Object-relational database"], 0,
     "Graph databases represent nodes and edges natively, allowing rapid relationship traversals without expensive multi-table joins.", "Easy", "Databases", "Previous Exam"),
    ("What is the primary operational advantage of Redis as a data store?",
     ["In-memory key-value data storage providing microsecond read/write latencies with support for rich data structures", "Storing terabytes of tabular financial records on tape", "Automatic SQL query compilation", "Replacing web browsers"], 0,
     "Redis is an in-memory key-value store supporting strings, lists, sets, and sorted sets, commonly used for caching and real-time analytics.", "Medium", "Databases", "Previous Exam"),
    ("What is a Phantom Read anomaly?",
     ["A transaction re-executes a query reading a set of rows satisfying a condition and discovers additional 'phantom' rows inserted by another committed transaction", "Reading data that vanished from disk", "Reading corrupted data blocks", "A query that runs infinitely"], 0,
     "Phantom reads occur when a transaction re-queries a range and finds new rows inserted and committed by concurrent transactions.", "Medium", "Databases", "Previous Exam"),
    ("What is a Non-Repeatable Read (Fuzzy Read) anomaly?",
     ["A transaction reads a row, another transaction updates or deletes that row and commits, and the first transaction rereads the row finding altered values", "A transaction crashing repeatedly", "An index failing to update", "A query returning NULL twice"], 0,
     "A non-repeatable read occurs when data within an already-read row is modified by another transaction before the current transaction completes.", "Medium", "Databases", "Previous Exam"),
    ("What is the Lost Update anomaly?",
     ["Two concurrent transactions read the same data and calculate updates; the second transaction overwrites the first transaction's update without incorporating it", "A hard drive losing written files", "A database server running out of disk space", "Dropping a table accidentally"], 0,
     "Lost updates occur when concurrent transactions overwrite each other's updates blindly because neither locked the row during computation.", "Medium", "Databases", "Previous Exam"),
    ("In SQL, what does the COUNT(*) function return?",
     ["The total number of rows in the table or group, including rows with NULL values", "Only rows where all columns are non-NULL", "The sum of all integer columns", "The execution time of the query"], 0,
     "COUNT(*) counts all rows meeting the criteria regardless of NULL values, whereas COUNT(column_name) ignores NULLs in that column.", "Easy", "SQL", "Previous Exam"),
    ("What is the result of the SQL expression: SELECT AVG(val) FROM (SELECT 10 AS val UNION ALL SELECT NULL UNION ALL SELECT 20 AS val) t;",
     ["15", "10", "NULL", "30"], 0,
     "Standard SQL aggregate functions (except COUNT(*)) completely ignore NULL values. The average of 10 and 20 is (10 + 20) / 2 = 15.", "Medium", "SQL", "Previous Exam"),

    # 41-50
    ("What is an equi-join in relational algebra?",
     ["A theta-join where the join predicate uses only the equality operator (=)", "A join between two tables with identical row counts", "A join that produces no results", "A join that deletes duplicate columns automatically"], 0,
     "An equi-join is a join condition comparing column values from two tables using strictly the equality operator (=).", "Easy", "Databases", "Previous Exam"),
    ("What distinguishes a Natural Join from an Equi-Join?",
     ["A natural join automatically joins tables on all columns with matching names and eliminates duplicate join columns from the output", "A natural join allows inequality conditions", "A natural join creates temporary tables", "A natural join does not require primary keys"], 0,
     "Natural Join implicitly matches all columns sharing identical names across both relations and outputs only a single copy of each matched column.", "Medium", "Databases", "Previous Exam"),
    ("What is a Cross Join in SQL?",
     ["Produces the Cartesian product of the two tables, combining every row from the first table with every row from the second table", "Joins tables on primary key equals foreign key", "Filters out non-matching rows", "Inverts table rows into columns"], 0,
     "CROSS JOIN creates a Cartesian product; joining a table of 10 rows with a table of 5 rows produces 50 output rows.", "Easy", "SQL", "Previous Exam"),
    ("What does a LEFT OUTER JOIN return?",
     ["All rows from the left table, along with matching rows from the right table, filling with NULL where right table matches are absent", "Only rows that match in both tables", "All rows from the right table only", "An empty result set if matches fail"], 0,
     "LEFT JOIN preserves all records from the left relation, padding right-side attributes with NULL when no matching tuple exists.", "Easy", "SQL", "Previous Exam"),
    ("What is a Self Join in SQL?",
     ["A join where a table is joined with itself by assigning different alias names to the same table", "A query that updates itself", "A recursive function that halts automatically", "A join between two identical databases"], 0,
     "A self-join joins a table to itself using aliases (e.g., matching employees to their managers within the same employee table).", "Easy", "SQL", "Previous Exam"),
    ("In database indexing, what is a Non-Clustered (Secondary) Index?",
     ["An index structure stored separately from table data, containing index key copies pointing back to row locations (heap RID or clustered key)", "An index that only sorts odd numbers", "An index that disables table updates", "A database without primary keys"], 0,
     "A non-clustered index maintains a separate B-tree whose leaf nodes hold row locators pointing to the actual data storage.", "Medium", "Databases", "Previous Exam"),
    ("What is a Composite Index in SQL?",
     ["An index built on two or more columns of a table together", "An index combining hash and B-tree simultaneously", "An index stored across multiple hard drives", "An encrypted index"], 0,
     "A composite (compound) index indexes multiple columns simultaneously, accelerating queries filtering on the leftmost prefix of those columns.", "Medium", "Databases", "Previous Exam"),
    ("What is the Leftmost Prefix Rule in composite indexing?",
     ["A composite index on (A, B, C) can only be used by queries that filter by column A, or (A, B), or (A, B, C), but not B or C alone", "The index only searches left-handed rows", "Columns must start with the letter A", "Indexes are sorted from left to right"], 0,
     "Composite B-tree indexes require the leading (leftmost) column to be present in query predicates to navigate the tree efficiently.", "Hard", "Databases", "Previous Exam"),
    ("What is a database transaction Savepoint?",
     ["An intermediate marker within a transaction allowing partial rollback to that point without aborting the entire transaction", "A scheduled backup on external tape", "The primary key of the transaction table", "A hardware RAID snapshot"], 0,
     "SAVEPOINT creates a checkpoint within a transaction; ROLLBACK TO SAVEPOINT undoes changes made after the savepoint while keeping earlier work.", "Medium", "SQL", "Previous Exam"),
    ("What is the difference between DDL and DML in SQL?",
     ["DDL defines and modifies database structures and schemas; DML manipulates and queries the actual data tuples within those schemas", "DDL is used by users, DML by admins", "DDL commands can always be rolled back in MySQL", "DML creates tables, DDL inserts rows"], 0,
     "DDL (Data Definition Language) creates/alters schemas (CREATE, DROP, ALTER); DML (Data Manipulation Language) manages rows (SELECT, INSERT, UPDATE, DELETE).", "Easy", "Databases", "Previous Exam"),

    # 51-60
    ("Which SQL keyword ensures that a column cannot contain duplicate values while permitting a single NULL value in standard relational systems?",
     ["PRIMARY KEY", "UNIQUE", "NOT NULL", "CHECK"], 1,
     "UNIQUE enforces that all non-null values in the column are distinct; unlike PRIMARY KEY, it permits NULL values.", "Easy", "SQL", "Previous Exam"),
    ("What is the function of the SQL CHECK constraint?",
     ["Enforce that all values entered in a column satisfy a specific Boolean condition (e.g., age >= 18)", "Verify user credit cards", "Check database hard drive sectors for errors", "Validate query execution speed"], 0,
     "The CHECK constraint limits values accepted by a column based on a defined predicate condition.", "Easy", "SQL", "Previous Exam"),
    ("In relational algebra, what does the Projection operator (pi) do?",
     ["Selects specified columns (attributes) from a relation and discards all others, removing duplicate tuples in pure theory", "Filters rows based on a WHERE condition", "Combines two tables vertically", "Sorts rows in ascending order"], 0,
     "Projection (pi) extracts vertical slices of a relation, selecting specified columns and discarding the rest.", "Easy", "Databases", "Previous Exam"),
    ("In relational algebra, what does the Selection operator (sigma) do?",
     ["Selects horizontal rows (tuples) that satisfy a specified predicate condition", "Chooses which database to open", "Picks columns for display", "Generates primary keys"], 0,
     "Selection (sigma) extracts a horizontal subset of tuples from a relation satisfying a specified condition.", "Easy", "Databases", "Previous Exam"),
    ("What is database normalization designed to minimize?",
     ["Data redundancy and update/insertion/deletion anomalies", "The speed of SQL SELECT statements", "The size of database RAM caches", "The number of primary keys"], 0,
     "Normalization structures relational schemas to reduce redundant data duplication and eliminate modification anomalies.", "Easy", "Databases", "Previous Exam"),
    ("What is an Insertion Anomaly in an unnormalized database table?",
     ["The inability to record certain facts about an entity without artificially inserting unrelated data about another entity", "Inserting rows too fast for the hard drive", "An error caused by duplicate primary keys", "Inserting text into an integer column"], 0,
     "An insertion anomaly occurs when attributes cannot be recorded independently because the schema forces them to accompany unrelated keys.", "Medium", "Databases", "Previous Exam"),
    ("What is a Deletion Anomaly?",
     ["Deleting one fact about an entity inadvertently deletes completely unrelated facts about another entity", "Accidentally running DROP DATABASE", "A hard drive head crash during delete", "Deleting rows without WHERE clause"], 0,
     "A deletion anomaly occurs when removing a record inadvertently purges unrelated information stored exclusively in that same record.", "Medium", "Databases", "Previous Exam"),
    ("What is an Update Anomaly?",
     ["Data redundancy forces multiple rows to be updated for a single real-world change, leading to data inconsistency if some rows are missed", "Software updates breaking the database", "Updating primary keys to negative numbers", "CPU clock updates during writes"], 0,
     "An update anomaly arises when redundant copies of a value require multi-record updates, creating inconsistent records if partially updated.", "Medium", "Databases", "Previous Exam"),
    ("What is a partial functional dependency in relational database design?",
     ["A functional dependency where a non-prime attribute depends on only a proper subset of a composite candidate key", "A dependency that works only on weekdays", "A dependency between two columns in different tables", "A query that returns half the rows"], 0,
     "A partial dependency occurs when an attribute depends on part of a composite primary key rather than the entire composite key (violating 2NF).", "Medium", "Databases", "Previous Exam"),
    ("What is a transitive functional dependency?",
     ["An indirect functional dependency where attribute X determines Y, and Y determines Z, making Z depend on X through Y", "A dependency that transfers across network routers", "A dependency that converts strings to numbers", "A circular foreign key reference"], 0,
     "A transitive dependency occurs when X -> Y and Y -> Z (where Y is not a candidate key and Y does not determine X), violating 3NF.", "Medium", "Databases", "Previous Exam"),

    # 61-70
    ("What is the Wait-Die deadlock prevention scheme in database transactions?",
     ["Non-preemptive scheme where an older transaction waits for a younger transaction holding a lock, but a younger transaction requesting a lock held by an older transaction dies (aborts)", "A scheme where all transactions wait until midnight", "Killing transactions that run longer than 5 seconds", "A hardware watchdog timer"], 0,
     "In Wait-Die, if older requests younger: older waits. If younger requests older: younger dies (aborts and restarts with its original timestamp).", "Hard", "Databases", "Previous Exam"),
    ("What is the Wound-Wait deadlock prevention scheme?",
     ["Preemptive scheme where an older transaction preempts ('wounds') a younger transaction holding a lock, while a younger transaction waits for an older transaction", "Transactions are killed if memory runs low", "Transactions wait for network packets", "Older transactions abort immediately"], 0,
     "In Wound-Wait, if older requests younger: older wounds (preempts/aborts) younger. If younger requests older: younger waits.", "Hard", "Databases", "Previous Exam"),
    ("What is a Deadlock in database transactions?",
     ["A state where two or more transactions are permanently blocked, each waiting for locks held by the other in a circular chain", "A corrupted database file that cannot be opened", "A query that executes for more than 1 minute", "A user forgetting their database password"], 0,
     "Deadlock occurs when two or more transactions form a cycle in the wait-for graph, each waiting for resources held by another.", "Easy", "Databases", "Previous Exam"),
    ("How do database engines typically detect transaction deadlocks automatically?",
     ["By maintaining a Wait-For Graph (WFG) and running background cycle-detection algorithms", "By monitoring database server temperature", "By checking the operating system process list", "By counting the number of SELECT statements"], 0,
     "DBMS engines construct a Wait-For Graph of transactions and resources; detecting a directed cycle reveals a deadlock requiring transaction rollback.", "Hard", "Databases", "Previous Exam"),
    ("What is an entity-relationship (ER) diagram?",
     ["A conceptual graphical model depicting entities, their attributes, and relationships in a problem domain", "A physical layout of server racks", "A flow chart of assembly instructions", "A network topology diagram"], 0,
     "ER diagrams model conceptual database structures using entities (rectangles), attributes (ovals), and relationships (diamonds).", "Easy", "Databases", "Previous Exam"),
    ("In ER modeling, what is a Weak Entity?",
     ["An entity that lacks sufficient attributes to form its own primary key and depends on an identifying relationship with an owner entity for identification", "An entity with only one attribute", "An entity stored on a slow disk", "An entity that allows NULL in all columns"], 0,
     "Weak entities cannot be uniquely identified by their own attributes alone; their key is formed by combining a discriminator with the owner entity's primary key.", "Medium", "Databases", "Previous Exam"),
    ("What is the cardinality of a database relationship (e.g., 1:1, 1:N, M:N)?",
     ["The number of entity instances of one entity set that can be associated with entity instances of another entity set", "The number of columns in a table", "The size of a database file in gigabytes", "The number of index levels"], 0,
     "Relationship cardinality expresses the numerical ratio of entity associations: One-to-One (1:1), One-to-Many (1:N), or Many-to-Many (M:N).", "Easy", "Databases", "Previous Exam"),
    ("How is a Many-to-Many (M:N) relationship between two entities physically implemented in a relational database schema?",
     ["By introducing an associative (junction/bridge) table containing foreign keys referencing the primary keys of both participating tables", "By adding 100 columns to both tables", "By merging both tables into one giant table", "M:N relationships cannot be modeled in relational databases"], 0,
     "Relational schemas resolve M:N relationships using an intermediate junction table containing foreign keys to both parent tables as a composite key.", "Easy", "Databases", "Previous Exam"),
    ("What does the SQL statement SELECT DISTINCT do?",
     ["Filters out duplicate rows from the query output so that all returned tuples are unique", "Sorts the output alphabetically", "Selects only rows with primary keys", "Highlights distinct colors in the database console"], 0,
     "DISTINCT eliminates duplicate tuples from query results, ensuring every returned record is unique across selected columns.", "Easy", "SQL", "Previous Exam"),
    ("In SQL, what is the default sorting order when ORDER BY is used without specifying ASC or DESC?",
     ["ASC (Ascending)", "DESC (Descending)", "Random", "Order of insertion"], 0,
     "The default sort order in SQL ORDER BY clauses is ascending (ASC).", "Easy", "SQL", "Previous Exam"),

    # 71-80
    ("What does the SQL LIKE operator with wildcard '%' represent?",
     ["Matches zero, one, or multiple arbitrary characters", "Matches exactly one character", "Matches only numbers", "Represents modulus arithmetic"], 0,
     "In SQL pattern matching, '%' matches zero or more characters; '_' matches exactly one character.", "Easy", "SQL", "Previous Exam"),
    ("What does the SQL wildcard '_' (underscore) match in a LIKE predicate?",
     ["Matches exactly one single character", "Matches zero or more characters", "Matches spaces only", "Escapes special characters"], 0,
     "The underscore wildcard '_' matches exactly one single character in standard SQL LIKE pattern evaluations.", "Easy", "SQL", "Previous Exam"),
    ("What is a database Stored Procedure?",
     ["A precompiled collection of SQL statements and procedural logic stored in the database catalog that can be invoked by name", "A backup copy of database files", "A manual typed by database administrators", "A hardware testing routine in BIOS"], 0,
     "Stored procedures are precompiled database routines encapsulating complex business logic, reducing network round trips and enhancing security.", "Easy", "Databases", "Previous Exam"),
    ("What is an SQL Trigger?",
     ["A procedural code block executed automatically by the database engine in response to specific DML events (INSERT, UPDATE, DELETE) on a table", "A hardware button that reboots the server", "A command that starts a database backup", "A syntax error detector"], 0,
     "Triggers are event-driven routines that automatically fire before or after data modification statements to enforce integrity or audit changes.", "Easy", "Databases", "Previous Exam"),
    ("What is the difference between a Stored Procedure and a User-Defined Function (UDF) in SQL?",
     ["A UDF must return a value and cannot execute transaction control (COMMIT/ROLLBACK), whereas a procedure can execute transactions and return zero or multiple values", "UDFs can modify table schemas while procedures cannot", "UDFs only run on Sundays", "There is no difference between them"], 0,
     "UDFs return scalar values or tables and can be called directly within SELECT expressions; stored procedures execute administrative tasks and transactions independently.", "Medium", "Databases", "Previous Exam"),
    ("What does the SQL COALESCE() function do?",
     ["Returns the first non-NULL expression from its list of arguments", "Combines two strings together", "Calculates standard deviation", "Counts non-null columns"], 0,
     "COALESCE(arg1, arg2, ...) evaluates its parameters in order and returns the first non-NULL value encountered.", "Easy", "SQL", "Previous Exam"),
    ("In SQL, what is the NULLIF(a, b) function used for?",
     ["Returns NULL if arguments a and b are equal; otherwise returns a", "Converts NULL to 0", "Throws an error if either value is NULL", "Returns the larger of two values"], 0,
     "NULLIF(a, b) returns NULL if a = b; otherwise it returns a (frequently used to prevent division-by-zero: val / NULLIF(divisor, 0)).", "Medium", "SQL", "Previous Exam"),
    ("What is a recursive query in SQL, and which clause is standardly used to define it?",
     ["A query that references its own output, defined using a Common Table Expression with WITH RECURSIVE", "A query with an infinite loop", "A subquery in the WHERE clause", "A query executed by two users simultaneously"], 0,
     "WITH RECURSIVE creates Common Table Expressions (CTEs) that iterate over hierarchical or graph structures (such as organizational trees).", "Hard", "SQL", "Previous Exam"),
    ("What is a database Cursor in procedural SQL?",
     ["A database control structure that enables sequential, row-by-row traversal and processing of a query result set", "The mouse pointer on the database GUI", "An index on cursor keys", "A hardware register inside the CPU"], 0,
     "Cursors provide procedural row-by-row navigation through query result sets when set-based operations cannot express the required logic.", "Medium", "Databases", "Previous Exam"),
    ("What is database Sharding?",
     ["A horizontal partitioning architecture where subsets of table rows are distributed across multiple independent database servers", "Breaking database disks with a hammer", "Compressing database logs", "Creating redundant indexes on every column"], 0,
     "Sharding partitions rows across multiple distinct database instances based on a shard key to scale write throughput and storage horizontally.", "Medium", "Databases", "Previous Exam"),

    # 81-90
    ("What is the difference between horizontal partitioning and vertical partitioning of tables?",
     ["Horizontal partitioning divides rows across partitions; vertical partitioning splits table columns into distinct tables sharing the same primary key", "Horizontal partitioning is for SQL, vertical is for NoSQL", "Vertical partitioning only works on hard drives", "There is no functional difference"], 0,
     "Horizontal partitioning distributes row subsets (e.g., by date or ID); vertical partitioning separates columns into narrower tables to optimize I/O.", "Medium", "Databases", "Previous Exam"),
    ("What is a database Query Optimizer?",
     ["The DBMS component that analyzes SQL queries and generates the most cost-effective execution plan based on statistics, indexes, and join algorithms", "A program that reformats SQL indentation", "A human DBA tuning servers", "A hardware chip on the motherboard"], 0,
     "The query optimizer evaluates alternative execution plans (index scans vs table scans, nested loops vs hash joins) to execute queries with minimal cost.", "Medium", "Databases", "Previous Exam"),
    ("Which join algorithm is typically chosen by a query optimizer when joining two large tables with no pre-existing indexes on the join columns?",
     ["Hash Join", "Nested Loop Join", "Single Index Seek", "Cross Multiply Scan"], 0,
     "Hash Join builds an in-memory hash table on the smaller relation and probes it with the larger relation, providing O(M + N) performance.", "Hard", "Databases", "Previous Exam"),
    ("When is a Nested Loop Join most efficient in a relational query engine?",
     ["When the outer table is small and the inner table has an efficient index on the join key", "When both tables have over 100 million unindexed rows", "When joining tables across different physical disks", "When sorting descending data"], 0,
     "Nested loops excel when one table is small and each iteration can perform a fast index seek into the inner relation.", "Medium", "Databases", "Previous Exam"),
    ("What is an Index Seek versus an Index Scan in database execution plans?",
     ["An Index Seek navigates B-tree levels directly to locate matching rows using the key; an Index Scan reads all leaf pages of the index sequentially", "An Index Seek reads all table data; an Index Scan reads one row", "Index Seek only works on integers", "Index Scan is always faster than Seek"], 0,
     "Index Seek traverses the tree hierarchy to find specific key values in logarithmic time; Index Scan traverses the entire index leaf sequence.", "Medium", "Databases", "Previous Exam"),
    ("What does a Table Scan (Full Table Scan) mean in an execution plan?",
     ["The database scans every single data page of the table sequentially from start to end because no suitable index could be used", "Scanning a printed database schema with a scanner", "Checking table metadata in memory", "Executing an index seek on the primary key"], 0,
     "A full table scan reads every block of a table, often a sign of missing indexes or non-sargable query predicates.", "Easy", "Databases", "Previous Exam"),
    ("What is a 'sargable' predicate in SQL query optimization?",
     ["A Search-Argument-Able predicate written in a way that allows the query engine to utilize an index seek (e.g., avoiding functions on indexed columns)", "A predicate that tests for strings", "A predicate that uses aggregate functions", "A syntax error in SQL"], 0,
     "A sargable predicate (Search Argument Able) allows index seeks; wrapping columns in functions (e.g., WHERE YEAR(date_col) = 2024) prevents index seeks.", "Hard", "Databases", "Previous Exam"),
    ("What is database replication?",
     ["The practice of continuously copying and maintaining database objects across multiple servers to ensure high availability and read scalability", "Making duplicate backups on USB sticks", "Copying database software licenses", "Running identical queries twice"], 0,
     "Database replication syncs data from a primary node to replica nodes (synchronously or asynchronously) for failover and read load distribution.", "Easy", "Databases", "Previous Exam"),
    ("What is the difference between Synchronous and Asynchronous replication?",
     ["Synchronous commits only after replicas acknowledge writing data; asynchronous acknowledges the client immediately and syncs replicas in background", "Synchronous replication does not use network cables", "Asynchronous replication causes instant deadlocks", "Synchronous is only used on weekends"], 0,
     "Synchronous replication guarantees zero data loss (RPO=0) at the cost of write latency; asynchronous provides high write throughput with potential replication lag.", "Medium", "Databases", "Previous Exam"),
    ("What is a Write Conflict in multi-master database replication?",
     ["Two different master nodes update the exact same data row concurrently, resulting in conflicting values that must be reconciled", "A hard drive failing during write", "A syntax error during INSERT", "A user typing conflicting passwords"], 0,
     "Multi-master configurations allow writes on any node; simultaneous conflicting writes require conflict resolution strategies (e.g., Last-Write-Wins).", "Medium", "Databases", "Previous Exam"),

    # 91-100
    ("In database systems, what is a Tuple in relational model terminology?",
     ["A single row or record in a relation (table)", "A column attribute", "The name of the database table", "The data type of a field"], 0,
     "In relational formal theory: Relation = Table, Tuple = Row/Record, Attribute = Column/Field.", "Easy", "Databases", "Previous Exam"),
    ("In relational model terminology, what is an Attribute?",
     ["A named column of a relation representing a specific property of the entity", "A row in a table", "The database password", "The total size of RAM"], 0,
     "An attribute corresponds to a column in a relational table, taking values from a designated domain.", "Easy", "Databases", "Previous Exam"),
    ("What is the Degree of a relation in relational algebra?",
     ["The total number of attributes (columns) comprising the relation", "The total number of rows in the table", "The temperature of the server CPU", "The number of foreign keys"], 0,
     "Degree represents the number of attributes (columns); Cardinality represents the number of tuples (rows).", "Easy", "Databases", "Previous Exam"),
    ("What is the Cardinality of a relation in relational algebra?",
     ["The total number of tuples (rows) present in the relation", "The number of columns", "The maximum allowed size of the table", "The number of primary keys"], 0,
     "Cardinality is the total count of tuples (rows) currently stored in the relation.", "Easy", "Databases", "Previous Exam"),
    ("What is the Domain of an attribute?",
     ["The set of all permissible atomic values that can be assigned to that attribute", "The internet website domain of the company", "The name of the primary key index", "The physical storage folder on disk"], 0,
     "A domain defines the legal data type, format, and range of values an attribute may take.", "Easy", "Databases", "Previous Exam"),
    ("What is Lossless-Join Decomposition in database normalization?",
     ["Decomposing a relation R into sub-relations R1 and R2 such that natural joining R1 and R2 reconstructs R exactly without generating spurious tuples", "Compressing a table without loss of audio", "Joining two tables without using primary keys", "Deleting empty columns"], 0,
     "A decomposition is lossless if R1 natural join R2 yields original relation R without phantom or spurious rows (guaranteed if R1 intersection R2 -> R1 or R2).", "Hard", "Databases", "Previous Exam"),
    ("What is Dependency Preservation in schema decomposition?",
     ["Ensuring that all functional dependencies of the original relation can be checked using sub-relations without having to compute expensive joins", "Preventing users from modifying tables", "Keeping primary keys in one file", "Enforcing foreign keys across servers"], 0,
     "Dependency preservation ensures all original functional dependencies remain verifiable within individual decomposed tables without requiring joins.", "Hard", "Databases", "Previous Exam"),
    ("What is a Surrogate Key in database modeling?",
     ["An artificial, system-generated primary key (such as an auto-increment integer or UUID) having no intrinsic business meaning", "A natural key extracted from passport numbers", "A foreign key pointing to external systems", "A password hash"], 0,
     "Surrogate keys (e.g., auto-incrementing ID) simplify relations and insulate the schema from business logic changes in natural keys.", "Easy", "Databases", "Previous Exam"),
    ("What is a Natural Key in database modeling?",
     ["A primary key composed of real-world attributes with inherent business meaning (e.g., Social Security Number, ISBN)", "An auto-incrementing integer starting at 1", "A random string of bytes", "A key that requires no indexes"], 0,
     "Natural keys are real-world identifier attributes that exist intrinsically outside the database system.", "Easy", "Databases", "Previous Exam"),
    ("What does the SQL statement GRANT SELECT, INSERT ON employees TO 'analyst_role'; represent?",
     ["Data Control Language (DCL) statement assigning permissions to a user role", "Data Definition Language altering table schema", "Data Manipulation Language inserting rows", "Transaction Control committing changes"], 0,
     "GRANT and REVOKE are DCL statements used to assign and retract database privileges and roles.", "Easy", "SQL", "Previous Exam")
]

print(f"Total Part 4 questions: {len(questions)}")
assert len(questions) == 100, f"Expected 100 questions, got {len(questions)}"

part4_data = []
for i, q in enumerate(questions):
    qid = f"p4-q{i+1}"
    part4_data.append({
        "id": qid,
        "part": 4,
        "topic": q[5],
        "difficulty": q[4],
        "question": q[0],
        "choices": q[1],
        "options": q[1],
        "correctAnswer": q[2],
        "explanation": q[3],
        "source": q[6]
    })

out_file = os.path.join(os.getcwd(), 'src', 'data', 'parts', 'part4.ts')
os.makedirs(os.path.dirname(out_file), exist_ok=True)
with open(out_file, 'w') as f:
    f.write("import { Question } from '../../types';\n\n")
    f.write("export const PART_4_QUESTIONS: Question[] = ")
    json.dump(part4_data, f, indent=2)
    f.write(";\n")

print("Wrote Part 4 successfully to src/data/parts/part4.ts")
